-- ------------------------------
-- desc: generated by xls2data.py
-- source: 水手解雇基础数值.xls
-- sheet: 解雇奖励
-- ------------------------------


local fire_reward = {
	[1] = {
		['exp_book'] = 0,
		['star'] = 0,
	},
	[2] = {
		['exp_book'] = 1,
		['star'] = 3,
	},
	[3] = {
		['exp_book'] = 2,
		['star'] = 15,
	},
	[4] = {
		['exp_book'] = 4,
		['star'] = 75,
	},
	[5] = {
		['exp_book'] = 10,
		['star'] = 375,
	},
	[6] = {
		['exp_book'] = 20,
		['star'] = 1875,
	},
}

return fire_reward