return 
{
[1] = {
    ['explain'] = T('寻宝'),
    ['job'] = 'watch',
    ['msg'] = T('发现宝物的几率。'),
    ['name'] = T('瞭望手'),
    ['skill'] = T('瞭望手技能'),
    ['skillRes'] = '#skill_1066.png',
    },
[2] = {
    ['explain'] = T('耐久'),
    ['job'] = 'captain',
    ['msg'] = T('水手上限。'),
    ['name'] = T('大副'),
    ['skill'] = T('大副技能'),
    ['skillRes'] = '#skill_1002.png',
    },
[3] = {
    ['explain'] = T('远程'),
    ['job'] = 'guns',
    ['msg'] = T('远程伤害。'),
    ['name'] = T('火炮手'),
    ['skill'] = T('火炮手技能'),
    ['skillRes'] = '#skill_1018.png',
    },
[4] = {
    ['explain'] = T('近战'),
    ['job'] = 'sailor',
    ['msg'] = T('近战伤害和水手血量。'),
    ['name'] = T('水手长'),
    ['skill'] = T('水手长技能'),
    ['skillRes'] = '#skill_1034.png',
    },
[5] = {
    ['explain'] = T('速度'),
    ['job'] = 'control',
    ['msg'] = T('船舶速度。'),
    ['name'] = T('操控师'),
    ['skill'] = T('操控师技能'),
    ['skillRes'] = '#skill_1110.png',
    },
[6] = {
    ['explain'] = T('防御'),
    ['job'] = 'measure',
    ['msg'] = T('船舶耐久。'),
    ['name'] = T('木工'),
    ['skill'] = T('木工技能'),
    ['skillRes'] = '#skill_1058.png',
    },
[7] = {
    ['explain'] = T('利润'),
    ['job'] = 'account',
    ['msg'] = T('交易利润。'),
    ['name'] = T('会计师'),
    ['skill'] = T('会计师技能'),
    ['skillRes'] = '#skill_1082.png',
    },
}