-- ------------------------------
-- desc: generated by xls2data.py
-- source: 水手洗练消耗数值.xlsx
-- sheet: 水手洗练
-- ------------------------------


local sailor_train_info = {
	[6] = {
		['star'] = 1,
	},
	[5] = {
		['star'] = 1,
	},
	[4] = {
		['star'] = 1,
	},
	[3] = {
		['star'] = 1,
	},
	[2] = {
		['star'] = 1,
	},
}

return sailor_train_info