-- ------------------------------
-- desc: generated by xls2data.py
-- source: 水手config.xls
-- sheet: 职业
-- ------------------------------


local sailor_job = {
	[1] = {
		['name'] = T('瞭望手'),
		['job'] = 'watch',
		['msg'] = T('发现宝物的几率。'),
		['skill'] = T('瞭望手技能'),
		['skillRes'] = '#skill_1066.png',
		['explain'] = T('寻宝'),
	},
	[2] = {
		['name'] = T('大副'),
		['job'] = 'captain',
		['msg'] = T('水手上限。'),
		['skill'] = T('大副技能'),
		['skillRes'] = '#skill_1002.png',
		['explain'] = T('耐久'),
	},
	[3] = {
		['name'] = T('火炮手'),
		['job'] = 'guns',
		['msg'] = T('远程伤害。'),
		['skill'] = T('火炮手技能'),
		['skillRes'] = '#skill_1018.png',
		['explain'] = T('远程'),
	},
	[4] = {
		['name'] = T('水手长'),
		['job'] = 'sailor',
		['msg'] = T('近战伤害和水手血量。'),
		['skill'] = T('水手长技能'),
		['skillRes'] = '#skill_1034.png',
		['explain'] = T('近战'),
	},
	[5] = {
		['name'] = T('操控师'),
		['job'] = 'control',
		['msg'] = T('船舶速度。'),
		['skill'] = T('操控师技能'),
		['skillRes'] = '#skill_1110.png',
		['explain'] = T('速度'),
	},
	[6] = {
		['name'] = T('木工'),
		['job'] = 'measure',
		['msg'] = T('船舶耐久。'),
		['skill'] = T('木工技能'),
		['skillRes'] = '#skill_1058.png',
		['explain'] = T('防御'),
	},
	[7] = {
		['name'] = T('会计师'),
		['job'] = 'account',
		['msg'] = T('交易利润。'),
		['skill'] = T('会计师技能'),
		['skillRes'] = '#skill_1082.png',
		['explain'] = T('利润'),
	},
}

return sailor_job