-- ------------------------------
-- desc: generated by xls2data.py
-- source: 升星升阶解雇配置表.xlsx
-- sheet: 水手操作
-- ------------------------------


local sailor_op_config = {
	[1] = {
		['skill_solt'] = 1,
		['awake_consume_gold'] = 0,
		['upstar_consume'] = 82,
		['upstar_consume_count'] = 2,
		['upstep_consume'] = 82,
		['upstep_consume_count'] = 10,
		['awake_consume'] = 0,
		['awake_consume_count'] = 0,
	},
	[2] = {
		['skill_solt'] = 1,
		['awake_consume_gold'] = 0,
		['upstar_consume'] = 82,
		['upstar_consume_count'] = 2,
		['upstep_consume'] = 82,
		['upstep_consume_count'] = 10,
		['awake_consume'] = 0,
		['awake_consume_count'] = 0,
	},
	[3] = {
		['skill_solt'] = 1,
		['awake_consume_gold'] = 0,
		['upstar_consume'] = 83,
		['upstar_consume_count'] = 2,
		['upstep_consume'] = 83,
		['upstep_consume_count'] = 10,
		['awake_consume'] = 0,
		['awake_consume_count'] = 0,
	},
	[4] = {
		['skill_solt'] = 2,
		['awake_consume_gold'] = 0,
		['upstar_consume'] = 84,
		['upstar_consume_count'] = 2,
		['upstep_consume'] = 84,
		['upstep_consume_count'] = 10,
		['awake_consume'] = 0,
		['awake_consume_count'] = 0,
	},
	[5] = {
		['skill_solt'] = 3,
		['awake_consume_gold'] = 0,
		['upstar_consume'] = 85,
		['upstar_consume_count'] = 2,
		['upstep_consume'] = 85,
		['upstep_consume_count'] = 10,
		['awake_consume'] = 0,
		['awake_consume_count'] = 0,
	},
	[6] = {
		['skill_solt'] = 3,
		['awake_consume_gold'] = 800,
		['upstar_consume'] = 86,
		['upstar_consume_count'] = 2,
		['upstep_consume'] = 0,
		['upstep_consume_count'] = 0,
		['awake_consume'] = 50,
		['awake_consume_count'] = 1,
	},
	[7] = {
		['skill_solt'] = 3,
		['awake_consume_gold'] = 0,
		['upstar_consume'] = 86,
		['upstar_consume_count'] = 2,
		['upstep_consume'] = 0,
		['upstep_consume_count'] = 0,
		['awake_consume'] = 0,
		['awake_consume_count'] = 0,
	},
}

return sailor_op_config