-- ------------------------------
-- desc: generated by xls2data.py
-- source: 问卷调查.xls
-- sheet: 问卷调查
-- ------------------------------


local question_data = {
	[1] = {
		['qq_url'] = 'http://ue.qq.com/mur?a=survey&b=11625&c=2&d=3ce15db782067c09661d8857bebdc228',
		['wx_url'] = 'http://ue.qq.com/mur?a=survey&b=11661&c=2&d=03c5bd1edcc1ed4837be0e60a45eb986',
	},
	[25] = {
		['qq_url'] = 'http://ue.qq.com/mur?a=survey&b=11626&c=2&d=73d18ab053194916fce23f80b1e9a345',
		['wx_url'] = 'http://ue.qq.com/mur?a=survey&b=11663&c=2&d=4db3cdfcdcd77831021d587a4b79968e',
	},
}

return question_data