-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会技能-研究所.xls
-- sheet: 商会技能名字图标
-- ------------------------------


local guild_skill_info = {
	[1] = {
		['name'] = 'remote',
		['guild_skill_name'] = T('火炮战术'),
		['guild_skill_txt'] = T('远程伤害'),
		['guild_skill_icon'] = 'skill_1027.png',
		['guild_skill_desc'] = T('古老的火炮书籍，通过研究火炮的角度、抛物线以及火药的研制能极大地增加火炮的杀伤力！'),
	},
	[2] = {
		['name'] = 'melee',
		['guild_skill_name'] = T('肉搏战术'),
		['guild_skill_txt'] = T('近战伤害'),
		['guild_skill_icon'] = 'skill_1006.png',
		['guild_skill_desc'] = T('通过研究人体构造图和剑术秘籍，极大增强士兵的肌肉强度和剑术，从而大大增加舰队的近战能力。'),
	},
	[3] = {
		['name'] = 'durable',
		['guild_skill_name'] = T('耐久研究'),
		['guild_skill_txt'] = T('船舶耐久'),
		['guild_skill_icon'] = 'skill_1061.png',
		['guild_skill_desc'] = T('《鲁班造经》，船工通过研究依其指引所改造的船体，不但轻盈灵巧，而且船舶耐久大幅度增加。'),
	},
	[4] = {
		['name'] = 'defense',
		['guild_skill_name'] = T('防御研究'),
		['guild_skill_txt'] = T('船舶防御'),
		['guild_skill_icon'] = 'skill_1052.png',
		['guild_skill_desc'] = T('记载着上古大战的书籍，通过研究其摆局布阵用来招架敌人的攻击，能极大增加舰队整体的防御能力。'),
	},
	[5] = {
		['name'] = 'load',
		['guild_skill_name'] = T('货仓扩展'),
		['guild_skill_txt'] = T('载货容量'),
		['guild_skill_icon'] = 'skill_1083.png',
		['guild_skill_desc'] = T('一位传奇船工留下的改造图纸，通过研究能轻而易举地将有限的船体空间增加载货容量。'),
	},
	[6] = {
		['name'] = 'speed',
		['guild_skill_name'] = T('扬帆御风'),
		['guild_skill_txt'] = T('海上航速'),
		['guild_skill_icon'] = 'skill_1113.png',
		['guild_skill_desc'] = T('曾经驰骋大海的航海士的笔记，记载的经验足够让你从容应对暴风雨，轻松增加海上航速。'),
	},
}

return guild_skill_info