-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会技能-研究所.xls
-- sheet: 研究所等级受公会等级控制
-- ------------------------------


local guild_skill_lv_control = {
	[1] = {
		['institute_lv'] = 1,
		['guild_lv'] = 25,
		['skill_lv_limit'] = 5,
	},
	[2] = {
		['institute_lv'] = 2,
		['guild_lv'] = 30,
		['skill_lv_limit'] = 10,
	},
	[3] = {
		['institute_lv'] = 3,
		['guild_lv'] = 35,
		['skill_lv_limit'] = 15,
	},
	[4] = {
		['institute_lv'] = 4,
		['guild_lv'] = 40,
		['skill_lv_limit'] = 20,
	},
	[5] = {
		['institute_lv'] = 5,
		['guild_lv'] = 45,
		['skill_lv_limit'] = 25,
	},
	[6] = {
		['institute_lv'] = 6,
		['guild_lv'] = 50,
		['skill_lv_limit'] = 30,
	},
	[7] = {
		['institute_lv'] = 7,
		['guild_lv'] = 55,
		['skill_lv_limit'] = 35,
	},
	[8] = {
		['institute_lv'] = 8,
		['guild_lv'] = 60,
		['skill_lv_limit'] = 40,
	},
}

return guild_skill_lv_control