-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会技能-研究所.xls
-- sheet: 学习-防御
-- ------------------------------


local guild_skill_defense = {
	[1] = {
		['skill_lv'] = 1,
		['skill_add'] = '1%',
		['skill_use_contribution'] = 100,
	},
	[2] = {
		['skill_lv'] = 2,
		['skill_add'] = '2%',
		['skill_use_contribution'] = 200,
	},
	[3] = {
		['skill_lv'] = 3,
		['skill_add'] = '3%',
		['skill_use_contribution'] = 300,
	},
	[4] = {
		['skill_lv'] = 4,
		['skill_add'] = '4%',
		['skill_use_contribution'] = 400,
	},
	[5] = {
		['skill_lv'] = 5,
		['skill_add'] = '5%',
		['skill_use_contribution'] = 500,
	},
	[6] = {
		['skill_lv'] = 6,
		['skill_add'] = '6%',
		['skill_use_contribution'] = 600,
	},
	[7] = {
		['skill_lv'] = 7,
		['skill_add'] = '7%',
		['skill_use_contribution'] = 700,
	},
	[8] = {
		['skill_lv'] = 8,
		['skill_add'] = '8%',
		['skill_use_contribution'] = 800,
	},
	[9] = {
		['skill_lv'] = 9,
		['skill_add'] = '9%',
		['skill_use_contribution'] = 900,
	},
	[10] = {
		['skill_lv'] = 10,
		['skill_add'] = '10%',
		['skill_use_contribution'] = 1000,
	},
	[11] = {
		['skill_lv'] = 11,
		['skill_add'] = '11%',
		['skill_use_contribution'] = 1100,
	},
	[12] = {
		['skill_lv'] = 12,
		['skill_add'] = '12%',
		['skill_use_contribution'] = 1200,
	},
	[13] = {
		['skill_lv'] = 13,
		['skill_add'] = '13%',
		['skill_use_contribution'] = 1400,
	},
	[14] = {
		['skill_lv'] = 14,
		['skill_add'] = '14%',
		['skill_use_contribution'] = 1700,
	},
	[15] = {
		['skill_lv'] = 15,
		['skill_add'] = '15%',
		['skill_use_contribution'] = 2000,
	},
	[16] = {
		['skill_lv'] = 16,
		['skill_add'] = '16%',
		['skill_use_contribution'] = 2400,
	},
	[17] = {
		['skill_lv'] = 17,
		['skill_add'] = '17%',
		['skill_use_contribution'] = 2900,
	},
	[18] = {
		['skill_lv'] = 18,
		['skill_add'] = '18%',
		['skill_use_contribution'] = 3500,
	},
	[19] = {
		['skill_lv'] = 19,
		['skill_add'] = '19%',
		['skill_use_contribution'] = 4200,
	},
	[20] = {
		['skill_lv'] = 20,
		['skill_add'] = '20%',
		['skill_use_contribution'] = 5000,
	},
	[21] = {
		['skill_lv'] = 21,
		['skill_add'] = '21%',
		['skill_use_contribution'] = 5800,
	},
	[22] = {
		['skill_lv'] = 22,
		['skill_add'] = '22%',
		['skill_use_contribution'] = 6500,
	},
	[23] = {
		['skill_lv'] = 23,
		['skill_add'] = '23%',
		['skill_use_contribution'] = 6700,
	},
	[24] = {
		['skill_lv'] = 24,
		['skill_add'] = '24%',
		['skill_use_contribution'] = 7000,
	},
	[25] = {
		['skill_lv'] = 25,
		['skill_add'] = '25%',
		['skill_use_contribution'] = 7400,
	},
	[26] = {
		['skill_lv'] = 26,
		['skill_add'] = '26%',
		['skill_use_contribution'] = 7900,
	},
	[27] = {
		['skill_lv'] = 27,
		['skill_add'] = '27%',
		['skill_use_contribution'] = 8100,
	},
	[28] = {
		['skill_lv'] = 28,
		['skill_add'] = '28%',
		['skill_use_contribution'] = 8300,
	},
	[29] = {
		['skill_lv'] = 29,
		['skill_add'] = '29%',
		['skill_use_contribution'] = 8600,
	},
	[30] = {
		['skill_lv'] = 30,
		['skill_add'] = '30%',
		['skill_use_contribution'] = 9000,
	},
	[31] = {
		['skill_lv'] = 31,
		['skill_add'] = '31%',
		['skill_use_contribution'] = 9500,
	},
	[32] = {
		['skill_lv'] = 32,
		['skill_add'] = '32%',
		['skill_use_contribution'] = 10000,
	},
	[33] = {
		['skill_lv'] = 33,
		['skill_add'] = '33%',
		['skill_use_contribution'] = 10500,
	},
	[34] = {
		['skill_lv'] = 34,
		['skill_add'] = '34%',
		['skill_use_contribution'] = 11000,
	},
	[35] = {
		['skill_lv'] = 35,
		['skill_add'] = '35%',
		['skill_use_contribution'] = 11700,
	},
	[36] = {
		['skill_lv'] = 36,
		['skill_add'] = '36%',
		['skill_use_contribution'] = 12700,
	},
	[37] = {
		['skill_lv'] = 37,
		['skill_add'] = '37%',
		['skill_use_contribution'] = 13000,
	},
	[38] = {
		['skill_lv'] = 38,
		['skill_add'] = '38%',
		['skill_use_contribution'] = 13200,
	},
	[39] = {
		['skill_lv'] = 39,
		['skill_add'] = '39%',
		['skill_use_contribution'] = 13500,
	},
	[40] = {
		['skill_lv'] = 40,
		['skill_add'] = '40%',
		['skill_use_contribution'] = 14000,
	},
}

return guild_skill_defense