-- ------------------------------
-- desc: generated by xls2data.py
-- source: guild_badge.xls
-- sheet: 公会商品
-- ------------------------------


local guild_badge = {
	[1] = {
		['name'] = T('金鹰军团'),
		['res'] = 'guild_badge_3.png',
		['explore'] = 'common_guild_icon3.png',
	},
	[2] = {
		['name'] = T('战龙商会'),
		['res'] = 'guild_badge_1.png',
		['explore'] = 'common_guild_icon1.png',
	},
	[3] = {
		['name'] = T('圣狮殿堂'),
		['res'] = 'guild_badge_2.png',
		['explore'] = 'common_guild_icon2.png',
	},
}

return guild_badge