-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会预开放文本config.xls
-- sheet: 商会预开放
-- ------------------------------


local guild_advance_open = {
	[1] = {
		['name'] = T('商会之星'),
		['target_tips'] = T('每日选出一位商会之星。致敬商会之星可领取奖励，保证商会活跃。'),
	},
	[2] = {
		['name'] = T('商会讨伐'),
		['target_tips'] = T('大量海盗入侵商会所在港口，击退海盗，赢得大量金币、商会贡献和经验。'),
	},
	[3] = {
		['name'] = T('商会研究所'),
		['target_tips'] = T('研究技能提升商会技能上限，学习技能提高自身属性。'),
	},
}

return guild_advance_open