-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会BOSS投放.xlsx
-- sheet: 每次战斗奖励
-- ------------------------------


local item_info01 = {
	['1'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 20,
		['rate'] = 0,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'REWARD',
		['id'] = 0,
		['cnt'] = 1,
		['rate'] = 0,
		['memo'] = '',
	},
}

return item_info01