-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会BOSS投放.xlsx
-- sheet: 第1名奖励
-- ------------------------------


local item_info03 = {
	['1'] = {
		['type'] = 'contribute',
		['id'] = 0,
		['cnt'] = 2000,
		['rate'] = 100,
		['memo'] = '',
	},
}

return item_info03