-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会BOSS投放.xlsx
-- sheet: 商会buff奖励
-- ------------------------------


local item_info02 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 70,
		['cnt'] = 1,
		['rate'] = 25,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'item',
		['id'] = 71,
		['cnt'] = 1,
		['rate'] = 25,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'item',
		['id'] = 72,
		['cnt'] = 1,
		['rate'] = 25,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'item',
		['id'] = 73,
		['cnt'] = 1,
		['rate'] = 25,
		['memo'] = '',
	},
	['5'] = {
		['type'] = '',
		['id'] = 0,
		['cnt'] = 1,
		['rate'] = 900,
		['memo'] = '',
	},
}

return item_info02