-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会BOSS投放.xlsx
-- sheet: 第6名至以后奖励
-- ------------------------------


local item_info05 = {
	['1'] = {
		['type'] = 'contribute',
		['id'] = 0,
		['cnt'] = 800,
		['rate'] = 100,
		['memo'] = '',
	},
}

return item_info05