-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会BOSS投放.xlsx
-- sheet: 商会BOSS胜利金钱奖励
-- ------------------------------


local item_info06 = {
	['1'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 150000,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 450000,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 900000,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 1350000,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 1800000,
		['rate'] = 100,
		['memo'] = '',
	},
}

return item_info06