-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会BOSS投放.xlsx
-- sheet: 第2-5名奖励
-- ------------------------------


local item_info04 = {
	['1'] = {
		['type'] = 'contribute',
		['id'] = 0,
		['cnt'] = 1200,
		['rate'] = 100,
		['memo'] = '',
	},
}

return item_info04