-- ------------------------------
-- desc: generated by xls2data.py
-- source: 公会多人任务奖励.xlsx
-- sheet: 宝物精华任务2
-- ------------------------------


local reward_guild_task_32 = {
	['1'] = {
		['type'] = 'group_exp',
		['id'] = 0,
		['cnt'] = 80,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'contribute',
		['id'] = 0,
		['cnt'] = 100,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'item',
		['id'] = 3,
		['cnt'] = 20,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_guild_task_32