-- ------------------------------
-- desc: generated by xls2data.py
-- source: 公会多人任务奖励.xlsx
-- sheet: 朗姆酒任务1 (3)
-- ------------------------------


local reward_guild_task_101 = {
	['1'] = {
		['type'] = 'group_exp',
		['id'] = 0,
		['cnt'] = 40,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'contribute',
		['id'] = 0,
		['cnt'] = 50,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'honour',
		['id'] = 0,
		['cnt'] = 20,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_guild_task_101