-- ------------------------------
-- desc: generated by xls2data.py
-- source: 公会多人任务奖励.xlsx
-- sheet: 执行3
-- ------------------------------


local reward_guild_task_13 = {
	['1'] = {
		['type'] = 'group_exp',
		['id'] = 0,
		['cnt'] = 160,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'contribute',
		['id'] = 0,
		['cnt'] = 300,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'item',
		['id'] = 190,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_guild_task_13