-- ------------------------------
-- desc: generated by xls2data.py
-- source: 公会多人任务奖励.xlsx
-- sheet: 进阶图纸1 (6)
-- ------------------------------


local reward_guild_task_241 = {
	['1'] = {
		['type'] = 'group_exp',
		['id'] = 0,
		['cnt'] = 40,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'contribute',
		['id'] = 0,
		['cnt'] = 50,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'material',
		['id'] = 1501,
		['cnt'] = 5,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_guild_task_241