-- ------------------------------
-- desc: generated by xls2data.py
-- source: 事件config.xls
-- sheet: 事件配置表
-- ------------------------------


local event_config = {
	[1] = {
		['id_str'] = 'GOLD_UPDATE_EVENT',
		['dec'] = T('钻石更新事件'),
	},
	[2] = {
		['id_str'] = 'CASH_UPDATE_EVENT',
		['dec'] = T('金币更新事件'),
	},
	[3] = {
		['id_str'] = 'JOIN_EXIT_GUILD_EVENT',
		['dec'] = T('加入(退出)公会事件'),
	},
	[4] = {
		['id_str'] = 'JOIN_EXIT_TEAM_EVENT',
		['dec'] = T('加入(退出)队伍事件'),
	},
	[5] = {
		['id_str'] = 'MATERIAL_UPDATE_EVENT',
		['dec'] = T('材料更新事件'),
	},
	[6] = {
		['id_str'] = 'AUDIO_PLAY_EVENT',
		['dec'] = T('语音播放事件'),
	},
	[7] = {
		['id_str'] = 'AUDIO_STOP_EVENT',
		['dec'] = T('语音停止事件'),
	},
	[8] = {
		['id_str'] = 'ITEM_UPDATE_EVENT',
		['dec'] = T('道具更新事件')
	},
	[9] = {
		['id_str'] = 'POWER_UPDATE_EVENT',
		['dec'] = T('体力更新事件')
	}
}

return event_config