-- ------------------------------
-- desc: generated by xls2data.py
-- source: 世界任务奖励表.xlsx
-- sheet: 讨伐-1
-- ------------------------------


local reward_worldmission_11 = {
	['1'] = {
		['type'] = 'honour',
		['id'] = 0,
		['cnt'] = 5,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 30,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_worldmission_11