-- ------------------------------
-- desc: generated by xls2data.py
-- source: 遗迹奖励.xls
-- sheet: 18
-- ------------------------------


local relic_18_info = {
	[1] = {
		['type'] = 'item',
		['id'] = 106,
		['cnt'] = 3,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[2] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 80,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[3] = {
		['type'] = 'item',
		['id'] = 166,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[4] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 120,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[5] = {
		['type'] = 'baowu',
		['id'] = 703,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
	[6] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 200,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
}

return relic_18_info