-- ------------------------------
-- desc: generated by xls2data.py
-- source: 遗迹奖励.xls
-- sheet: 69
-- ------------------------------


local relic_69_info = {
	[1] = {
		['type'] = 'item',
		['id'] = 162,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[2] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 300,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[3] = {
		['type'] = 'item',
		['id'] = 3,
		['cnt'] = 150,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[4] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 450,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[5] = {
		['type'] = 'item',
		['id'] = 3,
		['cnt'] = 300,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
	[6] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 600,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
	[7] = {
		['type'] = 'item',
		['id'] = 163,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 4,
	},
	[8] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 900,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 4,
	},
	[9] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 20,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 5,
	},
	[10] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 1500,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 5,
	},
	[11] = {
		['type'] = 'item',
		['id'] = 163,
		['cnt'] = 2,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 6,
	},
	[12] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 2000,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 6,
	},
	[13] = {
		['type'] = 'item',
		['id'] = 3,
		['cnt'] = 2000,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 7,
	},
	[14] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 2500,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 7,
	},
}

return relic_69_info