-- ------------------------------
-- desc: generated by xls2data.py
-- source: 遗迹奖励.xls
-- sheet: 35
-- ------------------------------


local relic_35_info = {
	[1] = {
		['type'] = 'item',
		['id'] = 162,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[2] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 200,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[3] = {
		['type'] = 'item',
		['id'] = 3,
		['cnt'] = 100,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[4] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 300,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[5] = {
		['type'] = 'item',
		['id'] = 162,
		['cnt'] = 2,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
	[6] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 400,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
	[7] = {
		['type'] = 'item',
		['id'] = 167,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 4,
	},
	[8] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 600,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 4,
	},
}

return relic_35_info