-- ------------------------------
-- desc: generated by xls2data.py
-- source: 遗迹奖励.xls
-- sheet: 51
-- ------------------------------


local relic_51_info = {
	[1] = {
		['type'] = 'item',
		['id'] = 162,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[2] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 300,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[3] = {
		['type'] = 'item',
		['id'] = 3,
		['cnt'] = 150,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[4] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 450,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[5] = {
		['type'] = 'item',
		['id'] = 3,
		['cnt'] = 300,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
	[6] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 600,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
	[7] = {
		['type'] = 'baowu',
		['id'] = 223,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 4,
	},
	[8] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 900,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 4,
	},
	[9] = {
		['type'] = 'item',
		['id'] = 163,
		['cnt'] = 2,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 5,
	},
	[10] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 1500,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 5,
	},
}

return relic_51_info