-- ------------------------------
-- desc: generated by xls2data.py
-- source: 遗迹奖励.xls
-- sheet: 39
-- ------------------------------


local relic_39_info = {
	[1] = {
		['type'] = 'item',
		['id'] = 3,
		['cnt'] = 30,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[2] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 200,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[3] = {
		['type'] = 'item',
		['id'] = 106,
		['cnt'] = 5,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[4] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 300,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[5] = {
		['type'] = 'baowu',
		['id'] = 503,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
	[6] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 400,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
}

return relic_39_info