-- ------------------------------
-- desc: generated by xls2data.py
-- source: 遗迹奖励.xls
-- sheet: 23
-- ------------------------------


local relic_23_info = {
	[1] = {
		['type'] = 'item',
		['id'] = 3,
		['cnt'] = 60,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[2] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 80,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 1,
	},
	[3] = {
		['type'] = 'baowu',
		['id'] = 803,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[4] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 120,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 2,
	},
	[5] = {
		['type'] = 'baowu',
		['id'] = 305,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
	[6] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 200,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 3,
	},
	[7] = {
		['type'] = 'item',
		['id'] = 162,
		['cnt'] = 3,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 4,
	},
	[8] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 300,
		['rate'] = 100,
		['memo'] = '',
		['star'] = 4,
	},
}

return relic_23_info