-- ------------------------------
-- desc: generated by xls2data.py
-- source: dailyrace.xls
-- sheet: 每日竞赛
-- ------------------------------


local dailyrace_data = {
	[1] = {
		['name'] = T('经商大赛'),
		['is_use'] = 1,
		['step'] = {500, 1500, 3000},
		['step_reward_name'] = {T("一级船舶宝物"),T("二级船舶宝物"),T("三级船舶宝物")},
		['step_reward'] = {"common_box_closed1.png","common_box_closed1.png","common_box_closed2.png"},
		['step_diamond_reward'] = {[1]=1000, [2]=500, [3]=200},
	},
	[2] = {
		['name'] = T('悬赏达人'),
		['is_use'] = 1,
		['step'] = {60, 120, 180},
		['step_reward_name'] = {T("一级船舶宝物"),T("二级船舶宝物"),T("三级船舶宝物")},
		['step_reward'] = {"common_box_closed1.png","common_box_closed1.png","common_box_closed2.png"},
		['step_diamond_reward'] = {[1]=1000, [2]=500, [3]=200},
	},
	[3] = {
		['name'] = T('最强王者'),
		['is_use'] = 0,
		['step'] = {5, 10, 27},
		['step_reward_name'] = {T("一级船舶宝物"),T("二级船舶宝物"),T("三级船舶宝物")},
		['step_reward'] = {"common_box_closed1.png","common_box_closed1.png","common_box_closed2.png"},
		['step_diamond_reward'] = {[1]=1000, [2]=500, [3]=200},
	},
	[4] = {
		['name'] = T('海盗宝藏'),
		['is_use'] = 0,
		['step'] = {1, 3, 8},
		['step_reward_name'] = {T("一级船舶宝物"),T("二级船舶宝物"),T("三级船舶宝物")},
		['step_reward'] = {"common_box_closed1.png","common_box_closed1.png","common_box_closed2.png"},
		['step_diamond_reward'] = {[1]=1000, [2]=500, [3]=200},
	},
}

return dailyrace_data