-- ------------------------------
-- desc: generated by xls2data.py
-- source: mjms.xls
-- sheet: 名舰名仕
-- ------------------------------


local mjms_huodong = {
	[1] = {
		['type'] = 1,
		['huodong_id'] = 60,
		['x'] = 415,
		['y'] = 300,
		['scale'] = 48,
	},
	[2] = {
		['type'] = 1,
		['huodong_id'] = 82,
		['x'] = 415,
		['y'] = 300,
		['scale'] = 48,
	},
	[3] = {
		['type'] = 1,
		['huodong_id'] = 66,
		['x'] = 410,
		['y'] = 300,
		['scale'] = 48,
	},
	[4] = {
		['type'] = 1,
		['huodong_id'] = 67,
		['x'] = 410,
		['y'] = 300,
		['scale'] = 48,
	},
	[5] = {
		['type'] = 1,
		['huodong_id'] = 64,
		['x'] = 415,
		['y'] = 300,
		['scale'] = 48,
	},
	[6] = {
		['type'] = 1,
		['huodong_id'] = 72,
		['x'] = 415,
		['y'] = 300,
		['scale'] = 48,
	},
	[7] = {
		['type'] = 1,
		['huodong_id'] = 62,
		['x'] = 410,
		['y'] = 300,
		['scale'] = 48,
	},
	[8] = {
		['type'] = 1,
		['huodong_id'] = 59,
		['x'] = 415,
		['y'] = 300,
		['scale'] = 48,
	},
	[9] = {
		['type'] = 2,
		['huodong_id'] = 21,
		['x'] = 420,
		['y'] = 310,
		['scale'] = 40,
	},
	[10] = {
		['type'] = 2,
		['huodong_id'] = 19,
		['x'] = 420,
		['y'] = 310,
		['scale'] = 40,
	},
	[11] = {
		['type'] = 2,
		['huodong_id'] = 22,
		['x'] = 420,
		['y'] = 310,
		['scale'] = 40,
	},
	[12] = {
		['type'] = 2,
		['huodong_id'] = 17,
		['x'] = 425,
		['y'] = 310,
		['scale'] = 42,
	},
	[13] = {
		['type'] = 2,
		['huodong_id'] = 20,
		['x'] = 420,
		['y'] = 310,
		['scale'] = 40,
	},
}

return mjms_huodong