-- ------------------------------
-- desc: generated by xls2data.py
-- source: explore_ship_cfg.xls
-- sheet: 探索船配置
-- ------------------------------


local explore_ship_cfg = {
	[1] = {
		['ship_dir1'] = {stPos={-25,0}, endPos={-25,-20}},
		['ship_dir2'] = {stPos={-40,10}, endPos={-50,-10}},
		['ship_dir3'] = {stPos={-30,15}, endPos={-30,-10}},
		['ship_dir4'] = {stPos={-10,10}, endPos={-20,-10}},
		['ship_dir5'] = {stPos={-25,10}, endPos={-25,-10}},
	},
	[2] = {
		['ship_dir1'] = {stPos={-25,-10}, endPos={-30,-20}},
		['ship_dir2'] = {stPos={-50,0}, endPos={-50,-20}},
		['ship_dir3'] = {stPos={-30,5}, endPos={-30,-20}},
		['ship_dir4'] = {stPos={-10,0}, endPos={-15,-20}},
		['ship_dir5'] = {stPos={-25,0}, endPos={-25,-20}},
	},
	[3] = {
		['ship_dir1'] = {stPos={-25,5}, endPos={-25,-15}},
		['ship_dir2'] = {stPos={-50,10}, endPos={-50,-10}},
		['ship_dir3'] = {stPos={-20,20}, endPos={-20,-10}},
		['ship_dir4'] = {stPos={0,10}, endPos={0,-10}},
		['ship_dir5'] = {stPos={-25,10}, endPos={-30,-10}},
	},
	[4] = {
		['ship_dir1'] = {stPos={0,0}, endPos={0,0}},
		['ship_dir2'] = {stPos={0,0}, endPos={0,0}},
		['ship_dir3'] = {stPos={0,0}, endPos={0,0}},
		['ship_dir4'] = {stPos={0,0}, endPos={0,0}},
		['ship_dir5'] = {stPos={0,0}, endPos={0,0}},
	},
	[5] = {
		['ship_dir1'] = {stPos={-30,10}, endPos={-30,-10}},
		['ship_dir2'] = {stPos={-60,20}, endPos={-60,-10}},
		['ship_dir3'] = {stPos={-20,20}, endPos={-20,-10}},
		['ship_dir4'] = {stPos={10,0}, endPos={10,-20}},
		['ship_dir5'] = {stPos={-25,-5}, endPos={-25,-20}},
	},
	[6] = {
		['ship_dir1'] = {stPos={-20,5}, endPos={-20,-15}},
		['ship_dir2'] = {stPos={-50,10}, endPos={-50,-10}},
		['ship_dir3'] = {stPos={-30,15}, endPos={-40,-10}},
		['ship_dir4'] = {stPos={5,10}, endPos={0,-15}},
		['ship_dir5'] = {stPos={-25,10}, endPos={-30,-10}},
	},
	[7] = {
		['ship_dir1'] = {stPos={-25,0}, endPos={-30,-20}},
		['ship_dir2'] = {stPos={-60,10}, endPos={-60,-10}},
		['ship_dir3'] = {stPos={-20,20}, endPos={-20,-10}},
		['ship_dir4'] = {stPos={10,10}, endPos={5,-10}},
		['ship_dir5'] = {stPos={-25,0}, endPos={-30,-20}},
	},
	[8] = {
		['ship_dir1'] = {stPos={-25,-10}, endPos={-25,-30}},
		['ship_dir2'] = {stPos={-55,5}, endPos={-55,-25}},
		['ship_dir3'] = {stPos={-25,5}, endPos={-25,-30}},
		['ship_dir4'] = {stPos={5,0}, endPos={0,-30}},
		['ship_dir5'] = {stPos={-30,0}, endPos={-30,-20}},
	},
	[9] = {
		['ship_dir1'] = {stPos={-25,-5}, endPos={-30,-20}},
		['ship_dir2'] = {stPos={-70,5}, endPos={-70,-20}},
		['ship_dir3'] = {stPos={-30,35}, endPos={-30,-10}},
		['ship_dir4'] = {stPos={15,5}, endPos={10,-20}},
		['ship_dir5'] = {stPos={-30,0}, endPos={-30,-20}},
	},
	[10] = {
		['ship_dir1'] = {stPos={-25,5}, endPos={-30,-10}},
		['ship_dir2'] = {stPos={-60,20}, endPos={-60,-15}},
		['ship_dir3'] = {stPos={-25,25}, endPos={-30,-10}},
		['ship_dir4'] = {stPos={15,15}, endPos={10,-20}},
		['ship_dir5'] = {stPos={-25,5}, endPos={-30,-20}},
	},
	[11] = {
		['ship_dir1'] = {stPos={-25,10}, endPos={-30,-10}},
		['ship_dir2'] = {stPos={-70,10}, endPos={-70,-20}},
		['ship_dir3'] = {stPos={-25,20}, endPos={-25,-10}},
		['ship_dir4'] = {stPos={20,10}, endPos={20,-20}},
		['ship_dir5'] = {stPos={-25,5}, endPos={-25,-25}},
	},
	[12] = {
		['ship_dir1'] = {stPos={-25,5}, endPos={-30,-20}},
		['ship_dir2'] = {stPos={-60,15}, endPos={-65,-20}},
		['ship_dir3'] = {stPos={-30,25}, endPos={-30,-10}},
		['ship_dir4'] = {stPos={0,10}, endPos={0,-20}},
		['ship_dir5'] = {stPos={-35,5}, endPos={-35,-20}},
	},
	[13] = {
		['ship_dir1'] = {stPos={-30,0}, endPos={-35,-30}},
		['ship_dir2'] = {stPos={-65,10}, endPos={-70,-20}},
		['ship_dir3'] = {stPos={-30,10}, endPos={-30,-20}},
		['ship_dir4'] = {stPos={5,5}, endPos={0,-20}},
		['ship_dir5'] = {stPos={-20,5}, endPos={-25,-25}},
	},
	[14] = {
		['ship_dir1'] = {stPos={-30,5}, endPos={-35,-20}},
		['ship_dir2'] = {stPos={-75,15}, endPos={-75,-10}},
		['ship_dir3'] = {stPos={-30,30}, endPos={-30,-10}},
		['ship_dir4'] = {stPos={15,15}, endPos={0,-10}},
		['ship_dir5'] = {stPos={-20,10}, endPos={-25,-20}},
	},
	[15] = {
		['ship_dir1'] = {stPos={-25,10}, endPos={-30,-10}},
		['ship_dir2'] = {stPos={-65,20}, endPos={-65,-10}},
		['ship_dir3'] = {stPos={-20,20}, endPos={-20,-10}},
		['ship_dir4'] = {stPos={20,15}, endPos={15,-15}},
		['ship_dir5'] = {stPos={-25,5}, endPos={-30,-15}},
	},
	[16] = {
		['ship_dir1'] = {stPos={-30,-5}, endPos={-35,-30}},
		['ship_dir2'] = {stPos={-65,5}, endPos={-65,-30}},
		['ship_dir3'] = {stPos={-30,10}, endPos={-30,-25}},
		['ship_dir4'] = {stPos={0,-5}, endPos={0,-30}},
		['ship_dir5'] = {stPos={-30,-10}, endPos={-35,-35}},
	},
	[17] = {
		['ship_dir1'] = {stPos={-30,5}, endPos={-30,-30}},
		['ship_dir2'] = {stPos={-60,5}, endPos={-60,-30}},
		['ship_dir3'] = {stPos={-20,10}, endPos={-20,-25}},
		['ship_dir4'] = {stPos={10,0}, endPos={10,-35}},
		['ship_dir5'] = {stPos={-30,-15}, endPos={-30,-35}},
	},
	[18] = {
		['ship_dir1'] = {stPos={-25,10}, endPos={-30,-20}},
		['ship_dir2'] = {stPos={-65,20}, endPos={-60,-20}},
		['ship_dir3'] = {stPos={-30,25}, endPos={-30,-10}},
		['ship_dir4'] = {stPos={5,15}, endPos={5,-20}},
		['ship_dir5'] = {stPos={-25,5}, endPos={-25,-25}},
	},
	[19] = {
		['ship_dir1'] = {stPos={-30,25}, endPos={-30,-20}},
		['ship_dir2'] = {stPos={-60,25}, endPos={-60,-20}},
		['ship_dir3'] = {stPos={-20,15}, endPos={-20,-15}},
		['ship_dir4'] = {stPos={0,20}, endPos={0,-10}},
		['ship_dir5'] = {stPos={-30,5}, endPos={-30,-25}},
	},
	[20] = {
		['ship_dir1'] = {stPos={-35,10}, endPos={-35,-35}},
		['ship_dir2'] = {stPos={-60,10}, endPos={-60,-35}},
		['ship_dir3'] = {stPos={-30,15}, endPos={-30,-25}},
		['ship_dir4'] = {stPos={0,0}, endPos={0,-40}},
		['ship_dir5'] = {stPos={-40,-10}, endPos={-40,-45}},
	},
	[21] = {
		['ship_dir1'] = {stPos={-30,10}, endPos={-30,-30}},
		['ship_dir2'] = {stPos={-60,15}, endPos={-60,-30}},
		['ship_dir3'] = {stPos={-30,25}, endPos={-30,-15}},
		['ship_dir4'] = {stPos={0,15}, endPos={0,-20}},
		['ship_dir5'] = {stPos={-30,15}, endPos={-30,-20}},
	},
	[22] = {
		['ship_dir1'] = {stPos={-35,0}, endPos={-40,-30}},
		['ship_dir2'] = {stPos={-85,25}, endPos={-80,-30}},
		['ship_dir3'] = {stPos={-30,15}, endPos={-30,-20}},
		['ship_dir4'] = {stPos={25,5}, endPos={20,-35}},
		['ship_dir5'] = {stPos={-30,-5}, endPos={-30,-35}},
	},
}

return explore_ship_cfg