-- ------------------------------
-- desc: generated by xls2data.py
-- source: explore_whirlpool.xls
-- sheet: Sheet1
-- ------------------------------


local explore_whirlpool = {
	[1] = {
		['name'] = T('直布罗陀漩涡'),
		['sea_pos'] = {772,292},
		['map_pos'] = {51,19},
		['map_name_pos'] = {0,0},
		['des'] = T('位于地中海入口'),
		['sea_index'] = 1,
		['switch_key'] = 'VORTEX_MED',
	},
	[2] = {
		['name'] = T('北海巨妖巢穴'),
		['sea_pos'] = {847,157},
		['map_pos'] = {56,10},
		['map_name_pos'] = {0,0},
		['des'] = T('位于北海中部'),
		['sea_index'] = 2,
		['switch_key'] = 'VORTEX_NOR',
	},
	[3] = {
		['name'] = T('南大西洋蓝洞'),
		['sea_pos'] = {907,697},
		['map_pos'] = {60,46},
		['map_name_pos'] = {0,0},
		['des'] = T('位于非洲最南端'),
		['sea_index'] = 3,
		['switch_key'] = 'VORTEX_AFR',
	},
	[4] = {
		['name'] = T('阿拉伯海漩涡'),
		['sea_pos'] = {1102,412},
		['map_pos'] = {73,27},
		['map_name_pos'] = {0,0},
		['des'] = T('位于印度洋中部'),
		['sea_index'] = 4,
		['switch_key'] = 'VORTEX_IND',
	},
	[5] = {
		['name'] = T('科科锡美丽漩涡'),
		['sea_pos'] = {1327,547},
		['map_pos'] = {88,36},
		['map_name_pos'] = {0,0},
		['des'] = T('位于东南亚最南端'),
		['sea_index'] = 5,
		['switch_key'] = 'VORTEX_SA',
	},
	[6] = {
		['name'] = T('日本龙三角'),
		['sea_pos'] = {1447,322},
		['map_pos'] = {96,21},
		['map_name_pos'] = {0,0},
		['des'] = T('位于东亚长崎附近'),
		['sea_index'] = 6,
		['switch_key'] = 'VORTEX_EA',
	},
	[7] = {
		['name'] = T('伯利兹蓝洞'),
		['sea_pos'] = {427,382},
		['map_pos'] = {28,25},
		['map_name_pos'] = {0,0},
		['des'] = T('位于加勒比海附近'),
		['sea_index'] = 7,
		['switch_key'] = 'VORTEX_BT',
	},
	[8] = {
		['name'] = T('滕斯朋漩涡'),
		['sea_pos'] = {1567,637},
		['map_pos'] = {104,42},
		['map_name_pos'] = {0,0},
		['des'] = T('位于澳洲右侧'),
		['sea_index'] = 10,
		['switch_key'] = 'VORTEX_OCE',
	},
}

return explore_whirlpool