-- ------------------------------
-- desc: generated by xls2data.py
-- source: explore_objects.xls
-- sheet: 矿物资源信息表
-- ------------------------------


local explore_mineral_config = {
	[1] = {
		['res'] = 'ui/minerals/mineral_wood_1.png',
		['reward'] = {"material",1001},
	},
	[2] = {
		['res'] = 'ui/minerals/mineral_wood_2.png',
		['reward'] = {"material",1002},
	},
	[3] = {
		['res'] = 'ui/minerals/mineral_wood_3.png',
		['reward'] = {"material",1003},
	},
	[4] = {
		['res'] = 'ui/minerals/mineral_winery_1.png',
		['reward'] = {"cash"},
	},
	[5] = {
		['res'] = 'ui/minerals/mineral_winery_2.png',
		['reward'] = {"cash"},
	},
	[6] = {
		['res'] = 'ui/minerals/mineral_winery_3.png',
		['reward'] = {"cash"},
	},
	[7] = {
		['res'] = 'ui/minerals/mineral_steel_1.png',
		['reward'] = {"material",1201},
	},
	[8] = {
		['res'] = 'ui/minerals/mineral_steel_2.png',
		['reward'] = {"material",1202},
	},
	[9] = {
		['res'] = 'ui/minerals/mineral_steel_3.png',
		['reward'] = {"material",1203},
	},
	[10] = {
		['res'] = '',
		['reward'] = {"material",1301},
	},
	[11] = {
		['res'] = '',
		['reward'] = {"material",1302},
	},
	[12] = {
		['res'] = '',
		['reward'] = {"material",1303},
	},
	[13] = {
		['res'] = '',
		['reward'] = {"tili"},
	},
	[14] = {
		['res'] = '',
		['reward'] = {"tili"},
	},
	[15] = {
		['res'] = '',
		['reward'] = {"tili"},
	},
	[16] = {
		['res'] = 'ui/minerals/mineral_essence_1.png',
		['reward'] = {"item",3},
	},
	[17] = {
		['res'] = 'ui/minerals/mineral_essence_2.png',
		['reward'] = {"item",3},
	},
	[18] = {
		['res'] = 'ui/minerals/mineral_essence_3.png',
		['reward'] = {"item",3},
	},
	[19] = {
		['res'] = '',
		['reward'] = {"honour"},
	},
	[20] = {
		['res'] = '',
		['reward'] = {"honour"},
	},
	[21] = {
		['res'] = '',
		['reward'] = {"honour"},
	},
	[22] = {
		['res'] = 'ui/minerals/mineral_diamond_1.png',
		['reward'] = {"gold"},
	},
	[23] = {
		['res'] = 'ui/minerals/mineral_diamond_2.png',
		['reward'] = {"gold"},
	},
	[24] = {
		['res'] = 'ui/minerals/mineral_diamond_3.png',
		['reward'] = {"gold"},
	},
}

return explore_mineral_config