/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qtz_utils_share_QTZShareSDK */

#ifndef _Included_com_qtz_utils_share_QTZShareSDK
#define _Included_com_qtz_utils_share_QTZShareSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qtz_utils_share_QTZShareSDK
 * Method:    onShareNotifyNative
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qtz_utils_share_QTZShareSDK_onShareNotifyNative
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
