/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_tencent_msdk_api_WGRealNameAuthObserverForSO.h"
#include "CommonFiles/WGPlatform.h"
#include "CommonFiles/WGCommon.h"

#include <android/log.h>
/*
 * Class:     com_tencent_msdk_api_WGRealNameAuthObserverForSO
 * Method:    OnRealNameAuthNotify
 * Signature: (Lcom/tencent/msdk/api/RealNameAuthRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGRealNameAuthObserverForSO_OnRealNameAuthNotify
  (JNIEnv * env , jclass, jobject jAuthRet){
	 jclass jAuthRetClz = env->GetObjectClass(jAuthRet);
	 RealNameAuthRet cRealNameAuthRet;
	 JniGetAndSetIntField(flag, "flag", jAuthRetClz, jAuthRet, cRealNameAuthRet);
	 JniGetAndSetIntField(errorCode, "errorCode", jAuthRetClz, jAuthRet, cRealNameAuthRet);
	 JniGetAndSetStringField(desc, "desc", jAuthRetClz, jAuthRet, cRealNameAuthRet);
	 JniGetAndSetIntField(platform, "platform", jAuthRetClz, jAuthRet, cRealNameAuthRet);
	 if (WGPlatform::GetInstance()->GetRealNameAuthObserver() != NULL) {
	 		 WGPlatform::GetInstance()->GetRealNameAuthObserver()->OnRealNameAuthNotify(cRealNameAuthRet);
	 }
	 env->DeleteLocalRef(jAuthRetClz);
}



