/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative */

#ifndef _Included_com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative
#define _Included_com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative
 * Method:    OnCheckNeedUpdateInfo
 * Signature: (JLjava/lang/String;JILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative_OnCheckNeedUpdateInfo
  (JNIEnv *, jclass, jlong, jstring, jlong, jint, jstring, jint);

/*
 * Class:     com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative
 * Method:    OnDownloadAppProgressChanged
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative_OnDownloadAppProgressChanged
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative
 * Method:    OnDownloadAppStateChanged
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative_OnDownloadAppStateChanged
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative
 * Method:    OnDownloadYYBProgressChanged
 * Signature: (Ljava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative_OnDownloadYYBProgressChanged
  (JNIEnv *, jclass, jstring, jlong, jlong);

/*
 * Class:     com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative
 * Method:    OnDownloadYYBStateChanged
 * Signature: (Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_myapp_autoupdate_WGSaveUpdateObserverNative_OnDownloadYYBStateChanged
  (JNIEnv *, jclass, jstring, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
