/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_msdk_api_WGADObserverForSO */

#ifndef _Included_com_tencent_msdk_api_WGRealNameAuthObserverForSO
#define _Included_com_tencent_msdk_api_WGRealNameAuthObserverForSO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_msdk_api_WGRealNameAuthObserverForSO
 * Method:    OnRealNameAuthNotify
 * Signature: (Lcom/tencent/msdk/api/RealNameAuthRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGRealNameAuthObserverForSO_OnRealNameAuthNotify
  (JNIEnv *, jclass, jobject);


#ifdef __cplusplus
}
#endif
#endif
