/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_msdk_api_WGGroupObserverForSO */

#ifndef _Included_com_tencent_msdk_api_WGGroupObserverForSO
#define _Included_com_tencent_msdk_api_WGGroupObserverForSO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_msdk_api_WGGroupObserverForSO
 * Method:    OnQueryGroupInfoNotify
 * Signature: (Lcom/tencent/msdk/api/GroupRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGGroupObserverForSO_OnQueryGroupInfoNotify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_msdk_api_WGGroupObserverForSO
 * Method:    OnBindGroupNotify
 * Signature: (Lcom/tencent/msdk/api/GroupRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGGroupObserverForSO_OnBindGroupNotify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_msdk_api_WGGroupObserverForSO
 * Method:    OnUnbindGroupNotify
 * Signature: (Lcom/tencent/msdk/api/GroupRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGGroupObserverForSO_OnUnbindGroupNotify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_msdk_api_WGGroupObserverForSO
 * Method:    OnQueryQQGroupKeyNotify
 * Signature: (Lcom/tencent/msdk/api/GroupRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGGroupObserverForSO_OnQueryQQGroupKeyNotify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_msdk_api_WGGroupObserverForSO
 * Method:    OnJoinWXGroupNotify
 * Signature: (Lcom/tencent/msdk/api/GroupRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGGroupObserverForSO_OnJoinWXGroupNotify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_msdk_api_WGGroupObserverForSO
 * Method:    OnCreateWXGroupNotify
 * Signature: (Lcom/tencent/msdk/api/GroupRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGGroupObserverForSO_OnCreateWXGroupNotify
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
