/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_msdk_api_WGADObserverForSO */

#ifndef _Included_com_tencent_msdk_api_WGADObserverForSO
#define _Included_com_tencent_msdk_api_WGADObserverForSO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_msdk_api_WGADObserverForSO
 * Method:    OnADNotify
 * Signature: (Lcom/tencent/msdk/api/ADRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGADObserverForSO_OnADNotify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_msdk_api_WGADObserverForSO
 * Method:    OnADBackPressedNotify
 * Signature: (Lcom/tencent/msdk/api/ADRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGADObserverForSO_OnADBackPressedNotify
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
