-- ------------------------------
-- desc: generated by xls2data.py
-- source: team_config.xls
-- sheet: 人物等级对应宝物
-- ------------------------------


local dailyrace_reward = {
	[1] = {
	},
	[2] = {
	},
	[3] = {
	},
	[4] = {
	},
	[5] = {
	},
	[6] = {
	},
}

return dailyrace_reward