-- ------------------------------
-- desc: generated by xls2data.py
-- source: team_config.xls
-- sheet: 每日竞赛
-- ------------------------------


local team_config = {
	[1] = {
		['team_key'] = '',
		['name'] = T('无目标'),
		['skip_info'] = '',
		['close'] = 0,
		['team_activity_txt'] = '',
		['activity_txt_need_num'] = 0,
		['activity_id'] = 0,
		['limit'] = 0,
	},
	[2] = {
		['team_key'] = 'team_market',
		['name'] = T('组队经商'),
		['skip_info'] = 'market',
		['close'] = 0,
		['team_activity_txt'] = T('队伍中人数、好友数对经商收益有加成；委任经商队员不扣次数'),
		['activity_txt_need_num'] = 0,
		['activity_id'] = 19,
		['limit'] = 0,
	},
	[3] = {
		['team_key'] = 'team_wanted',
		['name'] = T('组队悬赏'),
		['skip_info'] = 'guild_task',
		['close'] = 0,
		['team_activity_txt'] = T('队伍中人数对经验有加成，好友数对贡献有加成'),
		['activity_txt_need_num'] = 0,
		['activity_id'] = 17,
		['limit'] = 0,
	},
	[4] = {
		['team_key'] = 'team_treasure',
		['name'] = T('藏宝海湾'),
		['skip_info'] = 'guild_treasure',
		['close'] = 0,
		['team_activity_txt'] = T('有人越快打捞沉船，整队奖励越好'),
		['activity_txt_need_num'] = 1,
		['activity_id'] = 18,
		['limit'] = 0,
	},
	[5] = {
		['team_key'] = 'team_haishen',
		['name'] = T('海神挑战'),
		['skip_info'] = 'sea_god_fight',
		['close'] = 0,
		['team_activity_txt'] = T('每五关可获得一个航海士'),
		['activity_txt_need_num'] = 1,
		['activity_id'] = 21,
		['limit'] = 23,
	},
}

return team_config