-- ------------------------------
-- desc: generated by xls2data.py
-- source: huodong.xls
-- sheet: 总奖励
-- ------------------------------


local new_star_reward = {
	[1] = {
		['point'] = 6,
		['rewards'] = 'reward_hsxxprogress_1',
	},
	[2] = {
		['point'] = 12,
		['rewards'] = 'reward_hsxxprogress_2',
	},
	[3] = {
		['point'] = 18,
		['rewards'] = 'reward_hsxxprogress_3',
	},
	[4] = {
		['point'] = 25,
		['rewards'] = 'reward_hsxxprogress_4',
	},
}

return new_star_reward