-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 进度奖励1
-- ------------------------------


local reward_hsxxprogress_1 = {
	['1'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 200,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxxprogress_1