-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 4-3
-- ------------------------------


local reward_hsxx_43 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 167,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxx_43