-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 4-5
-- ------------------------------


local reward_hsxx_45 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 175,
		['cnt'] = 3,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxx_45