-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 1-4
-- ------------------------------


local reward_hsxx_14 = {
	['1'] = {
		['type'] = 'honour',
		['id'] = 0,
		['cnt'] = 100,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxx_14