-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 进度奖励4
-- ------------------------------


local reward_hsxxprogress_4 = {
	['11'] = {
		['type'] = 'sailor',
		['id'] = 80,
		['cnt'] = 1,
		['rate'] = 1,
		['memo'] = T('a级航海士'),
	},
}

return reward_hsxxprogress_4