-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 4-1
-- ------------------------------


local reward_hsxx_41 = {
	['1'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 100000,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxx_41