-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 5-5
-- ------------------------------


local reward_hsxx_55 = {
	['1'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 300,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxx_55