-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 5-2
-- ------------------------------


local reward_hsxx_52 = {
	['1'] = {
		['type'] = 'contribute',
		['id'] = 0,
		['cnt'] = 500,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxx_52