-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 1-1
-- ------------------------------


local reward_hsxx_11 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 237,
		['cnt'] = 3,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxx_11