-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 1-5
-- ------------------------------


local reward_hsxx_15 = {
	['1'] = {
		['type'] = 'REWARD',
		['id'] = 0,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxx_15