-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 2-5
-- ------------------------------


local reward_hsxx_25 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 175,
		['cnt'] = 2,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxx_25