-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海上新星活动奖励表.xls
-- sheet: 2-2
-- ------------------------------


local reward_hsxx_22 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 106,
		['cnt'] = 10,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_hsxx_22