-- ------------------------------
-- desc: generated by xls2data.py
-- source: 商会战对象表.xls
-- sheet: 对象表
-- ------------------------------


local group_battle_objects = {
	[1] = {
		['name'] = T('基地'),
		['sea_pos'] = {63, 41},
		['ship_pos'] = {62,39},
		['ship_dir'] = 135,
		['name_pos'] = {66,39},
		['map_pos'] = {10,6},
		['dialog_atk'] = '189',
		['dialog_def'] = '191',
	},
	[2] = {
		['name'] = T('据点'),
		['sea_pos'] = {76, 30},
		['ship_pos'] = {81,26},
		['ship_dir'] = 225,
		['name_pos'] = {79,28},
		['map_pos'] = {12,4},
		['dialog_atk'] = '190',
		['dialog_def'] = '192',
	},
	[3] = {
		['name'] = T('据点'),
		['sea_pos'] = {72, 53},
		['ship_pos'] = {78,54},
		['ship_dir'] = 315,
		['name_pos'] = {75,51},
		['map_pos'] = {12,8},
		['dialog_atk'] = '190',
		['dialog_def'] = '192',
	},
	[4] = {
		['name'] = T('基地'),
		['sea_pos'] = {106, 42},
		['ship_pos'] = {111,39},
		['ship_dir'] = 225,
		['name_pos'] = {107,40},
		['map_pos'] = {18,6},
		['dialog_atk'] = '189',
		['dialog_def'] = '191',
	},
	[5] = {
		['name'] = T('据点'),
		['sea_pos'] = {93, 33},
		['ship_pos'] = {93,29},
		['ship_dir'] = 135,
		['name_pos'] = {95,31},
		['map_pos'] = {15,4},
		['dialog_atk'] = '190',
		['dialog_def'] = '192',
	},
	[6] = {
		['name'] = T('据点'),
		['sea_pos'] = {93, 56},
		['ship_pos'] = {93,56},
		['ship_dir'] = 45,
		['name_pos'] = {95,54},
		['map_pos'] = {15,8},
		['dialog_atk'] = '190',
		['dialog_def'] = '192',
	},
	[7] = {
		['name'] = T('漩涡'),
		['sea_pos'] = {43, 57},
		['ship_pos'] = nil,
		['ship_dir'] = 0,
		['name_pos'] = nil,
		['map_pos'] = nil,
		['dialog_atk'] = '',
		['dialog_def'] = '',
	},
	[8] = {
		['name'] = T('漩涡'),
		['sea_pos'] = {124, 69},
		['ship_pos'] = nil,
		['ship_dir'] = 0,
		['name_pos'] = nil,
		['map_pos'] = nil,
		['dialog_atk'] = '',
		['dialog_def'] = '',
	},
}

return group_battle_objects