-- ------------------------------
-- desc: generated by xls2data.py
-- source: strategy_config.xls
-- sheet: strategy_conf
-- ------------------------------


local strategy_conf = {
	[1] = {
		['name'] = T('声望提升'),
		['little_name'] = {"1","2","3"},
		['json_name'] = 'strategy_prestige.json',
	},
	[2] = {
		['name'] = T('资源获取'),
		['little_name'] = {"4","5","6","7"},
		['json_name'] = 'strategy_resources.json',
	},
}

return strategy_conf