-- ------------------------------
-- desc: generated by xls2data.py
-- source: port_shop.xls
-- sheet: prestige_shop
-- ------------------------------


local prestige_shop = {
	[1] = {
		['type'] = 'baowu',
		['camp'] = 3,
		['prestige'] = 300,
		['goods_id'] = 608,
		['amount'] = 1,
	},
	[2] = {
		['type'] = 'gold',
		['camp'] = 3,
		['prestige'] = 500,
		['goods_id'] = 0,
		['amount'] = 200,
	},
	[3] = {
		['type'] = 'baowu',
		['camp'] = 3,
		['prestige'] = 1000,
		['goods_id'] = 708,
		['amount'] = 1,
	},
	[4] = {
		['type'] = 'gold',
		['camp'] = 3,
		['prestige'] = 1500,
		['goods_id'] = 0,
		['amount'] = 400,
	},
	[5] = {
		['type'] = 'baowu',
		['camp'] = 3,
		['prestige'] = 2500,
		['goods_id'] = 808,
		['amount'] = 1,
	},
	[6] = {
		['type'] = 'gold',
		['camp'] = 3,
		['prestige'] = 4000,
		['goods_id'] = 0,
		['amount'] = 500,
	},
	[7] = {
		['type'] = 'item',
		['camp'] = 3,
		['prestige'] = 6000,
		['goods_id'] = 3,
		['amount'] = 250,
	},
	[8] = {
		['type'] = 'baowu',
		['camp'] = 3,
		['prestige'] = 10000,
		['goods_id'] = 408,
		['amount'] = 1,
	},
	[9] = {
		['type'] = 'gold',
		['camp'] = 3,
		['prestige'] = 15000,
		['goods_id'] = 0,
		['amount'] = 500,
	},
	[10] = {
		['type'] = 'item',
		['camp'] = 3,
		['prestige'] = 21000,
		['goods_id'] = 3,
		['amount'] = 250,
	},
	[11] = {
		['type'] = 'baowu',
		['camp'] = 3,
		['prestige'] = 30000,
		['goods_id'] = 508,
		['amount'] = 1,
	},
}

return prestige_shop