-- ------------------------------
-- desc: generated by xls2data.py
-- source: announce_config.xlsx
-- sheet: 70级版本更新公告
-- ------------------------------


local announce_config = {
	[1] = {
		['content'] = T('全新版本来袭！'),
		['rich'] = '',
		['right'] = 0,
	},
	[2] = {
		['content'] = T('亲爱的船长们：'),
		['rich'] = '',
		['right'] = 0,
	},
	[3] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[4] = {
		['content'] = T('重点提示：港口争夺战报名时间调整为每周四！请各位商会会长记得为自己商会报名。'),
		['rich'] = T('$(c:COLOR_RED)重点提示：$(c:COLOR_BROWN)港口争夺战报名时间调整为$(c:COLOR_RED)每周四！$(c:COLOR_BROWN)请各位商会会长记得为自己商会报名。'),
		['right'] = 0,
	},
	[5] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[6] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[7] = {
		['content'] = T('【70级】版本踏浪来袭！碧蓝大海又添新的航道，扬帆起航有了新的目标，出发！自由、荣誉、宝藏在等着你。'),
		['rich'] = '',
		['right'] = 0,
	},
	[8] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[9] = {
		['content'] = T('1.新增大洋洲海域、12个港口、14个遗迹，真实世界，探索续航！'),
		['rich'] = T('1.新增$(c:COLOR_RED)大洋洲海域：$(c:COLOR_BROWN)12个港口、14个遗迹，真实世界，探索续航！'),
		['right'] = 0,
	},
	[10] = {
		['content'] = T('2.新增4个公爵爵位、12艘酷炫新战船，荣耀新船来袭，等你来拿。'),
		['rich'] = T('2.新增4个$(c:COLOR_RED)公爵爵位$(c:COLOR_BROWN)、12艘$(c:COLOR_RED)酷炫战船$(c:COLOR_BROWN)，荣耀新船来袭，等你来拿。'),
		['right'] = 0,
	},
	[11] = {
		['content'] = T('3.角色等级、航海士等级、船舶强化等级、基础技能全面上限提升至70级。'),
		['rich'] = '',
		['right'] = 0,
	},
	[12] = {
		['content'] = T('4.水手宝物、船舶改造属性等属性全面开放至70级。'),
		['rich'] = '',
		['right'] = 0,
	},
	[13] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[14] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[15] = {
		['content'] = T('【商会】商会界面大装修，船长们的家面貌一新'),
		['rich'] = '',
		['right'] = 0,
	},
	[16] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[17] = {
		['content'] = T('1.讨伐、商会战、港口战入口现已统一放入“商会活动”按钮内'),
		['rich'] = '',
		['right'] = 0,
	},
	[18] = {
		['content'] = T('2.港口战的报名时间调整为周四，加入排名限制'),
		['rich'] = '',
		['right'] = 0,
	},
	[19] = {
		['content'] = T('3.商会战、港口战新增MVP评选'),
		['rich'] = '',
		['right'] = 0,
	},
	[20] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[21] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[22] = {
		['content'] = T('【觉醒】两位名扬七海的传奇航海士震撼降临，势必在大海上掀起新的狂风巨浪。'),
		['rich'] = '',
		['right'] = 0,
	},
	[23] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[24] = {
		['content'] = T('1.新增SS级航海士“海军女王-伊丽莎白”，6月19日登陆'),
		['rich'] = '',
		['right'] = 0,
	},
	[25] = {
		['content'] = T('2.新增SS级航海士“伟大冒险家-哥伦布”，6月26日登陆'),
		['rich'] = '',
		['right'] = 0,
	},
	[26] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[27] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[28] = {
		['content'] = T('以上为本次更新的主要内容，如有疑问，请通过以下方式联系我们'),
		['rich'] = '',
		['right'] = 0,
	},
	[29] = {
		['content'] = T('官方微信公众号: qmdahanghai'),
		['rich'] = '',
		['right'] = 0,
	},
	[30] = {
		['content'] = T('官方QQ1群: 485038482'),
		['rich'] = '',
		['right'] = 0,
	},
	[31] = {
		['content'] = T('官方QQ2群: 523979278'),
		['rich'] = '',
		['right'] = 0,
	},
	[32] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[33] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[34] = {
		['content'] = T('《全民大航海》手游官方运营团队'),
		['rich'] = '',
		['right'] = 1,
	},
	[35] = {
		['content'] = T('2017年6月15日'),
		['rich'] = '',
		['right'] = 1,
	},
}

return announce_config