-- ------------------------------
-- desc: generated by xls2data.py
-- source: announce_config.xlsx
-- sheet: 通用停服公告
-- ------------------------------


local announce_stop_config = {
	[1] = {
		['content'] = T('维护公告'),
		['rich'] = '',
		['right'] = 0,
	},
	[2] = {
		['content'] = T('各位亲爱的船长：'),
		['rich'] = '',
		['right'] = 0,
	},
	[3] = {
		['content'] = T('为确保服务器的运行稳定，全民大航海将于7日早1点30分进行停机维护，预计维护时间1小时。如遇特殊情况，开机时间也可能继续顺延。'),
		['rich'] = '',
		['right'] = 0,
	},
	[4] = {
		['content'] = T('      【停服时间】1月7日01：30—02：30'),
		['rich'] = '',
		['right'] = 0,
	},
	[5] = {
		['content'] = T('      【停服范围】安卓QQ大区、安卓微信大区'),
		['rich'] = '',
		['right'] = 0,
	},
	[6] = {
		['content'] = '',
		['rich'] = '',
		['right'] = 0,
	},
	[7] = {
		['content'] = T('全民大航海手游官方运营团队'),
		['rich'] = '',
		['right'] = 1,
	},
	[8] = {
		['content'] = T('2017年1月7日'),
		['rich'] = '',
		['right'] = 1,
	},
}

return announce_stop_config