-- ------------------------------
-- desc: generated by xls2data.py
-- source: 属性key对应.xlsx
-- sheet: Sheet1
-- ------------------------------


local base_attr_info = {
	['durable'] = {
		['name'] = T('船舶耐久'),
		['rate'] = 1.0,
		['unit'] = '%',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['melee'] = {
		['name'] = T('近战攻击'),
		['rate'] = 1.0,
		['unit'] = '%',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['remote'] = {
		['name'] = T('远程攻击'),
		['rate'] = 1.0,
		['unit'] = '%',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['defense'] = {
		['name'] = T('船舶防御'),
		['rate'] = 1.0,
		['unit'] = '%',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['hit'] = {
		['name'] = T('命中等级'),
		['rate'] = 1.0,
		['unit'] = '',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['dodge'] = {
		['name'] = T('闪避等级'),
		['rate'] = 1.0,
		['unit'] = '',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['crits'] = {
		['name'] = T('暴击等级'),
		['rate'] = 1.0,
		['unit'] = '',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['antiCrits'] = {
		['name'] = T('抗暴等级'),
		['rate'] = 1.0,
		['unit'] = '',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['range'] = {
		['name'] = T('火炮射程'),
		['rate'] = 1.0,
		['unit'] = '',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['speed'] = {
		['name'] = T('航行速度'),
		['rate'] = 1.0,
		['unit'] = '',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['damageIncrease'] = {
		['name'] = T('伤害增幅'),
		['rate'] = 1.0,
		['unit'] = '%',
		['rate_1'] = 0.1,
		['unit_1'] = '%',
	},
	['damageReduction'] = {
		['name'] = T('伤害减免'),
		['rate'] = 1.0,
		['unit'] = '%',
		['rate_1'] = 0.1,
		['unit_1'] = '%',
	},
	['load'] = {
		['name'] = T('载货容量'),
		['rate'] = 1.0,
		['unit'] = '',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['goods_capacity'] = {
		['name'] = T('载货容量'),
		['rate'] = 1.0,
		['unit'] = '',
		['rate_1'] = 1.0,
		['unit_1'] = '',
	},
	['business_add'] = {
		['name'] = T('经商利润'),
		['rate'] = 1.0,
		['unit'] = '%',
		['rate_1'] = 1.0,
		['unit_1'] = '%',
	},
	['sailing_speed'] = {
		['name'] = T('海上航速'),
		['rate'] = 0.1,
		['unit'] = T('节'),
		['rate_1'] = 0.1,
		['unit_1'] = T('节'),
	},
}

return base_attr_info