-- ------------------------------
-- desc: generated by xls2data.py
-- source: 端午活动表.xls
-- sheet: 端午消耗钻石
-- ------------------------------


local duanwu_activity_diamond = {
	[1] = {
		['top_ups_num'] = 1000,
		['sea_heart_num'] = 1,
	},
	[2] = {
		['top_ups_num'] = 5000,
		['sea_heart_num'] = 2,
	},
	[3] = {
		['top_ups_num'] = 10000,
		['sea_heart_num'] = 3,
	},
	[4] = {
		['top_ups_num'] = 20000,
		['sea_heart_num'] = 5,
	},
	[5] = {
		['top_ups_num'] = 30000,
		['sea_heart_num'] = 5,
	},
	[6] = {
		['top_ups_num'] = 50000,
		['sea_heart_num'] = 10,
	},
	[7] = {
		['top_ups_num'] = 100000,
		['sea_heart_num'] = 20,
	},
}

return duanwu_activity_diamond