-- ------------------------------
-- desc: generated by xls2data.py
-- source: 端午活动表.xls
-- sheet: 端午活动日常
-- ------------------------------


local duanwu_activity_daily = {
	[1] = {
		['name'] = T('遗迹'),
		['mission_icon'] = 'activity_icon_20.png',
		['mission_step_1'] = T('发掘或探索遗迹%s次'),
		['mission_step_2'] = T('发掘或探索遗迹%s次'),
		['mission_step_3'] = T('完成哈里森·琼斯的战书%s次'),
		['mission_score'] = {10,15,15},
	},
	[2] = {
		['name'] = T('世界任务'),
		['mission_icon'] = 'activity_icon_4.png',
		['mission_step_1'] = T('完成世界任务%s次'),
		['mission_step_2'] = T('完成世界任务%s次'),
		['mission_step_3'] = T('完成橙色世界任务%s次'),
		['mission_score'] = {10,15,15},
	},
	[3] = {
		['name'] = T('悬赏任务'),
		['mission_icon'] = 'activity_icon_5.png',
		['mission_step_1'] = T('完成悬赏任务%s次'),
		['mission_step_2'] = T('完成悬赏任务%s次'),
		['mission_step_3'] = T('完成S级悬赏任务%s次'),
		['mission_score'] = {10,15,15},
	},
	[4] = {
		['name'] = T('经商'),
		['mission_icon'] = 'activity_icon_22.png',
		['mission_step_1'] = T('经商赚取利益%s金币'),
		['mission_step_2'] = T('经商赚取利益%s金币'),
		['mission_step_3'] = T('经商赚取利益%s金币'),
		['mission_score'] = {10,15,15},
	},
}

return duanwu_activity_daily