-- ------------------------------
-- desc: generated by xls2data.py
-- source: 水手招募固定获得物品.xlsx
-- sheet: 普通招募固定奖励
-- ------------------------------


local lmjzm_reward_expbook = {
	['1'] = {
		['type'] = 'item',
		['id'] = 68,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = T('一级经验书'),
	},
}

return lmjzm_reward_expbook