-- ------------------------------
-- desc: generated by xls2data.py
-- source: 收益找回数值.xls
-- sheet: 活动名称对应
-- ------------------------------


local lose_found_data = {
	[1] = {
		['type'] = 1,
		['name'] = T('藏宝海湾'),
	},
	[2] = {
		['type'] = 2,
		['name'] = T('海神挑战'),
	},
	[3] = {
		['type'] = 3,
		['name'] = T('海怪突袭'),
	},
	[4] = {
		['type'] = 4,
		['name'] = T('海上运镖'),
	},
	[5] = {
		['type'] = 5,
		['name'] = T('深渊乱斗'),
	},
	[6] = {
		['type'] = 6,
		['name'] = T('商会讨伐'),
	},
	[7] = {
		['type'] = 7,
		['name'] = T('商会战争'),
	},
	[8] = {
		['type'] = 8,
		['name'] = T('特产找回'),
	},
	[9] = {
		['type'] = 9,
		['name'] = T('港口争夺'),
	},
	[10] = {
		['type'] = 10,
		['name'] = T('市政官试炼'),
	},
}

return lose_found_data