-- ------------------------------
-- desc: generated by xls2data.py
-- source: 音效配置.xls
-- sheet: 装备总表
-- ------------------------------


local music_effect_info = {
	['BT_ADVANCE'] = {
		['time'] = 3,
	},
	['BT_ATTACK_1'] = {
		['time'] = 2,
	},
	['BT_ATTACK_2'] = {
		['time'] = 2,
	},
	['BT_ATTACK_3'] = {
		['time'] = 2,
	},
	['BT_AVOID'] = {
		['time'] = 2,
	},
	['BT_CASTING'] = {
		['time'] = 1,
	},
	['BT_CHAIN_HIT'] = {
		['time'] = 2,
	},
	['BT_CHAIN_SHOT'] = {
		['time'] = 2,
	},
	['BT_DEFENSE'] = {
		['time'] = 3,
	},
	['BT_HOOK'] = {
		['time'] = 3,
	},
	['BT_REINFORCE'] = {
		['time'] = 3,
	},
	['BT_SALVO_HIT'] = {
		['time'] = 3,
	},
	['BT_SALVO_SHOT'] = {
		['time'] = 2,
	},
	['BT_SORTIE'] = {
		['time'] = 5,
	},
	['FIRE_LARGE'] = {
		['time'] = 2,
	},
	['FIRE_MEDIUM'] = {
		['time'] = 1,
	},
	['FIRE_SMALL'] = {
		['time'] = 1,
	},
	['HIT_LARGE'] = {
		['time'] = 2,
	},
	['HIT_MEDIUM'] = {
		['time'] = 1,
	},
	['HIT_SMALL'] = {
		['time'] = 1,
	},
}

return music_effect_info