-- ------------------------------
-- desc: generated by xls2data.py
-- source: 音乐音效配置总表.xls
-- sheet: 界面音效
-- ------------------------------


local music_info = {
	['COMMON_BUTTON'] = {
		['res'] = 'ui/ui_click',
	},
	['COMMON_CLOSE'] = {
		['res'] = 'ui/ui_close',
	},
	['COMMON_CASH'] = {
		['res'] = 'ui/ui_silver',
	},
	['COMMON_GOLD'] = {
		['res'] = 'ui/ui_gold',
	},
	['COMMON_HONOUR'] = {
		['res'] = 'ui/ui_exp',
	},
	['MISSION_ACCEPT'] = {
		['res'] = 'ui/ui_mission_new',
	},
	['MISSION_COMPLETE'] = {
		['res'] = 'ui/ui_mission_complete',
	},
	['LEVEL_UP'] = {
		['res'] = 'ui/ui_level_up',
	},
	['COMMON_NUMBER'] = {
		['res'] = 'ui/ui_number',
	},
	['PAPER_STRETCH'] = {
		['res'] = 'ui/ui_paper_stretch',
	},
	['OPEN_BOX'] = {
		['res'] = 'ui/ui_box',
	},
	['SKILL_TRIGGER'] = {
		['res'] = 'ui/ui_skill_trigger',
	},
	['TOWN_CARD'] = {
		['res'] = 'ui/ui_card',
	},
	['GET_NEW_TITLE'] = {
		['res'] = 'ui/ui_new_title',
	},
	['PRESTIGE_RAISE'] = {
		['res'] = 'ui/ui_prestige_raise',
	},
	['PORT_INFO_UP'] = {
		['res'] = 'ui/ui_info_up',
	},
	['LOGIN_BGM'] = {
		['res'] = 'bg/bg_login',
	},
	['LOGIN_AWARD'] = {
		['res'] = 'ui/ui_enter_award_effect',
	},
	['LOGIN_NAVY_BGM'] = {
		['res'] = 'bg/bg_login_navy',
	},
	['LOGIN_NAVY_CLOTHES'] = {
		['res'] = 'ui/ui_login_navy_clothes',
	},
	['LOGIN_NAVY_WAVE'] = {
		['res'] = 'ui/ui_login_navy',
	},
	['LOGIN_ADV_BGM'] = {
		['res'] = 'bg/bg_login_adv',
	},
	['LOGIN_ADV_VIOLIN'] = {
		['res'] = 'bg/bg_login_adv_violin',
	},
	['LOGIN_ADV_WAVE'] = {
		['res'] = 'ui/ui_login_adv',
	},
	['LOGIN_PIRATE_BGM'] = {
		['res'] = 'bg/bg_login_pirate',
	},
	['LOGIN_PIRATE_WAVE'] = {
		['res'] = 'ui/ui_login_pirate',
	},
	['LOGIN_ENTER'] = {
		['res'] = 'ui/ui_login_enter',
	},
	['LOGIN_WAVE'] = {
		['res'] = 'ui/ui_login_wave',
	},
	['LOGIN_RANDOM_NAME'] = {
		['res'] = 'ui/ui_login_random_name',
	},
	['PLOT_SERIOUS'] = {
		['res'] = 'bg/bg_plot_serious',
	},
	['PLOT_ANGRY'] = {
		['res'] = 'bg/bg_plot_angry',
	},
	['PLOT_SAD'] = {
		['res'] = 'bg/bg_plot_sad',
	},
	['PLOT_CALM'] = {
		['res'] = 'bg/bg_plot_calm',
	},
	['PLOT_HAPPY'] = {
		['res'] = 'bg/bg_plot_happy',
	},
	['PLOT_WORRY'] = {
		['res'] = 'bg/bg_plot_worry',
	},
	['EX_WAVE'] = {
		['res'] = 'ui/ex_wave',
	},
	['BGM_IBERIA'] = {
		['res'] = 'bg/bg_port_iberia',
	},
	['BGM_MED'] = {
		['res'] = 'bg/bg_port_med',
	},
	['BGM_ARAB'] = {
		['res'] = 'bg/bg_port_arab',
	},
	['BGM_NORTH'] = {
		['res'] = 'bg/bg_port_north',
	},
	['BGM_AFRICA'] = {
		['res'] = 'bg/bg_port_africa',
	},
	['BGM_INDIA'] = {
		['res'] = 'bg/bg_port_india',
	},
	['BGM_SEASIA'] = {
		['res'] = 'bg/bg_port_seasia',
	},
	['BGM_CHINA'] = {
		['res'] = 'bg/bg_port_china',
	},
	['BGM_JAPAN'] = {
		['res'] = 'bg/bg_port_japan',
	},
	['BGM_LATIN'] = {
		['res'] = 'bg/bg_port_latin',
	},
	['NPC_TIPS_CLOSED'] = {
		['res'] = 'ui/ui_npc_tips_2',
	},
	['PORT_GOTOSEA'] = {
		['res'] = 'ui/ui_quay_sail',
	},
	['PORT_BATTLE'] = {
		['res'] = 'ui/ui_quay_battle',
	},
	['ENTER_PORT_FOG'] = {
		['res'] = 'ui/ui_enterport_fog',
	},
	['ENTER_PORT_NAME'] = {
		['res'] = 'ui/ui_enterport_name',
	},
	['PORT_WAREHOUSE'] = {
		['res'] = 'ui/ui_port_warehouse',
	},
	['PORT_STAFF'] = {
		['res'] = 'ui/ui_port_staff',
	},
	['PORT_SKILL'] = {
		['res'] = 'ui/ui_port_skill',
	},
	['PORT_MARKET'] = {
		['res'] = 'ui/ui_port_market',
	},
	['PORT_PUB'] = {
		['res'] = 'ui/ui_port_pub',
	},
	['PORT_TITLE'] = {
		['res'] = 'ui/ui_port_title',
	},
	['PORT_GUILD'] = {
		['res'] = 'ui/ui_port_guild',
	},
	['PORT_CITYHALL'] = {
		['res'] = 'ui/ui_port_cityhall',
	},
	['PORT_SHIPYARD'] = {
		['res'] = 'ui/ui_port_shipyard',
	},
	['PORT_MALL'] = {
		['res'] = 'ui/ui_click',
	},
	['NEW_CHAPTER'] = {
		['res'] = 'ui/ui_new_chapter',
	},
	['TOWN_INVEST'] = {
		['res'] = 'ui/ui_progressbar',
	},
	['MARKET_OK'] = {
		['res'] = 'ui/ui_trade',
	},
	['NAVIGATOR_EXP_UP'] = {
		['res'] = 'ui/ui_navigator_exp_up',
	},
	['HOTEL_CARD_DEAL'] = {
		['res'] = 'ui/ui_card_deal',
	},
	['HOTEL_CARD_FLOP'] = {
		['res'] = 'ui/ui_card_flop',
	},
	['HOTLE_CARD_SAILOR'] = {
		['res'] = 'ui/ui_card_sailor',
	},
	['SAILOR_LEVEL_UP'] = {
		['res'] = 'ui/ui_sailor_level_up',
	},
	['SAILOR_STAR_UP'] = {
		['res'] = 'ui/ui_sailor_star_up',
	},
	['SAILOR_LETTER_UP'] = {
		['res'] = 'ui/ui_sailor_letter_up',
	},
	['SHIPYARD_BUILD'] = {
		['res'] = 'ui/ui_shipyard_build',
	},
	['BOAT_REMAKE'] = {
		['res'] = 'ui/ui_boat_remake',
	},
	['SHIPYARD_DISMANTLE'] = {
		['res'] = 'ui/ui_boat_dismantle',
	},
	['SHIPYARD_DISMANTLE_AWARD'] = {
		['res'] = 'ui/ui_boat_dismantle_award',
	},
	['BOAT_UP'] = {
		['res'] = 'ui/ui_boat_up',
	},
	['ARENA_MATCH'] = {
		['res'] = 'ui/ui_arena_match',
	},
	['ARENA_STAR'] = {
		['res'] = 'ui/ui_arena_star',
	},
	['ARENA_RANK_UP'] = {
		['res'] = 'ui/ui_arena_rank_up',
	},
	['ARENA_RANK_AWARD'] = {
		['res'] = 'ui/ui_guild_gift',
	},
	['GUILD_WAREHOUSE_GIFT'] = {
		['res'] = 'ui/ui_guild_gift',
	},
	['UI_FRIE'] = {
		['res'] = 'ui/ui_burning',
	},
	['ROOM_BOOK2'] = {
		['res'] = 'ui/ui_page_fast',
	},
	['UI_GLOBE'] = {
		['res'] = 'ui/ui_globe',
	},
	['BOTTLE_ENLARGE'] = {
		['res'] = 'ui/ui_bottle_enlarge',
	},
	['UNLOCK_RELIC'] = {
		['res'] = 'ui/ui_relic',
	},
	['ROOM_BOOK'] = {
		['res'] = 'ui/ui_page_slow',
	},
	['BATTLE_BG'] = {
		['res'] = 'bg/bg_battle',
	},
	['BATTLE_BG2'] = {
		['res'] = 'bg/bg_battle2',
	},
	['UI_SKIN'] = {
		['res'] = 'ui/bt_sink',
	},
	['BATTLE_WIN'] = {
		['res'] = 'ui/bt_win',
	},
	['BATTLE_FAIL'] = {
		['res'] = 'ui/bt_lose',
	},
	['FIRE_SMALL'] = {
		['res'] = 'skill/bt_fire_small',
	},
	['FIRE_MEDIUM'] = {
		['res'] = 'skill/bt_fire_medium',
	},
	['FIRE_LARGE'] = {
		['res'] = 'skill/bt_fire_large',
	},
	['HIT_SMALL'] = {
		['res'] = 'skill/bt_hit_small',
	},
	['HIT_MEDIUM'] = {
		['res'] = 'skill/bt_hit_medium',
	},
	['HIT_LARGE'] = {
		['res'] = 'skill/bt_hit_large',
	},
	['BT_ATTACK_1'] = {
		['res'] = 'skill/bt_attack1',
	},
	['BT_ATTACK_2'] = {
		['res'] = 'skill/bt_attack2',
	},
	['BT_ATTACK_3'] = {
		['res'] = 'skill/bt_attack3',
	},
	['BT_SALVO_CASTING'] = {
		['res'] = 'skill/bt_salvo_casting',
	},
	['BT_SALVO_SHOT'] = {
		['res'] = 'skill/bt_salvo_shot',
	},
	['BT_SALVO_SHOT_1'] = {
		['res'] = 'skill/bt_salvo_shot_1',
	},
	['BT_SALVO_HIT'] = {
		['res'] = 'skill/bt_salvo_hit',
	},
	['BT_SALVO_HIT_1'] = {
		['res'] = 'skill/bt_salvo_hit_1',
	},
	['BT_CHAIN_CASTING'] = {
		['res'] = 'skill/bt_chain_casting',
	},
	['BT_CHAIN_SHOT'] = {
		['res'] = 'skill/bt_chain_shot',
	},
	['BT_CHAIN_HIT'] = {
		['res'] = 'skill/bt_chain_hit',
	},
	['BT_SORTIE'] = {
		['res'] = 'skill/bt_sortie',
	},
	['BT_SORTIE_HIT'] = {
		['res'] = 'skill/bt_sortie_hit',
	},
	['BT_HOOK_CASTING'] = {
		['res'] = 'skill/bt_hook_casting',
	},
	['BT_HOOK'] = {
		['res'] = 'skill/bt_hook',
	},
	['BT_HOOK_HIT'] = {
		['res'] = 'skill/bt_hook_hit',
	},
	['BT_DEFENSE'] = {
		['res'] = 'skill/bt_defense',
	},
	['BT_REINFORCE'] = {
		['res'] = 'skill/bt_reinforce',
	},
	['BT_REINFORCE_1'] = {
		['res'] = 'skill/bt_reinforce_1',
	},
	['BT_AVOID'] = {
		['res'] = 'skill/bt_avoid',
	},
	['BT_ADVANCE'] = {
		['res'] = 'skill/bt_advance',
	},
	['BT_GUANTONG_SHOT'] = {
		['res'] = 'skill/bt_guantong_shot',
	},
	['BT_ZHIHUIQI_SHOT'] = {
		['res'] = 'skill/bt_zhihuiqi_shot',
	},
	['BT_YANWUDAN_SHOT'] = {
		['res'] = 'skill/bt_yanwudan_shot',
	},
	['BT_HUOYANDAN_SHOT'] = {
		['res'] = 'skill/bt_huoyandan_shot',
	},
	['BT_HUOYANDAN_HIT'] = {
		['res'] = 'skill/bt_huoyandan_hit',
	},
	['BT_PUTAODAN_HIT'] = {
		['res'] = 'skill/bt_putaodan_hit',
	},
	['BT_PUTAODAN_SHOT'] = {
		['res'] = 'skill/bt_putaodan_shot',
	},
	['BT_HAOJIAO'] = {
		['res'] = 'skill/bt_haojiao',
	},
	['BT_ZIBAO'] = {
		['res'] = 'skill/bt_zibao',
	},
	['NEW_SKILL_UNLOCK'] = {
		['res'] = 'ui/ui_new_skill',
	},
	['MONSTER_DIE'] = {
		['res'] = 'ui/ui_monster_die',
	},
	['BATTLE_RESULT_WIN'] = {
		['res'] = 'ui/bt_result_win',
	},
	['BATTLE_RESULT_LOSE'] = {
		['res'] = 'ui/bt_result_lose',
	},
	['BATTLE_START'] = {
		['res'] = 'ui/bt_star',
	},
	['EX_BGM'] = {
		['res'] = 'bg/bg_explore',
	},
	['EX_AFRICA'] = {
		['res'] = 'bg/bg_explore_africa',
	},
	['EX_ALAB'] = {
		['res'] = 'bg/bg_explore_alab',
	},
	['EX_NORTH'] = {
		['res'] = 'bg/bg_explore_north',
	},
	['EX_CHINA'] = {
		['res'] = 'bg/bg_explore_china',
	},
	['EX_LATIN'] = {
		['res'] = 'bg/bg_explore_latin',
	},
	['EX_DRAGMAP'] = {
		['res'] = 'ui/ui_map',
	},
	['EX_WIND'] = {
		['res'] = 'ui/ex_wind',
	},
	['EX_THUNDER'] = {
		['res'] = 'ui/ex_thunder',
	},
	['EX_STORM'] = {
		['res'] = 'ui/ex_storm',
	},
	['EX_WHALE_DIVE'] = {
		['res'] = 'ui/ex_dive_whale',
	},
	['EX_MERMAID_DIVE'] = {
		['res'] = 'ui/ex_dive_mermaid',
	},
	['EX_SAIL_UP'] = {
		['res'] = 'ui/ex_sail_up',
	},
	['EX_SAIL_DOWN'] = {
		['res'] = 'ui/ex_sail_down',
	},
	['EX_FOG'] = {
		['res'] = 'skill/ex_fog',
	},
	['EX_THROW'] = {
		['res'] = 'skill/ex_net_throw',
	},
	['EX_STICK'] = {
		['res'] = 'skill/ex_net_fall',
	},
	['UI_CLICK_BOX'] = {
		['res'] = 'ui/ex_box',
	},
	['EX_SALVAGE'] = {
		['res'] = 'skill/ex_salvage',
	},
	['EX_ROCK_HIT'] = {
		['res'] = 'skill/ex_hit_rock',
	},
	['EX_ICE_HIT'] = {
		['res'] = 'skill/ex_hit_ice',
	},
	['EX_MONSTER1'] = {
		['res'] = 'skill/ex_monster1',
	},
	['EX_MONSTER2'] = {
		['res'] = 'skill/ex_monster2',
	},
	['EX_MONSTER3'] = {
		['res'] = 'skill/ex_monster3',
	},
	['EX_SEAGULL'] = {
		['res'] = 'ui/ex_seagull',
	},
	['EX_TWEEDLE1'] = {
		['res'] = 'ui/ex_tweedle1',
	},
	['EX_TWEEDLE2'] = {
		['res'] = 'ui/ex_tweedle2',
	},
	['EX_TWEEDLE3'] = {
		['res'] = 'ui/ex_tweedle3',
	},
	['EX_TORNADO'] = {
		['res'] = 'ui/ex_tornado',
	},
	['EX_MONSTER_CRASH'] = {
		['res'] = 'ui/ex_monster_crash',
	},
	['EX_SHARK_CRASH'] = {
		['res'] = 'ui/ex_shark_crash',
	},
	['EX_ICE_CRASH'] = {
		['res'] = 'ui/ex_ice_crash',
	},
	['EX_ROCK_CRASH'] = {
		['res'] = 'ui/ex_rock_crash',
	},
	['EX_COPY_END'] = {
		['res'] = 'ui/ex_copy_end',
	},
	['UI_NEW_PORT'] = {
		['res'] = 'ui/ui_new_port',
	},
	['BATTLE_BEGIN'] = {
		['res'] = 'ui/ui_battle_begin',
	},
	['UI_SKILL_FRAME'] = {
		['res'] = 'ui/ui_skill_frame',
	},
	['PLOT_STORY_1'] = {
		['res'] = 'bg/bg_story_1',
	},
	['PLOT_STORY_2'] = {
		['res'] = 'bg/bg_story_2',
	},
	['PLOT_STORY_3'] = {
		['res'] = 'bg/bg_story_3',
	},
	['UI_HORN'] = {
		['res'] = 'ui/ui_horn',
	},
	['UI_FIX'] = {
		['res'] = 'ui/ui_fix',
	},
	['MONSTER_COME'] = {
		['res'] = 'ui/ui_monster_come',
	},
}

return music_info