-- ------------------------------
-- desc: generated by xls2data.py
-- source: 招募物品特效配置.xlsx
-- sheet: Sheet1
-- ------------------------------


local recruit_item_effect = {
	[168] = {
		['count'] = 1,
		['effect_id'] = 'tx_0138orange',
	},
	[50] = {
		['count'] = 100,
		['effect_id'] = 'tx_0138purple',
	},
}

return recruit_item_effect