-- ------------------------------
-- desc: generated by xls2data.py
-- source: res_config.xls
-- sheet: 设置
-- ------------------------------


local res_load_format_cfg = {
	['ui/bg/bg_awake.png'] = {
		['res_format'] = 'RGBA4444',
	},
	['ui/bg/bg_bottom1.png'] = {
		['res_format'] = 'RGBA4444',
	},
	['ui/bg/bg_collect_room.png'] = {
		['res_format'] = 'RGBA4444',
	},
	['ui/bg/bg_cut.png'] = {
		['res_format'] = 'RGBA4444',
	},
	['ui/bg/bg_title.png'] = {
		['res_format'] = 'RGBA4444',
	},
	['ui/bg/bg_top.png'] = {
		['res_format'] = 'RGBA4444',
	},
	['ui/bg/bg_treasure_map.png'] = {
		['res_format'] = 'RGBA4444',
	},
	['relic_map/yiji_01.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['relic_map/yiji_02.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['relic_map/yiji_03.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_13.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_14.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_15.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_16.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_17.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_19.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_2.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_20.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_21.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_22.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_3.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_4.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_5.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_6.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_7.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_pic_8.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_week_13.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_week_20.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_week_6.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/activity_pic/activity_week_8.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_activity_adv.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_activity_navy.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_activity_pirate.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_arnea.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_award_bonus.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_award_fund.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_award_gift.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_award_idle.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_award_recharge.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_award_vip.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_battle_guide.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_captain.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_card_table.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_cityhall.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_collect_book.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_collect_sea.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_colloct_shelf.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_down.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_elite.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_guild_battle_map.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_guild_boss.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_guild_main.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_guild_match.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_hotel.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_loading.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_market.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_melee.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_middle.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_relic.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_shipyard.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_shop.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/bg/bg_warehouse.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_1.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_10.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_11.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_13.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_14.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_15.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_16.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_20.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_25.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_26.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_4.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/elite_book/bt_book_6.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_1.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_10.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_11.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_12.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_13.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_14.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_15.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_16.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_17.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_18.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_19.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_2.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_20.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_21.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_22.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_23.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_24.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_25.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_26.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_3.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_4.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_5.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_6.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_7.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_8.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/explore_port/explore_port_9.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_1.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_10.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_11.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_12.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_13.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_14.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_15.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_16.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_17.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_18.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_19.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_2.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_20.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_21.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_22.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_23.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_24.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_25.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_26.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_3.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_4.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_5.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_6.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_7.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_8.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/port/bg/port_bg_9.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/relic/relic_battle.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/relic/relic_unknown.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_1.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_10.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_100.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_11.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_12.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_13.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_16.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_17.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_18.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_19.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_2.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_20.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_21.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_3.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_4.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_5.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_6.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_7.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_8.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/story/story_9.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_01.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_02.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_03.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_04.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_05.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_06.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_07.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_08.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_09.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_10.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_11.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_12.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_13.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_14.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_15.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_16.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_17.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_18.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_19.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_20.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_21.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_22.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_23.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_24.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_25.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_26.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_27.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_28.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_29.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_30.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_31.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_32.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_33.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_34.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_35.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_36.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_37.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_38.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_39.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_40.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_41.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_42.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_43.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_44.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_45.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_46.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_47.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_49.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_50.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_51.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_52.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_53.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_54.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_55.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['ui/yiji/yiji_56.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['update/login_bg.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['update/screen_edge.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['world_map/battle_guild_map.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['world_map/stronghold_map.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['world_map/wm_arena_1.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['world_map/wm_arena_2.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['world_map/wm_arena_3.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['world_map/wm_arena_4.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['world_map/wm_arena_5.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['world_map/wm_arena_6.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['world_map/wm_arena_7.jpg'] = {
		['res_format'] = 'RGB565',
	},
	['world_map/world_map.jpg'] = {
		['res_format'] = 'RGB565',
	},
}

return res_load_format_cfg