-- ------------------------------
-- desc: generated by xls2data.py
-- source: 富文本配置.xls
-- sheet: 配置
-- ------------------------------


local richlabel_info = {
	['port'] = {
		['color'] = 'COLOR_GRASS_STROKE',
		['font'] = 'FONT_CFG_1',
		['tips'] = '',
	},
	['name'] = {
		['color'] = 'COLOR_GRASS_STROKE',
		['font'] = 'FONT_CFG_1',
		['tips'] = '',
	},
	['view'] = {
		['color'] = 'COLOR_GRASS_STROKE',
		['font'] = 'FONT_CFG_1',
		['tips'] = '',
	},
	['force'] = {
		['color'] = 'COLOR_GRASS_STROKE',
		['font'] = 'FONT_CFG_1',
		['tips'] = T('通过港口【市政厅】投资提升港口繁荣等级来获得势力等级提升，提升势力等级可得到建造更高级船只的资格。'),
	},
	['missioncolor'] = {
		['color'] = 'COLOR_YELLOW_STROKE',
		['font'] = 'FONT_CFG_1',
		['tips'] = '',
	},
	['chat_playerc'] = {
		['color'] = 'COLOR_GRASS_STROKE',
		['font'] = 'FONT_CFG_1',
		['tips'] = '',
	},
	['chat_rewardc'] = {
		['color'] = 'COLOR_GRASS_STROKE',
		['font'] = 'FONT_CFG_1',
		['tips'] = '',
	},
}

return richlabel_info