-- ------------------------------
-- desc: generated by xls2data.py
-- source: 富文本配置.xls
-- sheet: 跳转对应
-- ------------------------------


local richlabel_view_info = {
	['reward'] = {
		['word'] = T('每日登陆奖励'),
	},
	['mainBoats'] = {
		['word'] = T('船舶配置主界面'),
	},
	['town'] = {
		['word'] = T('市政厅'),
	},
	['market'] = {
		['word'] = T('交易所'),
	},
	['hotel'] = {
		['word'] = T('酒馆'),
	},
	['ship'] = {
		['word'] = T('造船厂'),
	},
	['ports'] = {
		['word'] = T('出海'),
	},
	['stronghold'] = {
		['word'] = T('出海据点'),
	},
	['fight'] = {
		['word'] = T('战役'),
	},
	['loot'] = {
		['word'] = T('港口掠夺'),
	},
	['arena'] = {
		['word'] = T('港口竞技场'),
	},
	['shipBuild'] = {
		['word'] = T('船舶建造'),
	},
	['assemble'] = {
		['word'] = T('船舶改造'),
	},
	['master'] = {
		['word'] = T('装配研究'),
	},
	['room'] = {
		['word'] = T('航海士任命'),
	},
	['collect'] = {
		['word'] = T('收藏室'),
	},
	['recruit'] = {
		['word'] = T('水手招募'),
	},
	['system'] = {
		['word'] = T('系统界面'),
	},
	['friend'] = {
		['word'] = T('好友界面'),
	},
	['foster'] = {
		['word'] = T('航海士列表'),
	},
	['singled'] = {
		['word'] = T('单挑设置'),
	},
	['fleet'] = {
		['word'] = T('舰队系统界面'),
	},
	['guild'] = {
		['word'] = T('海神宝藏界面'),
	},
	['achieve'] = {
		['word'] = T('成就界面'),
	},
	['hotelReward'] = {
		['word'] = T('酒馆悬赏界面'),
	},
	['hotelRecruit'] = {
		['word'] = T('酒馆招募界面'),
	},
	['regVipView'] = {
		['word'] = T('海神宝藏大礼包'),
	},
	['baoWu'] = {
		['word'] = T('宝物系统'),
	},
	['captainLv'] = {
		['word'] = T('船长信息界面'),
	},
	['chatSystem'] = {
		['word'] = T('聊天界面'),
	},
	['competition'] = {
		['word'] = T('每日活动'),
	},
	['syllabus'] = {
		['word'] = T('每日课程表'),
	},
}

return richlabel_view_info