-- ------------------------------
-- desc: generated by xls2data.py
-- source: 海神坐标.xls
-- sheet: 海神boss
-- ------------------------------


local seagod_boss_data = {
	[48] = {
		['head_ui'] = 2,
		['sailor_id'] = 82,
	},
	[49] = {
		['head_ui'] = 1,
		['sailor_id'] = 62,
	},
	[50] = {
		['head_ui'] = 3,
		['sailor_id'] = 69,
	},
	[51] = {
		['head_ui'] = 2,
		['sailor_id'] = 59,
	},
	[52] = {
		['head_ui'] = 1,
		['sailor_id'] = 78,
	},
	[53] = {
		['head_ui'] = 2,
		['sailor_id'] = 60,
	},
	[54] = {
		['head_ui'] = 3,
		['sailor_id'] = 67,
	},
	[55] = {
		['head_ui'] = 2,
		['sailor_id'] = 53,
	},
	[56] = {
		['head_ui'] = 2,
		['sailor_id'] = 83,
	},
	[57] = {
		['head_ui'] = 3,
		['sailor_id'] = 72,
	},
}

return seagod_boss_data