-- ------------------------------
-- desc: generated by xls2data.py
-- source: status.xls
-- sheet: 数值
-- ------------------------------


local status_info = {
	['explore_boat_speed'] = {
		['name'] = '',
		['BattleHonourRaise'] = 0,
		['SellGoodsProfitRaise'] = 0,
		['ExploreDriveSpeedRaise'] = 130,
		['RoleExpRaise'] = 0,
		['ExploreSailorExpRaise'] = 0,
		['fight_buff'] = {},
		['tips'] = T('探索行驶速度提升%s'),
		['icon'] = '',
		['buff_name'] = '',
	},
	['port_battle_exp_buff'] = {
		['name'] = '',
		['BattleHonourRaise'] = 0,
		['SellGoodsProfitRaise'] = 0,
		['ExploreDriveSpeedRaise'] = 0,
		['RoleExpRaise'] = 20,
		['ExploreSailorExpRaise'] = 0,
		['fight_buff'] = {},
		['tips'] = T('主角获得经验提升%s'),
		['icon'] = '#main_buff_exp.png',
		['buff_name'] = T('人物经验buff'),
	},
	['contend_ban_explore'] = {
		['name'] = '',
		['BattleHonourRaise'] = 0,
		['SellGoodsProfitRaise'] = 0,
		['ExploreDriveSpeedRaise'] = 0,
		['RoleExpRaise'] = 0,
		['ExploreSailorExpRaise'] = 0,
		['fight_buff'] = {},
		['tips'] = '',
		['icon'] = '',
		['buff_name'] = '',
	},
	['contend_status'] = {
		['name'] = '',
		['BattleHonourRaise'] = 0,
		['SellGoodsProfitRaise'] = 0,
		['ExploreDriveSpeedRaise'] = 0,
		['RoleExpRaise'] = 0,
		['ExploreSailorExpRaise'] = 0,
		['fight_buff'] = {},
		['tips'] = '',
		['icon'] = '',
		['buff_name'] = '',
	},
}

return status_info