-- ------------------------------
-- desc: generated by xls2data.py
-- source: base_view_control.xls
-- sheet: 设置
-- ------------------------------


local view_logic_cfg = {
	['ClsPrestigeMainUI'] = {
		['is_move_stop'] = 0,
		['is_member_lock'] = 1,
		['is_stop_food_down'] = 0,
		['is_explore_lock'] = 0,
	},
	['ClsMissionMainUI'] = {
		['is_move_stop'] = 0,
		['is_member_lock'] = 1,
		['is_stop_food_down'] = 0,
		['is_explore_lock'] = 0,
	},
	['ClsPortMarket'] = {
		['is_move_stop'] = 0,
		['is_member_lock'] = 1,
		['is_stop_food_down'] = 0,
		['is_explore_lock'] = 0,
	},
	['ClsAppointTradeUI'] = {
		['is_move_stop'] = 0,
		['is_member_lock'] = 1,
		['is_stop_food_down'] = 0,
		['is_explore_lock'] = 1,
	},
	['ClsGuildTaskPanel'] = {
		['is_move_stop'] = 0,
		['is_member_lock'] = 1,
		['is_stop_food_down'] = 0,
		['is_explore_lock'] = 0,
	},
	['ClsArenaMainUI'] = {
		['is_move_stop'] = 0,
		['is_member_lock'] = 1,
		['is_stop_food_down'] = 0,
		['is_explore_lock'] = 1,
	},
	['ClsEliteBattleUI'] = {
		['is_move_stop'] = 0,
		['is_member_lock'] = 1,
		['is_stop_food_down'] = 0,
		['is_explore_lock'] = 1,
	},
	['ClsRelicDiscoverUI'] = {
		['is_move_stop'] = 1,
		['is_member_lock'] = 1,
		['is_stop_food_down'] = 1,
		['is_explore_lock'] = 0,
	},
	['TreasureMapLayer'] = {
		['is_move_stop'] = 0,
		['is_member_lock'] = 1,
		['is_stop_food_down'] = 0,
		['is_explore_lock'] = 0,
	},
	['GuildBossUI'] = {
		['is_move_stop'] = 0,
		['is_member_lock'] = 1,
		['is_stop_food_down'] = 0,
		['is_explore_lock'] = 1,
	},
}

return view_logic_cfg