-- ------------------------------
-- desc: generated by xls2data.py
-- source: 五一活动表.xls
-- sheet: 五一活动充值
-- ------------------------------


local wuyi_activity_money = {
	[1] = {
		['top_ups_num'] = 100,
		['sea_heart_num'] = 1,
	},
	[2] = {
		['top_ups_num'] = 300,
		['sea_heart_num'] = 2,
	},
	[3] = {
		['top_ups_num'] = 500,
		['sea_heart_num'] = 3,
	},
	[4] = {
		['top_ups_num'] = 1000,
		['sea_heart_num'] = 5,
	},
	[5] = {
		['top_ups_num'] = 2000,
		['sea_heart_num'] = 10,
	},
	[6] = {
		['top_ups_num'] = 3000,
		['sea_heart_num'] = 10,
	},
	[7] = {
		['top_ups_num'] = 5000,
		['sea_heart_num'] = 20,
	},
}

return wuyi_activity_money