-- ------------------------------
-- desc: generated by xls2data.py
-- source: 水手招募固定获得物品.xlsx
-- sheet: 钻石招募固定奖励
-- ------------------------------


local zszm_reward_expbook = {
	['1'] = {
		['type'] = 'item',
		['id'] = 69,
		['cnt'] = 5,
		['rate'] = 100,
		['memo'] = T('三级经验书'),
	},
}

return zszm_reward_expbook