-- ------------------------------
-- desc: generated by xls2data.py
-- source: 市政官config.xls
-- sheet: 市政官试炼
-- ------------------------------


local city_challenge_data = {
	[1] = {
		['type'] = T('限时'),
		['name'] = T('市政官的试炼'),
		['target_tips'] = {T("好战的"),"#%s",T("执政者向我们下了战书")},
		['mission_tips'] = {T("%s的执政者听闻有一支打败阿芒德的年轻队伍，战斗狂热的他迫切与我们一战")},
		['skip_info'] = 'ports',
	},
	[2] = {
		['type'] = T('限时'),
		['name'] = T('市政官的试炼'),
		['target_tips'] = {T("与"),"#%s",T("市政官切磋武艺")},
		['mission_tips'] = {T("%s的市政官热衷与各种强者交朋友，我们去会一会他吧")},
		['skip_info'] = 'ports',
	},
	[3] = {
		['type'] = T('限时'),
		['name'] = T('市政官的试炼'),
		['target_tips'] = {T("前进，我们的目标是"),"#%s"},
		['mission_tips'] = {T("%s的市政官听闻我们寻找世界尽头，就想与我们交流交流一番")},
		['skip_info'] = 'ports',
	},
	[4] = {
		['type'] = T('限时'),
		['name'] = T('市政官的试炼'),
		['target_tips'] = {T("赢得"),"#%s",T("人民的尊重")},
		['mission_tips'] = {T("%s的市政官告诉我们，获得他们的尊重很简单，战胜他们")},
		['skip_info'] = 'ports',
	},
	[5] = {
		['type'] = T('限时'),
		['name'] = T('市政官的试炼'),
		['target_tips'] = {T("前往"),"#%s",T("挑战当地市政官")},
		['mission_tips'] = {T("%s的市政官听说有我们要前往世界尽头，特别想跟我们切磋一下。")},
		['skip_info'] = 'ports',
	},
	[6] = {
		['type'] = T('限时'),
		['name'] = T('市政官的试炼'),
		['target_tips'] = {T("前往"),"#%s",T("挑战当地市政官")},
		['mission_tips'] = {T("%s的市政官听说有我们要前往世界尽头，特别想跟我们切磋一下。")},
		['skip_info'] = 'ports',
	},
}

return city_challenge_data