-- ------------------------------
-- desc: generated by xls2data.py
-- source: item.xls
-- sheet: 道具特殊消耗配置
-- ------------------------------


local item_use_cost = {
	[1] = {
		['cash_count'] = 7000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 28000,
	},
	[2] = {
		['cash_count'] = 7000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 28000,
	},
	[3] = {
		['cash_count'] = 7000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 28000,
	},
	[4] = {
		['cash_count'] = 8000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 32000,
	},
	[5] = {
		['cash_count'] = 8000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 32000,
	},
	[6] = {
		['cash_count'] = 8000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 32000,
	},
	[7] = {
		['cash_count'] = 9000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 36000,
	},
	[8] = {
		['cash_count'] = 9000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 36000,
	},
	[9] = {
		['cash_count'] = 10000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 40000,
	},
	[10] = {
		['cash_count'] = 10000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 40000,
	},
	[11] = {
		['cash_count'] = 10000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 40000,
	},
	[12] = {
		['cash_count'] = 11000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 44000,
	},
	[13] = {
		['cash_count'] = 11000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 44000,
	},
	[14] = {
		['cash_count'] = 12000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 48000,
	},
	[15] = {
		['cash_count'] = 12000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 48000,
	},
	[16] = {
		['cash_count'] = 13000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 52000,
	},
	[17] = {
		['cash_count'] = 13000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 52000,
	},
	[18] = {
		['cash_count'] = 14000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 56000,
	},
	[19] = {
		['cash_count'] = 14000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 56000,
	},
	[20] = {
		['cash_count'] = 15000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 60000,
	},
	[21] = {
		['cash_count'] = 15000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 60000,
	},
	[22] = {
		['cash_count'] = 16000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 64000,
	},
	[23] = {
		['cash_count'] = 17000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 68000,
	},
	[24] = {
		['cash_count'] = 17000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 68000,
	},
	[25] = {
		['cash_count'] = 18000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 72000,
	},
	[26] = {
		['cash_count'] = 19000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 76000,
	},
	[27] = {
		['cash_count'] = 20000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 80000,
	},
	[28] = {
		['cash_count'] = 21000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 84000,
	},
	[29] = {
		['cash_count'] = 21000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 84000,
	},
	[30] = {
		['cash_count'] = 22000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 88000,
	},
	[31] = {
		['cash_count'] = 23000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 92000,
	},
	[32] = {
		['cash_count'] = 24000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 96000,
	},
	[33] = {
		['cash_count'] = 25000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 100000,
	},
	[34] = {
		['cash_count'] = 26000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 104000,
	},
	[35] = {
		['cash_count'] = 27000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 108000,
	},
	[36] = {
		['cash_count'] = 28000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 112000,
	},
	[37] = {
		['cash_count'] = 30000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 120000,
	},
	[38] = {
		['cash_count'] = 31000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 124000,
	},
	[39] = {
		['cash_count'] = 32000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 128000,
	},
	[40] = {
		['cash_count'] = 33000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 132000,
	},
	[41] = {
		['cash_count'] = 35000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 140000,
	},
	[42] = {
		['cash_count'] = 36000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 144000,
	},
	[43] = {
		['cash_count'] = 38000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 152000,
	},
	[44] = {
		['cash_count'] = 39000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 156000,
	},
	[45] = {
		['cash_count'] = 41000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 164000,
	},
	[46] = {
		['cash_count'] = 43000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 172000,
	},
	[47] = {
		['cash_count'] = 44000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 176000,
	},
	[48] = {
		['cash_count'] = 46000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 184000,
	},
	[49] = {
		['cash_count'] = 48000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 192000,
	},
	[50] = {
		['cash_count'] = 50000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 200000,
	},
	[51] = {
		['cash_count'] = 52000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 208000,
	},
	[52] = {
		['cash_count'] = 54000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 216000,
	},
	[53] = {
		['cash_count'] = 57000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 228000,
	},
	[54] = {
		['cash_count'] = 59000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 236000,
	},
	[55] = {
		['cash_count'] = 61000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 244000,
	},
	[56] = {
		['cash_count'] = 64000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 256000,
	},
	[57] = {
		['cash_count'] = 67000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 268000,
	},
	[58] = {
		['cash_count'] = 69000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 276000,
	},
	[59] = {
		['cash_count'] = 72000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 288000,
	},
	[60] = {
		['cash_count'] = 75000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 300000,
	},
	[61] = {
		['cash_count'] = 78000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 312000,
	},
	[62] = {
		['cash_count'] = 82000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 328000,
	},
	[63] = {
		['cash_count'] = 85000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 340000,
	},
	[64] = {
		['cash_count'] = 88000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 352000,
	},
	[65] = {
		['cash_count'] = 92000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 368000,
	},
	[66] = {
		['cash_count'] = 96000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 384000,
	},
	[67] = {
		['cash_count'] = 100000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 400000,
	},
	[68] = {
		['cash_count'] = 104000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 416000,
	},
	[69] = {
		['cash_count'] = 108000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 432000,
	},
	[70] = {
		['cash_count'] = 113000,
		['gold_count'] = 150,
		['shbx_cash_count'] = 452000,
	},
}

return item_use_cost