-- ------------------------------
-- desc: generated by xls2data.py
-- source: 水手config.xls
-- sheet: 技能施放警告
-- ------------------------------


local skill_warning = {
	['UNKNOW'] = {
		['msg'] = T('未知原因'),
	},
	['OK'] = {
		['msg'] = T('可使用'),
	},
	['DEADED'] = {
		['msg'] = T('目标已死亡'),
	},
	['CD'] = {
		['msg'] = T('技能尚未冷却'),
	},
	['COMMON_CD'] = {
		['msg'] = T('技能施放间隔太短，请稍后再试'),
	},
	['HP'] = {
		['msg'] = T('气血不足'),
	},
	['ANGER'] = {
		['msg'] = T('怒气不足'),
	},
	['IN_DIS'] = {
		['msg'] = T('目标距离太近无法施放'),
	},
	['OUT_DIS'] = {
		['msg'] = T('目标距离太远无法施放'),
	},
	['NO_TARGET'] = {
		['msg'] = T('没有目标或目标不在范围内'),
	},
	['NO_SPEED'] = {
		['msg'] = T('没有移动速度，操作失败'),
	},
	['NO_NEAR'] = {
		['msg'] = T('没有近战伤害，操作失败'),
	},
	['NONE'] = {
		['msg'] = T('没有该技能'),
	},
	['STATUS_LIMIT'] = {
		['msg'] = T('状态限制中，无法操作'),
	},
	['CHAOFENG'] = {
		['msg'] = T('被嘲讽，无法移动和改变目标'),
	},
	['CHENMO'] = {
		['msg'] = T('沉默状态中，无法施放技能'),
	},
}

return skill_warning