-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役星级奖励.xls
-- sheet: reward_jyzy_area7_star1
-- ------------------------------


local reward_jyzy_area7_star1 = {
	['1'] = {
		['type'] = 'material',
		['id'] = 1501,
		['cnt'] = 10,
		['rate'] = 1,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 120,
		['rate'] = 1,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 20000,
		['rate'] = 1,
		['memo'] = '',
	},
}

return reward_jyzy_area7_star1