-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役星级奖励.xls
-- sheet: reward_jyzy_area12_star3
-- ------------------------------


local reward_jyzy_area12_star3 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 3,
		['cnt'] = 150,
		['rate'] = 1,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 1000,
		['rate'] = 1,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 100000,
		['rate'] = 1,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'item',
		['id'] = 63,
		['cnt'] = 15,
		['rate'] = 1,
		['memo'] = '',
	},
}

return reward_jyzy_area12_star3