-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役星级奖励.xls
-- sheet: reward_jyzy_area19_star3
-- ------------------------------


local reward_jyzy_area19_star3 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 106,
		['cnt'] = 2,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 4000,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 800000,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'item',
		['id'] = 63,
		['cnt'] = 60,
		['rate'] = 1,
		['memo'] = '',
	},
}

return reward_jyzy_area19_star3