-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役星级奖励.xls
-- sheet: reward_jyzy_area4_star2
-- ------------------------------


local reward_jyzy_area4_star2 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 50,
		['cnt'] = 20,
		['rate'] = 1,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 90,
		['rate'] = 1,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 15000,
		['rate'] = 1,
		['memo'] = '',
	},
}

return reward_jyzy_area4_star2