-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役星级奖励.xls
-- sheet: reward_jyzy_area3_star1
-- ------------------------------


local reward_jyzy_area3_star1 = {
	['1'] = {
		['type'] = 'material',
		['id'] = 1501,
		['cnt'] = 5,
		['rate'] = 0,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 70,
		['rate'] = 0,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 10000,
		['rate'] = 0,
		['memo'] = '',
	},
}

return reward_jyzy_area3_star1