-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役星级奖励.xls
-- sheet: reward_jyzy_area16_star2
-- ------------------------------


local reward_jyzy_area16_star2 = {
	['1'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 200,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 1000,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 100000,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_jyzy_area16_star2