-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役星级奖励.xls
-- sheet: reward_jyzy_area11_star2
-- ------------------------------


local reward_jyzy_area11_star2 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 50,
		['cnt'] = 60,
		['rate'] = 1,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'prosper',
		['id'] = 0,
		['cnt'] = 300,
		['rate'] = 1,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 40000,
		['rate'] = 1,
		['memo'] = '',
	},
}

return reward_jyzy_area11_star2