-- ------------------------------
-- desc: generated by xls2data.py
-- source: 副本原型表.xls
-- sheet: 副本海水配色表
-- ------------------------------


local copy_scene_sea_cfg = {
	['seagod_lv_1'] = {
		['sea_cfg'] = {u_centerColor1={0.6392157,0.9960784,1,0},u_edgeColor1={0.8,1,0.9960784,0.7019608},u_centerColor2={0.3529412,0.8117647,0.6980392,0.8588235},u_edgeColor2={0.08627451,0.2196078,0.3176471,0.9176471},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_2'] = {
		['sea_cfg'] = {u_centerColor1={0.6392157,0.9960784,1,0},u_edgeColor1={0.8,1,0.9960784,0.7019608},u_centerColor2={0.3529412,0.8117647,0.6980392,0.8588235},u_edgeColor2={0.08627451,0.2196078,0.3176471,0.9176471},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_3'] = {
		['sea_cfg'] = {u_centerColor1={0.6392157,0.9960784,1,0},u_edgeColor1={0.8,1,0.9960784,0.7019608},u_centerColor2={0.3529412,0.8117647,0.6980392,0.8588235},u_edgeColor2={0.08627451,0.2196078,0.3176471,0.9176471},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_4'] = {
		['sea_cfg'] = {u_centerColor1={0.6392157,0.9960784,1,0},u_edgeColor1={0.8,1,0.9960784,0.7019608},u_centerColor2={0.3529412,0.8117647,0.6980392,0.8588235},u_edgeColor2={0.08627451,0.2196078,0.3176471,0.9176471},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_5'] = {
		['sea_cfg'] = {u_centerColor1={0.6392157,0.9960784,1,0},u_edgeColor1={0.8,1,0.9960784,0.7019608},u_centerColor2={0.3529412,0.8117647,0.6980392,0.8588235},u_edgeColor2={0.08627451,0.2196078,0.3176471,0.9176471},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_6'] = {
		['sea_cfg'] = {u_centerColor1={0.6392157,0.9960784,1,0},u_edgeColor1={0.8,1,0.9960784,0.7019608},u_centerColor2={0.3529412,0.8117647,0.6980392,0.8588235},u_edgeColor2={0.08627451,0.2196078,0.3176471,0.9176471},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_7'] = {
		['sea_cfg'] = {u_centerColor1={0.6392157,0.9960784,1,0},u_edgeColor1={0.8,1,0.9960784,0.7019608},u_centerColor2={0.3529412,0.8117647,0.6980392,0.8588235},u_edgeColor2={0.08627451,0.2196078,0.3176471,0.9176471},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_8'] = {
		['sea_cfg'] = {u_centerColor1={0.6392157,0.9960784,1,0},u_edgeColor1={0.8,1,0.9960784,0.7019608},u_centerColor2={0.3529412,0.8117647,0.6980392,0.8588235},u_edgeColor2={0.08627451,0.2196078,0.3176471,0.9176471},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_9'] = {
		['sea_cfg'] = {u_centerColor1={0.6392157,0.9960784,1,0},u_edgeColor1={0.8,1,0.9960784,0.7019608},u_centerColor2={0.3529412,0.8117647,0.6980392,0.8588235},u_edgeColor2={0.08627451,0.2196078,0.3176471,0.9176471},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_10'] = {
		['sea_cfg'] = {u_centerColor1={0.6392157,0.9960784,1,0},u_edgeColor1={0.8,1,0.9960784,0.7019608},u_centerColor2={0.3529412,0.8117647,0.6980392,0.8588235},u_edgeColor2={0.08627451,0.2196078,0.3176471,0.9176471},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_11'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={0.94,1,0.39,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_12'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={0.94,1,0.39,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_13'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={0.94,1,0.39,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_14'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={0.94,1,0.39,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_15'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={0.94,1,0.39,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_16'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={0.94,1,0.39,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_17'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={0.94,1,0.39,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_18'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={0.94,1,0.39,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_19'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={0.94,1,0.39,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_20'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={0.94,1,0.39,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_21'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_22'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_23'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_24'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_25'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_26'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_27'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_28'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_29'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_30'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_31'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
	['seagod_lv_32'] = {
		['sea_cfg'] = {u_centerColor1={1,1,1,0},u_edgeColor1={1,1,1,0.7},u_centerColor2={1,0.72,0.27,0.85},u_edgeColor2 = {0,0.2,0.3,0.9},u_foamTex={"sea_normals5.png"}},
	},
}

return copy_scene_sea_cfg