-- ------------------------------
-- desc: generated by xls2data.py
-- source: 寻宝副本任务.xlsx
-- sheet: Sheet1
-- ------------------------------


local copy_scene_mission = {
	[1] = {
		['name'] = T('击破礁石'),
		['event_id'] = 1,
	},
	[2] = {
		['name'] = T('击破浮冰'),
		['event_id'] = 2,
	},
	[3] = {
		['name'] = T('捕获海怪'),
		['event_id'] = 19,
	},
	[4] = {
		['name'] = T('捕获鲨鱼'),
		['event_id'] = 3,
	},
}

return copy_scene_mission