-- ------------------------------
-- desc: generated by xls2data.py
-- source: 乱斗积分表.xls
-- sheet: 乱斗积分表
-- ------------------------------


local melee_score = {
	[1] = {
		['all_score'] = 0,
		['name_color'] = COLOR_WHITE_STROKE,
	},
	[2] = {
		['all_score'] = 5,
		['name_color'] = COLOR_GREEN_STROKE,
	},
	[3] = {
		['all_score'] = 10,
		['name_color'] = COLOR_BLUE_STROKE,
	},
	[4] = {
		['all_score'] = 15,
		['name_color'] = COLOR_PURPLE_STROKE,
	},
	[5] = {
		['all_score'] = 20,
		['name_color'] = COLOR_ORANGE_STROKE,
	},
}

return melee_score