-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口争夺战场景事件.xlsx
-- sheet: Sheet2
-- ------------------------------


local port_battle_model = {
	[1] = {
		['model'] = '80',
		['build'] = 59600,
	},
	[2] = {
		['model'] = '81',
		['build'] = 79200,
	},
	[3] = {
		['model'] = '82',
		['build'] = 98800,
	},
	[4] = {
		['model'] = '83',
		['build'] = 118400,
	},
	[5] = {
		['model'] = '76',
		['build'] = 138000,
	},
}

return port_battle_model