-- ------------------------------
-- desc: generated by xls2data.py
-- source: 副本原型表.xls
-- sheet: qte_config
-- ------------------------------


local qte_config = {
	[1] = {
		['name'] = T('攻击'),
		['event_type'] = 'attack',
		['res'] = '#explore_ore_attack.png',
		['dialog'] = 189,
	},
	[2] = {
		['name'] = T('防御'),
		['event_type'] = 'defense',
		['res'] = '#explore_ore_denfense.png',
		['dialog'] = 191,
	},
	[3] = {
		['name'] = T('收集'),
		['event_type'] = 'collect',
		['res'] = '#explore_btn_collect.png',
		['dialog'] = 193,
	},
	[4] = {
		['name'] = T('补给'),
		['event_type'] = 'supply',
		['res'] = '#explore_btn_fix.png',
		['dialog'] = 194,
	},
}

return qte_config