-- ------------------------------
-- desc: generated by xls2data.py
-- source: 副本称号显示.xls
-- sheet: 副本称号显示
-- ------------------------------


local scene_title = {
	[1] = {
		['name'] = T('大杀特杀'),
		['font_size'] = 16,
		['font_color'] = 2,
		['kill'] = 3,
		['scale'] = 1.0,
	},
	[2] = {
		['name'] = T('无人能挡'),
		['font_size'] = 16,
		['font_color'] = 3,
		['kill'] = 5,
		['scale'] = 1.0,
	},
	[3] = {
		['name'] = T('杀人如麻'),
		['font_size'] = 16,
		['font_color'] = 4,
		['kill'] = 7,
		['scale'] = 1.1,
	},
	[4] = {
		['name'] = T('一夫当关'),
		['font_size'] = 16,
		['font_color'] = 5,
		['kill'] = 10,
		['scale'] = 1.2,
	},
}

return scene_title