-- ------------------------------
-- desc: generated by xls2data.py
-- source: boat_config.xls
-- sheet: 船舶洗练消耗金币
-- ------------------------------


local boat_xilian_cost = {
	[1] = {
		['level'] = 0,
		['boat_xilian_cash'] = 500,
	},
	[2] = {
		['level'] = 10,
		['boat_xilian_cash'] = 2000,
	},
	[3] = {
		['level'] = 20,
		['boat_xilian_cash'] = 2000,
	},
	[4] = {
		['level'] = 26,
		['boat_xilian_cash'] = 2000,
	},
	[5] = {
		['level'] = 29,
		['boat_xilian_cash'] = 15000,
	},
	[6] = {
		['level'] = 32,
		['boat_xilian_cash'] = 15000,
	},
	[7] = {
		['level'] = 34,
		['boat_xilian_cash'] = 15000,
	},
	[8] = {
		['level'] = 37,
		['boat_xilian_cash'] = 15000,
	},
	[9] = {
		['level'] = 40,
		['boat_xilian_cash'] = 45000,
	},
	[10] = {
		['level'] = 42,
		['boat_xilian_cash'] = 45000,
	},
	[11] = {
		['level'] = 45,
		['boat_xilian_cash'] = 45000,
	},
	[12] = {
		['level'] = 47,
		['boat_xilian_cash'] = 45000,
	},
	[13] = {
		['level'] = 50,
		['boat_xilian_cash'] = 150000,
	},
	[14] = {
		['level'] = 52,
		['boat_xilian_cash'] = 150000,
	},
	[15] = {
		['level'] = 55,
		['boat_xilian_cash'] = 150000,
	},
	[16] = {
		['level'] = 57,
		['boat_xilian_cash'] = 150000,
	},
	[17] = {
		['level'] = 60,
		['boat_xilian_cash'] = 500000,
	},
	[18] = {
		['level'] = 62,
		['boat_xilian_cash'] = 500000,
	},
	[19] = {
		['level'] = 65,
		['boat_xilian_cash'] = 500000,
	},
	[20] = {
		['level'] = 68,
		['boat_xilian_cash'] = 500000,
	},
}

return boat_xilian_cost