-- ------------------------------
-- desc: generated by xls2data.py
-- source: boat_config.xls
-- sheet: 船舶拆解
-- ------------------------------


local boat_fleet_config = {
	[1] = {
		['level'] = 0,
		['quality_2'] = {[106]=1},
		['quality_3'] = {[106]=1},
		['quality_4'] = {[106]=2},
		['quality_5'] = {},
	},
	[2] = {
		['level'] = 10,
		['quality_2'] = {[106]=1},
		['quality_3'] = {[106]=1},
		['quality_4'] = {[106]=2},
		['quality_5'] = {},
	},
	[3] = {
		['level'] = 20,
		['quality_2'] = {[106]=1},
		['quality_3'] = {[106]=1},
		['quality_4'] = {[106]=4},
		['quality_5'] = {},
	},
	[4] = {
		['level'] = 26,
		['quality_2'] = {[106]=1},
		['quality_3'] = {[106]=1},
		['quality_4'] = {[106]=4},
		['quality_5'] = {},
	},
	[5] = {
		['level'] = 29,
		['quality_2'] = {[106]=1},
		['quality_3'] = {[106]=2},
		['quality_4'] = {[106]=8},
		['quality_5'] = {},
	},
	[6] = {
		['level'] = 32,
		['quality_2'] = {[106]=1},
		['quality_3'] = {[106]=2},
		['quality_4'] = {[106]=8},
		['quality_5'] = {},
	},
	[7] = {
		['level'] = 34,
		['quality_2'] = {[106]=1},
		['quality_3'] = {[106]=2},
		['quality_4'] = {[106]=8},
		['quality_5'] = {},
	},
	[8] = {
		['level'] = 37,
		['quality_2'] = {[106]=1},
		['quality_3'] = {[106]=2},
		['quality_4'] = {[106]=8},
		['quality_5'] = {},
	},
	[9] = {
		['level'] = 40,
		['quality_2'] = {[106]=2},
		['quality_3'] = {[106]=5},
		['quality_4'] = {[162]=2},
		['quality_5'] = {},
	},
	[10] = {
		['level'] = 42,
		['quality_2'] = {[106]=2},
		['quality_3'] = {[106]=5},
		['quality_4'] = {[162]=2},
		['quality_5'] = {},
	},
	[11] = {
		['level'] = 45,
		['quality_2'] = {[106]=2},
		['quality_3'] = {[106]=5},
		['quality_4'] = {[162]=2},
		['quality_5'] = {},
	},
	[12] = {
		['level'] = 47,
		['quality_2'] = {[106]=2},
		['quality_3'] = {[106]=5},
		['quality_4'] = {[162]=2},
		['quality_5'] = {},
	},
	[13] = {
		['level'] = 50,
		['quality_2'] = {[106]=3},
		['quality_3'] = {[162]=1},
		['quality_4'] = {[162]=4},
		['quality_5'] = {},
	},
	[14] = {
		['level'] = 52,
		['quality_2'] = {[106]=3},
		['quality_3'] = {[162]=1},
		['quality_4'] = {[162]=4},
		['quality_5'] = {},
	},
	[15] = {
		['level'] = 55,
		['quality_2'] = {[106]=3},
		['quality_3'] = {[162]=1},
		['quality_4'] = {[162]=4},
		['quality_5'] = {},
	},
	[16] = {
		['level'] = 57,
		['quality_2'] = {[106]=3},
		['quality_3'] = {[162]=1},
		['quality_4'] = {[162]=4},
		['quality_5'] = {},
	},
	[17] = {
		['level'] = 60,
		['quality_2'] = {[106]=3},
		['quality_3'] = {[162]=1},
		['quality_4'] = {[162]=4},
		['quality_5'] = {},
	},
	[18] = {
		['level'] = 24,
		['quality_2'] = {},
		['quality_3'] = {},
		['quality_4'] = {},
		['quality_5'] = {[106]=10},
	},
	[19] = {
		['level'] = 62,
		['quality_2'] = {[106]=5},
		['quality_3'] = {[162]=2},
		['quality_4'] = {[162]=6},
		['quality_5'] = {},
	},
	[20] = {
		['level'] = 65,
		['quality_2'] = {[106]=5},
		['quality_3'] = {[162]=2},
		['quality_4'] = {[162]=6},
		['quality_5'] = {},
	},
	[21] = {
		['level'] = 68,
		['quality_2'] = {[106]=5},
		['quality_3'] = {[162]=2},
		['quality_4'] = {[162]=6},
		['quality_5'] = {},
	},
}

return boat_fleet_config