-- ------------------------------
-- desc: generated by xls2data.py
-- source: boat_config.xls
-- sheet: 船只类型图标
-- ------------------------------


local boat_type_icon = {
	[1] = {
		['boat_icon'] = 'common_job_pirate.png',
	},
	[2] = {
		['boat_icon'] = 'common_job_navy.png',
	},
	[3] = {
		['boat_icon'] = 'common_job_adventure.png',
	},
	[5] = {
		['boat_icon'] = 'common_job_navy.png',
	},
}

return boat_type_icon