-- ------------------------------
-- desc: generated by xls2data.py
-- source: boat_config.xls
-- sheet: 船舶突破属性显示（客户端）
-- ------------------------------


local boat_breakthrough_xianshi = {
	[1] = {
		['boat_breakthrough_icon'] = '#ship_skill_assist_1.png',
		['boat_breakthrough_txt'] = T('速度'),
		['boat_breakthrough_value'] = '10',
		['boat_breakthrough_name'] = T('风声'),
	},
	[2] = {
		['boat_breakthrough_icon'] = '#ship_skill_near_2.png',
		['boat_breakthrough_txt'] = T('伤害增幅'),
		['boat_breakthrough_value'] = '5%',
		['boat_breakthrough_name'] = T('重伤'),
	},
	[3] = {
		['boat_breakthrough_icon'] = '#ship_skill_defense_3.png',
		['boat_breakthrough_txt'] = T('伤害减免'),
		['boat_breakthrough_value'] = '5%',
		['boat_breakthrough_name'] = T('护盾'),
	},
	[4] = {
		['boat_breakthrough_icon'] = '#ship_skill_attack_4.png',
		['boat_breakthrough_txt'] = T('射程'),
		['boat_breakthrough_value'] = '50',
		['boat_breakthrough_name'] = T('远射'),
	},
	[5] = {
		['boat_breakthrough_icon'] = '#ship_skill_near_3.png',
		['boat_breakthrough_txt'] = T('伤害增幅'),
		['boat_breakthrough_value'] = '10%',
		['boat_breakthrough_name'] = T('要害'),
	},
	[6] = {
		['boat_breakthrough_icon'] = '#ship_skill_defense_4.png',
		['boat_breakthrough_txt'] = T('伤害减免'),
		['boat_breakthrough_value'] = '10%',
		['boat_breakthrough_name'] = T('厚甲'),
	},
	[7] = {
		['boat_breakthrough_icon'] = '#ship_skill_near_4.png',
		['boat_breakthrough_txt'] = T('伤害增幅'),
		['boat_breakthrough_value'] = '15%',
		['boat_breakthrough_name'] = T('致命'),
	},
}

return boat_breakthrough_xianshi