-- ------------------------------
-- desc: generated by xls2data.py
-- source: boat_config.xls
-- sheet: 船舶图纸数量和品质概率
-- ------------------------------


local boat_quality_probability = {
	[1] = {
		['probability_green'] = 70,
		['probability_blue'] = 25,
		['probability_purple'] = 5,
	},
	[2] = {
		['probability_green'] = 60,
		['probability_blue'] = 30,
		['probability_purple'] = 10,
	},
	[3] = {
		['probability_green'] = 50,
		['probability_blue'] = 35,
		['probability_purple'] = 15,
	},
	[4] = {
		['probability_green'] = 40,
		['probability_blue'] = 40,
		['probability_purple'] = 20,
	},
	[5] = {
		['probability_green'] = 30,
		['probability_blue'] = 45,
		['probability_purple'] = 25,
	},
}

return boat_quality_probability