return 
{
[1] = {
    ['descr'] = '',
    ['id'] = 47,
    ['name'] = 'VIP 1',
    ['payValue'] = 10,
    ['res'] = '',
    ['scale'] = 35,
    ['subType'] = 2,
    ['value'] = '',
    },
[2] = {
    ['descr'] = '',
    ['id'] = 0,
    ['name'] = 'VIP 2',
    ['payValue'] = 50,
    ['res'] = '',
    ['scale'] = 100,
    ['subType'] = 4,
    ['value'] = T('委任次数+1,体力购买次数+1'),
    },
[3] = {
    ['descr'] = '',
    ['id'] = 45,
    ['name'] = 'VIP 3',
    ['payValue'] = 100,
    ['res'] = '',
    ['scale'] = 35,
    ['subType'] = 2,
    ['value'] = '',
    },
[4] = {
    ['descr'] = '',
    ['id'] = 0,
    ['name'] = 'VIP 4',
    ['payValue'] = 200,
    ['res'] = '',
    ['scale'] = 100,
    ['subType'] = 4,
    ['value'] = T('委任次数+2,体力购买次数+2'),
    },
[5] = {
    ['descr'] = '',
    ['id'] = 71,
    ['name'] = 'VIP 5',
    ['payValue'] = 500,
    ['res'] = '',
    ['scale'] = 23,
    ['subType'] = 2,
    ['value'] = '',
    },
[6] = {
    ['descr'] = '',
    ['id'] = 0,
    ['name'] = 'VIP 6',
    ['payValue'] = 1000,
    ['res'] = '',
    ['scale'] = 100,
    ['subType'] = 4,
    ['value'] = T('委任次数+3,体力购买次数+3'),
    },
[7] = {
    ['descr'] = '',
    ['id'] = 0,
    ['name'] = 'VIP 7',
    ['payValue'] = 2000,
    ['res'] = '',
    ['scale'] = 100,
    ['subType'] = 4,
    ['value'] = T('委任次数+4,体力购买次数+4'),
    },
[8] = {
    ['descr'] = '',
    ['id'] = 20,
    ['name'] = 'VIP 8',
    ['payValue'] = 5000,
    ['res'] = '',
    ['scale'] = 15,
    ['subType'] = 3,
    ['value'] = '',
    },
}