return 
{
[1] = {
    [1] = {
        ['descr'] = '',
        ['id'] = 0,
        ['kind'] = 1,
        ['res'] = '#common_icon_coin.png',
        ['scale'] = 100,
        ['subType'] = 1,
        ['value'] = 100000,
        },
    [2] = {
        ['descr'] = '',
        ['id'] = 4,
        ['res'] = '',
        ['scale'] = 35,
        ['spe_reward'] = '',
        ['subType'] = 2,
        ['value'] = '',
        },
    },
[2] = {
    [1] = {
        ['descr'] = '',
        ['id'] = 0,
        ['kind'] = 5,
        ['res'] = '#txt_common_icon_guild_contribution.png',
        ['scale'] = 100,
        ['subType'] = 8,
        ['value'] = 500,
        },
    [2] = {
        ['descr'] = '',
        ['id'] = 41,
        ['res'] = '',
        ['scale'] = 35,
        ['spe_reward'] = '',
        ['subType'] = 2,
        ['value'] = '',
        },
    },
[3] = {
    [1] = {
        ['descr'] = '',
        ['id'] = 0,
        ['kind'] = 6,
        ['res'] = '#common_icon_box.png',
        ['scale'] = 100,
        ['subType'] = 9,
        ['value'] = 2,
        },
    [2] = {
        ['descr'] = '',
        ['id'] = 0,
        ['res'] = 106,
        ['scale'] = 100,
        ['spe_reward'] = '',
        ['subType'] = 5,
        ['value'] = 10,
        },
    },
[4] = {
    [1] = {
        ['descr'] = '',
        ['id'] = 0,
        ['kind'] = 1,
        ['res'] = '#common_icon_coin.png',
        ['scale'] = 100,
        ['subType'] = 1,
        ['value'] = 100000,
        },
    [2] = {
        ['descr'] = '',
        ['id'] = 0,
        ['res'] = 167,
        ['scale'] = 100,
        ['spe_reward'] = '',
        ['subType'] = 5,
        ['value'] = 1,
        },
    },
[5] = {
    [1] = {
        ['descr'] = '',
        ['id'] = 0,
        ['kind'] = 5,
        ['res'] = '#txt_common_icon_guild_contribution.png',
        ['scale'] = 100,
        ['subType'] = 8,
        ['value'] = 500,
        },
    [2] = {
        ['descr'] = '',
        ['id'] = 0,
        ['res'] = 211,
        ['scale'] = 100,
        ['spe_reward'] = 'LOGIN_REWARD_5',
        ['subType'] = 5,
        ['value'] = 3,
        },
    },
[6] = {
    [1] = {
        ['descr'] = '',
        ['id'] = 0,
        ['kind'] = 2,
        ['res'] = '#common_icon_diamond.png',
        ['scale'] = 100,
        ['subType'] = 1,
        ['value'] = 50,
        },
    [2] = {
        ['descr'] = '',
        ['id'] = 0,
        ['res'] = 403,
        ['scale'] = 100,
        ['spe_reward'] = 'LOGIN_REWARD_6',
        ['subType'] = 7,
        ['value'] = 1,
        },
    },
[7] = {
    [1] = {
        ['descr'] = '',
        ['id'] = 0,
        ['kind'] = 3,
        ['res'] = '#common_icon_honour.png',
        ['scale'] = 100,
        ['subType'] = 10,
        ['value'] = 100,
        },
    [2] = {
        ['descr'] = '',
        ['id'] = 77,
        ['kind'] = 2,
        ['res'] = '',
        ['scale'] = 35,
        ['spe_reward'] = '',
        ['subType'] = 2,
        ['value'] = '',
        },
    },
}