-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役奖励.xls
-- sheet: reward_jyzy_94
-- ------------------------------


local reward_jyzy_94 = {
	['1'] = {
		['type'] = 'boat',
		['id'] = 7,
		['cnt'] = 1,
		['rate'] = 1,
		['memo'] = '',
		['role'] = 3,
	},
	['2'] = {
		['type'] = 'boat',
		['id'] = 8,
		['cnt'] = 1,
		['rate'] = 1,
		['memo'] = '',
		['role'] = 2,
	},
	['3'] = {
		['type'] = 'boat',
		['id'] = 28,
		['cnt'] = 1,
		['rate'] = 1,
		['memo'] = '',
		['role'] = 1,
	},
	['4'] = {
		['type'] = 'exp',
		['id'] = 221,
		['cnt'] = 50,
		['rate'] = 100,
		['memo'] = '',
		['role'] = 0,
	},
	['5'] = {
		['type'] = 'prosper',
		['id'] = 222,
		['cnt'] = 200,
		['rate'] = 100,
		['memo'] = '',
		['role'] = 0,
	},
}

return reward_jyzy_94