-- ------------------------------
-- desc: generated by xls2data.py
-- source: 市政工作奖励表.xlsx
-- sheet: 市政工作1星
-- ------------------------------


local reward_szgz_star1 = {
	['1'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 0,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'item',
		['id'] = 63,
		['cnt'] = 10,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_szgz_star1