-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役奖励.xls
-- sheet: reward_jyzy_102
-- ------------------------------


local reward_jyzy_102 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 162,
		['cnt'] = 3,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'exp',
		['id'] = 221,
		['cnt'] = 50,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'prosper',
		['id'] = 222,
		['cnt'] = 200,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_jyzy_102