-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役奖励.xls
-- sheet: reward_jyzy_202
-- ------------------------------


local reward_jyzy_202 = {
	['1'] = {
		['type'] = 'exp',
		['id'] = 221,
		['cnt'] = 1000,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'prosper',
		['id'] = 222,
		['cnt'] = 2000,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'reward',
		['id'] = 224,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
	},
}

return reward_jyzy_202