-- ------------------------------
-- desc: generated by xls2data.py
-- source: 公会据点奖励.xlsx
-- sheet: 大港口1级5名
-- ------------------------------


local item_info = {
	['1'] = {
		['type'] = 'contribute',
		['id'] = 0,
		['cnt'] = 375,
		['rate'] = 100,
		['memo'] = '',
	},
}

return item_info