-- ------------------------------
-- desc: generated by xls2data.py
-- source: 精英战役奖励.xls
-- sheet: reward_jyzy_183
-- ------------------------------


local reward_jyzy_183 = {
	['1'] = {
		['type'] = 'boat',
		['id'] = 14,
		['cnt'] = 1,
		['rate'] = 1,
		['memo'] = '',
		['role'] = 3,
	},
	['2'] = {
		['type'] = 'boat',
		['id'] = 29,
		['cnt'] = 1,
		['rate'] = 1,
		['memo'] = '',
		['role'] = 2,
	},
	['3'] = {
		['type'] = 'boat',
		['id'] = 30,
		['cnt'] = 1,
		['rate'] = 1,
		['memo'] = '',
		['role'] = 1,
	},
	['4'] = {
		['type'] = 'exp',
		['id'] = 221,
		['cnt'] = 400,
		['rate'] = 100,
		['memo'] = '',
		['role'] = 0,
	},
	['5'] = {
		['type'] = 'prosper',
		['id'] = 222,
		['cnt'] = 1500,
		['rate'] = 100,
		['memo'] = '',
		['role'] = 0,
	},
}

return reward_jyzy_183