/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qtz_game_utils_sdk_QSDKObserver */

#ifndef _Included_com_qtz_game_utils_sdk_QSDKObserver
#define _Included_com_qtz_game_utils_sdk_QSDKObserver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qtz_game_utils_sdk_QSDKObserver
 * Method:    onLoginNotify
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qtz_game_utils_sdk_QSDKObserver_onLoginNotify
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_qtz_game_utils_sdk_QSDKObserver
 * Method:    onPayNotify
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qtz_game_utils_sdk_QSDKObserver_onPayNotify
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_qtz_game_utils_sdk_QSDKObserver
 * Method:    onLogoutNotify
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_qtz_game_utils_sdk_QSDKObserver_onLogoutNotify
  (JNIEnv *, jobject, jint);


#ifdef __cplusplus
}
#endif
#endif
