/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "QSDK.h"
/* Header for class com_qtz_utils_sdk_QTZJavaSDK */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qtz_utils_sdk_QTZJavaSDK
 * Method:    onNotifyNative
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qtz_utils_sdk_QTZJavaSDK_onNotifyNative
  (JNIEnv *env, jobject jc, jint ev, jint code, jstring msg)
{
    const char *cmsg = env->GetStringUTFChars(msg, 0); 
    std::string ret = cmsg;
    env->ReleaseStringUTFChars(msg, cmsg);
    QSDK::sharedQSDK()->commonHandle(ev, code, ret.c_str());
}

#ifdef __cplusplus
}
#endif
