-- ------------------------------
-- desc: generated by out_sound_excel.py
-- source: 多语言音乐音效配置总表.xls
-- sheet: 语音对白
-- ------------------------------


local voice_info = {
    ['VOICE_BOAT_1000'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BOAT_1001'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BOAT_1002'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BOAT_1003'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BOAT_1005'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1000'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1001'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1002'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1003'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1004'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1005'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1006'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1007'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1008'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1009'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1010'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1012'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1013'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1015'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1016'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1017'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1018'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1019'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1020'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1021'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1022'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1025'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1028'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1031'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1003'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1004'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1010'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1011'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1012'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1013'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1014'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1015'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1016'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1017'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1018'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1019'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1020'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1021'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1022'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1023'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1024'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1025'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1026'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1027'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1028'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1029'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1030'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1031'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1032'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1033'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1034'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1035'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1036'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1037'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1038'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1039'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1040'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1041'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1082'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_STORY_1015'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_STORY_1017'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_STORY_1018'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_STORY_1021'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_STORY_1022'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_STORY_1023'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1000'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1001'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1002'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1003'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1004'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1005'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1006'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1007'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1008'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1009'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1010'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1011'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1012'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1013'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1014'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1015'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1016'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1017'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1018'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1019'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1020'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1021'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1022'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1023'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1024'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1025'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1026'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1027'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1028'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1029'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1030'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1031'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1032'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1033'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1034'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1035'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1036'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1037'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1038'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1039'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1040'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1041'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1000'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1001'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1002'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1003'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1004'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1005'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1006'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1007'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_PRESTIGE_1000'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_1'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_2'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_3'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_4'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_5'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_6'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_7'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_1'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_2'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_3'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_4'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_5'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_6'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_7'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_1'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_2'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_3'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_4'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_5'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_6'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_7'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_1'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_2'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_3'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_4'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_5'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_1'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_2'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_3'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_4'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_5'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_6'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_7'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_8'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_9'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_10'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_11'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_12'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_13'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_14'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_15'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_AMMAND_1'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_LOLI_1'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_LOLI_2'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_LOLI_3'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_LOLI_4'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_16'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_17'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_18'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_MOORE_1'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_MOORE_2'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_8'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_8'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_8'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_6'] = {
        ['res'] = '',
        ['time'] = 0,
    },
    ['VOICE_AMMAND_2'] = {
        ['res'] = '',
        ['time'] = 0,
    },
}
return voice_info