-- ------------------------------
-- desc: generated by out_sound_excel.py
-- source: 多语言音乐音效配置总表.xls
-- sheet: 语音对白
-- ------------------------------


local voice_info = {
    ['VOICE_BOAT_1000'] = {
        ['res'] = 'voice/appoint_select_male',
        ['time'] = 0,
    },
    ['VOICE_BOAT_1001'] = {
        ['res'] = 'voice/appoint_confirm_male',
        ['time'] = 0,
    },
    ['VOICE_BOAT_1002'] = {
        ['res'] = 'voice/appoint_select_female',
        ['time'] = 0,
    },
    ['VOICE_BOAT_1003'] = {
        ['res'] = 'voice/appoint_confirm_female',
        ['time'] = 0,
    },
    ['VOICE_BOAT_1005'] = {
        ['res'] = 'voice/boat_backpack',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1000'] = {
        ['res'] = 'voice/market_welcome',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1001'] = {
        ['res'] = 'voice/market_full_male',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1002'] = {
        ['res'] = 'voice/market_empty_male',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1003'] = {
        ['res'] = 'voice/market_full_female',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1004'] = {
        ['res'] = 'voice/market_empty_female',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1005'] = {
        ['res'] = 'voice/hotel_welcome',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1006'] = {
        ['res'] = 'voice/hotel_cruit_male',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1007'] = {
        ['res'] = 'voice/hotel_train_male',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1008'] = {
        ['res'] = 'voice/hotel_cruit_female',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1009'] = {
        ['res'] = 'voice/hotel_train_female',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1010'] = {
        ['res'] = 'voice/port_battle_male',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1012'] = {
        ['res'] = 'voice/port_arena_male',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1013'] = {
        ['res'] = 'voice/port_battle_female',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1015'] = {
        ['res'] = 'voice/port_arena_female',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1016'] = {
        ['res'] = 'voice/port_relogin_m',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1017'] = {
        ['res'] = 'voice/port_relogin_w',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1018'] = {
        ['res'] = 'voice/port_marketquotations_m',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1019'] = {
        ['res'] = 'voice/port_marketquotations_w',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1020'] = {
        ['res'] = 'voice/port_appoint_m',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1021'] = {
        ['res'] = 'voice/port_appoint_w',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1022'] = {
        ['res'] = 'voice/port_reward',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1025'] = {
        ['res'] = 'voice/town_enter',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1028'] = {
        ['res'] = 'voice/port_sail',
        ['time'] = 0,
    },
    ['VOICE_PLOT_1031'] = {
        ['res'] = 'voice/hotel_reward',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1003'] = {
        ['res'] = 'voice/battle_4',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1004'] = {
        ['res'] = 'voice/battle_5',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1010'] = {
        ['res'] = 'voice/battle_11',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1011'] = {
        ['res'] = 'voice/battle_12',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1012'] = {
        ['res'] = 'voice/battle_13',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1013'] = {
        ['res'] = 'voice/battle_14',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1014'] = {
        ['res'] = 'voice/battle_15',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1015'] = {
        ['res'] = 'voice/battle_16',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1016'] = {
        ['res'] = 'voice/battle_17',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1017'] = {
        ['res'] = 'voice/battle_18',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1018'] = {
        ['res'] = 'voice/battle_19',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1019'] = {
        ['res'] = 'voice/battle_20',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1020'] = {
        ['res'] = 'voice/battle_21',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1021'] = {
        ['res'] = 'voice/battle_22',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1022'] = {
        ['res'] = 'voice/battle_23',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1023'] = {
        ['res'] = 'voice/battle_24',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1024'] = {
        ['res'] = 'voice/battle_25',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1025'] = {
        ['res'] = 'voice/battle_26',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1026'] = {
        ['res'] = 'voice/battle_27',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1027'] = {
        ['res'] = 'voice/battle_28',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1028'] = {
        ['res'] = 'voice/battle_29',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1029'] = {
        ['res'] = 'voice/battle_30',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1030'] = {
        ['res'] = 'voice/battle_31',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1031'] = {
        ['res'] = 'voice/battle_32',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1032'] = {
        ['res'] = 'voice/battle_33',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1033'] = {
        ['res'] = 'voice/battle_34',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1034'] = {
        ['res'] = 'voice/battle_35',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1035'] = {
        ['res'] = 'voice/battle_36',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1036'] = {
        ['res'] = 'voice/battle_37',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1037'] = {
        ['res'] = 'voice/battle_38',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1038'] = {
        ['res'] = 'voice/battle_39',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1039'] = {
        ['res'] = 'voice/battle_40',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1040'] = {
        ['res'] = 'voice/battle_41',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1041'] = {
        ['res'] = 'voice/battle_42',
        ['time'] = 0,
    },
    ['VOICE_BATTLE_1082'] = {
        ['res'] = 'voice/novice_battle_15',
        ['time'] = 0,
    },
    ['VOICE_STORY_1015'] = {
        ['res'] = 'voice/mission_16',
        ['time'] = 0,
    },
    ['VOICE_STORY_1017'] = {
        ['res'] = 'voice/mission_18',
        ['time'] = 0,
    },
    ['VOICE_STORY_1018'] = {
        ['res'] = 'voice/mission_19',
        ['time'] = 0,
    },
    ['VOICE_STORY_1021'] = {
        ['res'] = 'voice/mission_22',
        ['time'] = 0,
    },
    ['VOICE_STORY_1022'] = {
        ['res'] = 'voice/mission_23',
        ['time'] = 0,
    },
    ['VOICE_STORY_1023'] = {
        ['res'] = 'voice/mission_24',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1000'] = {
        ['res'] = 'voice/ex_stop_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1001'] = {
        ['res'] = 'voice/ex_manual_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1002'] = {
        ['res'] = 'voice/ex_sailing1_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1003'] = {
        ['res'] = 'voice/ex_sailing2_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1004'] = {
        ['res'] = 'voice/ex_no_food_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1005'] = {
        ['res'] = 'voice/battle_18',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1006'] = {
        ['res'] = 'voice/ex_no_ops_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1007'] = {
        ['res'] = 'voice/ex_storm1_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1008'] = {
        ['res'] = 'voice/ex_storm2_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1009'] = {
        ['res'] = 'voice/ex_storm3_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1010'] = {
        ['res'] = 'voice/ex_fog1_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1011'] = {
        ['res'] = 'voice/ex_fog2_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1012'] = {
        ['res'] = 'voice/ex_fog3_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1013'] = {
        ['res'] = 'voice/battle_25',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1014'] = {
        ['res'] = 'voice/ex_headwind_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1015'] = {
        ['res'] = 'voice/ex_box1_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1016'] = {
        ['res'] = 'voice/ex_rock1_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1017'] = {
        ['res'] = 'voice/ex_box2_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1018'] = {
        ['res'] = 'voice/ex_rock2_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1019'] = {
        ['res'] = 'voice/battle_11',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1020'] = {
        ['res'] = 'voice/ex_stop_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1021'] = {
        ['res'] = 'voice/ex_manual_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1022'] = {
        ['res'] = 'voice/ex_sailing1_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1023'] = {
        ['res'] = 'voice/ex_sailing2_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1024'] = {
        ['res'] = 'voice/ex_no_food_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1025'] = {
        ['res'] = 'voice/battle_33',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1026'] = {
        ['res'] = 'voice/ex_no_ops_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1027'] = {
        ['res'] = 'voice/ex_storm1_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1028'] = {
        ['res'] = 'voice/ex_storm2_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1029'] = {
        ['res'] = 'voice/ex_storm3_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1030'] = {
        ['res'] = 'voice/ex_fog1_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1031'] = {
        ['res'] = 'voice/ex_fog2_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1032'] = {
        ['res'] = 'voice/ex_fog3_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1033'] = {
        ['res'] = 'voice/battle_42',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1034'] = {
        ['res'] = 'voice/ex_headwind_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1035'] = {
        ['res'] = 'voice/ex_box1_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1036'] = {
        ['res'] = 'voice/ex_rock1_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1037'] = {
        ['res'] = 'voice/ex_box2_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1038'] = {
        ['res'] = 'voice/ex_rock2_f',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1039'] = {
        ['res'] = 'voice/battle_26',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1040'] = {
        ['res'] = 'voice/ex_sailing1_m',
        ['time'] = 0,
    },
    ['VOICE_EXPLORE_1041'] = {
        ['res'] = 'voice/ex_sailing1_f',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1000'] = {
        ['res'] = 'voice/voice_switch_1',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1001'] = {
        ['res'] = 'voice/voice_switch_2',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1002'] = {
        ['res'] = 'voice/voice_switch_3',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1003'] = {
        ['res'] = 'voice/voice_switch_4',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1004'] = {
        ['res'] = 'voice/voice_switch_5',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1005'] = {
        ['res'] = 'voice/voice_switch_6',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1006'] = {
        ['res'] = 'voice/voice_switch_7',
        ['time'] = 0,
    },
    ['VOICE_SWITCH_1007'] = {
        ['res'] = 'voice/voice_switch_8',
        ['time'] = 0,
    },
    ['VOICE_PRESTIGE_1000'] = {
        ['res'] = 'voice/voice_cheer',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_1'] = {
        ['res'] = 'voice/voice_role_navy_1',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_2'] = {
        ['res'] = 'voice/voice_role_navy_2',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_3'] = {
        ['res'] = 'voice/voice_role_navy_3',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_4'] = {
        ['res'] = 'voice/voice_role_navy_4',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_5'] = {
        ['res'] = 'voice/voice_role_navy_5',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_6'] = {
        ['res'] = 'voice/voice_role_navy_6',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_7'] = {
        ['res'] = 'voice/voice_role_navy_7',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_1'] = {
        ['res'] = 'voice/voice_role_adv_1',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_2'] = {
        ['res'] = 'voice/voice_role_adv_2',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_3'] = {
        ['res'] = 'voice/voice_role_adv_3',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_4'] = {
        ['res'] = 'voice/voice_role_adv_4',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_5'] = {
        ['res'] = 'voice/voice_role_adv_5',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_6'] = {
        ['res'] = 'voice/voice_role_adv_6',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_7'] = {
        ['res'] = 'voice/voice_role_adv_7',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_1'] = {
        ['res'] = 'voice/voice_role_pirate_1',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_2'] = {
        ['res'] = 'voice/voice_role_pirate_2',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_3'] = {
        ['res'] = 'voice/voice_role_pirate_3',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_4'] = {
        ['res'] = 'voice/voice_role_pirate_4',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_5'] = {
        ['res'] = 'voice/voice_role_pirate_5',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_6'] = {
        ['res'] = 'voice/voice_role_pirate_6',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_7'] = {
        ['res'] = 'voice/voice_role_pirate_7',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_1'] = {
        ['res'] = 'voice/voice_npc_dk_1',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_2'] = {
        ['res'] = 'voice/voice_npc_dk_2',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_3'] = {
        ['res'] = 'voice/voice_npc_dk_3',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_4'] = {
        ['res'] = 'voice/voice_npc_dk_4',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_5'] = {
        ['res'] = 'voice/voice_npc_dk_5',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_1'] = {
        ['res'] = 'voice/voice_npc_adviser_1',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_2'] = {
        ['res'] = 'voice/voice_npc_adviser_2',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_3'] = {
        ['res'] = 'voice/voice_npc_adviser_3',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_4'] = {
        ['res'] = 'voice/voice_npc_adviser_4',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_5'] = {
        ['res'] = 'voice/voice_npc_adviser_5',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_6'] = {
        ['res'] = 'voice/voice_npc_adviser_6',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_7'] = {
        ['res'] = 'voice/voice_npc_adviser_7',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_8'] = {
        ['res'] = 'voice/voice_npc_adviser_8',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_9'] = {
        ['res'] = 'voice/voice_npc_adviser_9',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_10'] = {
        ['res'] = 'voice/voice_npc_adviser_10',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_11'] = {
        ['res'] = 'voice/voice_npc_adviser_11',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_12'] = {
        ['res'] = 'voice/voice_npc_adviser_12',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_13'] = {
        ['res'] = 'voice/voice_npc_adviser_13',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_14'] = {
        ['res'] = 'voice/voice_npc_adviser_14',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_15'] = {
        ['res'] = 'voice/voice_npc_adviser_15',
        ['time'] = 0,
    },
    ['VOICE_AMMAND_1'] = {
        ['res'] = 'voice/voice_ammand_1',
        ['time'] = 0,
    },
    ['VOICE_LOLI_1'] = {
        ['res'] = 'voice/voice_loli_1',
        ['time'] = 0,
    },
    ['VOICE_LOLI_2'] = {
        ['res'] = 'voice/voice_loli_2',
        ['time'] = 0,
    },
    ['VOICE_LOLI_3'] = {
        ['res'] = 'voice/voice_loli_3',
        ['time'] = 0,
    },
    ['VOICE_LOLI_4'] = {
        ['res'] = 'voice/voice_loli_4',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_16'] = {
        ['res'] = 'voice/voice_npc_adviser_16',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_17'] = {
        ['res'] = 'voice/voice_npc_adviser_17',
        ['time'] = 0,
    },
    ['VOICE_NPC_ADVISER_18'] = {
        ['res'] = 'voice/voice_npc_adviser_18',
        ['time'] = 0,
    },
    ['VOICE_MOORE_1'] = {
        ['res'] = 'voice/voice_moore_1',
        ['time'] = 0,
    },
    ['VOICE_MOORE_2'] = {
        ['res'] = 'voice/voice_moore_2',
        ['time'] = 0,
    },
    ['VOICE_ROLE_NAVY_8'] = {
        ['res'] = 'voice/voice_role_navy_8',
        ['time'] = 0,
    },
    ['VOICE_ROLE_ADV_8'] = {
        ['res'] = 'voice/voice_role_adv_8',
        ['time'] = 0,
    },
    ['VOICE_ROLE_PIRATE_8'] = {
        ['res'] = 'voice/voice_role_pirate_8',
        ['time'] = 0,
    },
    ['VOICE_NPC_DK_6'] = {
        ['res'] = 'voice/voice_npc_dk_6',
        ['time'] = 0,
    },
    ['VOICE_AMMAND_2'] = {
        ['res'] = 'voice/voice_ammand_2',
        ['time'] = 0,
    },
}
return voice_info