-- ------------------------------
-- desc: generated by xls2data.py
-- source: 新活动开启提示.xlsx
-- sheet: 下一解锁活动文本
-- ------------------------------


local activity_next_txt = {
	[1] = {
		['activity_next_txt'] = T('商会讨伐'),
		['activity_next_lv_txt'] = T('（20级）'),
	},
	[2] = {
		['activity_next_txt'] = T('商会战争'),
		['activity_next_lv_txt'] = T('（25级）'),
	},
	[3] = {
		['activity_next_txt'] = T('深渊乱斗'),
		['activity_next_lv_txt'] = T('（20级）'),
	},
	[4] = {
		['activity_next_txt'] = T('成长基金'),
		['activity_next_lv_txt'] = T('（21级）'),
	},
	[5] = {
		['activity_next_txt'] = T('每日礼包'),
		['activity_next_lv_txt'] = T('（21级）'),
	},
	[6] = {
		['activity_next_txt'] = T('黑市商人'),
		['activity_next_lv_txt'] = T('（22级）'),
	},
	[7] = {
		['activity_next_txt'] = T('海神挑战'),
		['activity_next_lv_txt'] = T('（23级）'),
	},
	[8] = {
		['activity_next_txt'] = T('海上运镖'),
		['activity_next_lv_txt'] = T('（24级）'),
	},
	[9] = {
		['activity_next_txt'] = T('海怪突袭'),
		['activity_next_lv_txt'] = T('（24级）'),
	},
	[10] = {
		['activity_next_txt'] = T('港口争夺'),
		['activity_next_lv_txt'] = T('（25级）'),
	},
	[11] = {
		['activity_next_txt'] = T('传奇航海士活动'),
		['activity_next_lv_txt'] = T('（30级）'),
	},
	[12] = {
		['activity_next_txt'] = T('市政官试炼'),
		['activity_next_lv_txt'] = T('（20级）'),
	},
	[13] = {
		['activity_next_txt'] = T('请期待新活动内容'),
		['activity_next_lv_txt'] = '',
	},
}

return activity_next_txt