-- ------------------------------
-- desc: generated by xls2data.py
-- source: 传奇航海士活动配置表.xlsx
-- sheet: Sheet1
-- ------------------------------


local awake_huodong_config = {
	[1] = {
		['sailor'] = 63,
		['sailor_info'] = T('强力辅助，全体回血，全面解控。续航、反杀神级航海士。'),
		['sailor_type'] = 'txt_legend_adv.png',
	},
	[2] = {
		['sailor'] = 67,
		['sailor_info'] = T('硬派雇佣军，半血加防、近战回血，战场上生存能力无人能及。'),
		['sailor_type'] = 'txt_legend_pirate.png',
	},
	[3] = {
		['sailor'] = 83,
		['sailor_info'] = T('爆裂输出，全体提高命中，自身超远射程并破防伤害的神级海军。'),
		['sailor_type'] = 'txt_legend_navy.png',
	},
	[4] = {
		['sailor'] = 60,
		['sailor_info'] = T('以多制少，召唤强力自爆幽灵船，对范围敌人造成伤害。'),
		['sailor_type'] = 'txt_legend_adv.png',
	},
	[5] = {
		['sailor'] = 72,
		['sailor_info'] = T('强力压制，持续伤害，禁疗效果让敌人毫无办法。'),
		['sailor_type'] = 'txt_legend_pirate.png',
	},
	[6] = {
		['sailor'] = 111,
		['sailor_info'] = T('战场收割女王，给予敌军血量最低目标强力一击，满级技能破防。'),
		['sailor_type'] = 'txt_legend_navy.png',
	},
	[7] = {
		['sailor'] = 78,
		['sailor_info'] = T('神级救援，高频率救治友军血量最低目标，并清除不良状态。'),
		['sailor_type'] = 'txt_legend_adv.png',
	},
}

return awake_huodong_config