-- ------------------------------
-- desc: generated by xls2data.py
-- source: 成长基金.xlsx
-- sheet: 成长基金
-- ------------------------------


local fund_info = {
	[1] = {
		['level'] = 20,
		['gold'] = 2000,
	},
	[2] = {
		['level'] = 25,
		['gold'] = 1500,
	},
	[3] = {
		['level'] = 30,
		['gold'] = 1500,
	},
	[4] = {
		['level'] = 35,
		['gold'] = 1500,
	},
	[5] = {
		['level'] = 40,
		['gold'] = 1500,
	},
	[6] = {
		['level'] = 45,
		['gold'] = 2000,
	},
}

return fund_info