-- ------------------------------
-- desc: generated by xls2data.py
-- source: 加载界面预开放config.xls
-- sheet: 声望提升界面
-- ------------------------------


local loading_info = {
	[1] = {
		['title'] = T('今日活动'),
		['name'] = T('深渊乱斗'),
		['icon'] = 'common_icon_battle.png',
		['time'] = '20:30-21:00',
		['reward'] = {"common_item_crystal.png","common_icon_coin.png"},
	},
	[2] = {
		['title'] = T('今日活动'),
		['name'] = T('市政官试炼'),
		['icon'] = 'common_icon_invest.png',
		['time'] = '20:30-21:00',
		['reward'] = {"common_icon_coin.png","common_icon_exp.png"},
	},
	[3] = {
		['title'] = T('今日活动'),
		['name'] = T('港口争夺'),
		['icon'] = 'common_icon_portfight.png',
		['time'] = '20:30-21:00',
		['reward'] = {"common_icon_diamond.png","common_icon_equip.png"},
	},
	[4] = {
		['title'] = T('今日活动'),
		['name'] = T('深渊乱斗'),
		['icon'] = 'common_icon_battle.png',
		['time'] = '20:30-21:00',
		['reward'] = {"common_item_crystal.png","common_icon_coin.png"},
	},
	[5] = {
		['title'] = T('今日活动'),
		['name'] = T('市政官试炼'),
		['icon'] = 'common_icon_invest.png',
		['time'] = '20:30-21:00',
		['reward'] = {"common_icon_coin.png","common_icon_exp.png"},
	},
	[6] = {
		['title'] = T('今日活动'),
		['name'] = T('商会战'),
		['icon'] = 'common_icon_guild.png',
		['time'] = '20:30-21:00',
		['reward'] = {"txt_common_icon_guild_contribution.png","common_item_keepsake_a.png"},
	},
}

return loading_info