-- ------------------------------
-- desc: generated by xls2data.py
-- source: 名舰名仕奖励表.xls
-- sheet: mjms_activity_reward
-- ------------------------------


local mjms_activity_reward = {
	['1'] = {
		['type'] = 'item',
		['id'] = 83,
		['cnt'] = 1,
		['rate'] = 1,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'item',
		['id'] = 84,
		['cnt'] = 1,
		['rate'] = 1,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'item',
		['id'] = 85,
		['cnt'] = 1,
		['rate'] = 1,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'item',
		['id'] = 106,
		['cnt'] = 2,
		['rate'] = 1,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'item',
		['id'] = 106,
		['cnt'] = 3,
		['rate'] = 1,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'item',
		['id'] = 106,
		['cnt'] = 4,
		['rate'] = 1,
		['memo'] = '',
	},
}

return mjms_activity_reward