-- ------------------------------
-- desc: generated by xls2data.py
-- source: mjms_reward.xls
-- sheet: 名舰名仕奖励
-- ------------------------------


local mjms_reward = {
	[1] = {
		['type'] = 1,
		['reward_txt1'] = T('1.升星C级航海士1次'),
		['reward_txt2'] = '',
		['mjms_reward'] = 1,
	},
	[2] = {
		['type'] = 1,
		['reward_txt1'] = T('2.升星B级航海士1次'),
		['reward_txt2'] = '',
		['mjms_reward'] = 2,
	},
	[3] = {
		['type'] = 1,
		['reward_txt1'] = T('3.升星A级航海士1次'),
		['reward_txt2'] = '',
		['mjms_reward'] = 3,
	},
	[4] = {
		['type'] = 2,
		['reward_txt1'] = T('1.消耗锤子'),
		['reward_txt2'] = '%s/%s',
		['mjms_reward'] = 4,
	},
	[5] = {
		['type'] = 2,
		['reward_txt1'] = T('2.消耗锤子'),
		['reward_txt2'] = '%s/%s',
		['mjms_reward'] = 5,
	},
	[6] = {
		['type'] = 2,
		['reward_txt1'] = T('3.消耗锤子'),
		['reward_txt2'] = '%s/%s',
		['mjms_reward'] = 6,
	},
}

return mjms_reward