-- ------------------------------
-- desc: generated by xls2data.py
-- source: 首冲累计充值.xlsx
-- sheet: 累充排序
-- ------------------------------


local recharge_order = {
	[1] = {
		['order'] = { [1]={["item_type"]=15 ,["id"]=2,["pos"] = 1 , ["item_level"] = 1},[2]={["item_type"]=15 ,["id"]=237,["pos"] = 2 , ["item_level"] = 0},[3]={["item_type"]=15 ,["id"]=106,["pos"] = 3 , ["item_level"] = 0}},
	},
	[2] = {
		['order'] = { [1]={["item_type"]=15 ,["id"]=2,["pos"] = 1 , ["item_level"] = 1},[2]={["item_type"]=15 ,["id"]=237,["pos"] = 2 , ["item_level"] = 0},[3]={["item_type"]=15 ,["id"]=175,["pos"] = 3 , ["item_level"] = 0}},
	},
	[3] = {
		['order'] = { [1]={["item_type"]=10 ,["id"]=503,["pos"] = 1 , ["item_level"] = 2},[2]={["item_type"]=15 ,["id"]=167,["pos"] = 2 , ["item_level"] = 0},[3]={["item_type"]=15 ,["id"]=2,["pos"] = 3 , ["item_level"] = 1},[4]={["item_type"]=10 ,["id"]=603,["pos"] = 1 , ["item_level"] = 2},[5]={["item_type"]=10 ,["id"]=803,["pos"] = 1 , ["item_level"] = 2}},
	},
	[4] = {
		['order'] = { [1]={["item_type"]=10 ,["id"]=504,["pos"] = 1 , ["item_level"] = 2},[2]={["item_type"]=15 ,["id"]=167,["pos"] = 2 , ["item_level"] = 0},[3]={["item_type"]=15 ,["id"]=2,["pos"] = 3 , ["item_level"] = 1},[4]={["item_type"]=10 ,["id"]=604,["pos"] = 1 , ["item_level"] = 2},[5]={["item_type"]=10 ,["id"]=804,["pos"] = 1 , ["item_level"] = 2}},
	},
	[5] = {
		['order'] = { [1]={["item_type"]=15 ,["id"]=168,["pos"] = 1 , ["item_level"] = 2},[2]={["item_type"]=15 ,["id"]=2,["pos"] = 2 , ["item_level"] = 1},[3]={["item_type"]=15 ,["id"]=194,["pos"] = 3 , ["item_level"] = 2}},
	},
	[6] = {
		['order'] = { [1]={["item_type"]=10 ,["id"]=505,["pos"] = 1 , ["item_level"] = 2},[2]={["item_type"]=15 ,["id"]=2,["pos"] = 2 , ["item_level"] = 1},[3]={["item_type"]=15 ,["id"]=50,["pos"] = 3 , ["item_level"] = 2},[4]={["item_type"]=10 ,["id"]=605,["pos"] = 1 , ["item_level"] = 2},[5]={["item_type"]=10 ,["id"]=805,["pos"] = 1 , ["item_level"] = 2}},
	},
	[7] = {
		['order'] = { [1]={["item_type"]=15 ,["id"]=168,["pos"] = 1 , ["item_level"] = 2},[2]={["item_type"]=15 ,["id"]=2,["pos"] = 2 , ["item_level"] = 1},[3]={["item_type"]=15 ,["id"]=195,["pos"] = 3 , ["item_level"] = 2}},
	},
	[8] = {
		['order'] = { [1]={["item_type"]=15 ,["id"]=195,["pos"] = 1 , ["item_level"] = 2},[2]={["item_type"]=15 ,["id"]=2,["pos"] = 2 , ["item_level"] = 1},[3]={["item_type"]=15 ,["id"]=50,["pos"] = 3 , ["item_level"] = 2}},
	},
	[9] = {
		['order'] = { [1]={["item_type"]=12 ,["id"]=106,["pos"] = 1 , ["item_level"] = 1},[2]={["item_type"]=10 ,["id"]=511,["pos"] = 2 , ["item_level"] = 2},[3]={["item_type"]=15 ,["id"]=2,["pos"] = 3 , ["item_level"] = 1},[4]={["item_type"]=10 ,["id"]=611,["pos"] = 2 , ["item_level"] = 2},[5]={["item_type"]=10 ,["id"]=811,["pos"] = 2 , ["item_level"] = 2}},
	},
	[10] = {
		['order'] = { [1]={["item_type"]=15 ,["id"]=169,["pos"] = 1 , ["item_level"] = 2},[2]={["item_type"]=15 ,["id"]=2,["pos"] = 2 , ["item_level"] = 1},[3]={["item_type"]=15 ,["id"]=196,["pos"] = 3 , ["item_level"] = 2}},
	},
	[11] = {
		['order'] = { [1]={["item_type"]=15 ,["id"]=169,["pos"] = 1 , ["item_level"] = 2},[2]={["item_type"]=15 ,["id"]=2,["pos"] = 2 , ["item_level"] = 1},[3]={["item_type"]=15 ,["id"]=196,["pos"] = 3 , ["item_level"] = 2}},
	},
	[12] = {
		['order'] = { [1]={["item_type"]=15 ,["id"]=169,["pos"] = 1 , ["item_level"] = 2},[2]={["item_type"]=15 ,["id"]=2,["pos"] = 2 , ["item_level"] = 1},[3]={["item_type"]=15 ,["id"]=196,["pos"] = 3 , ["item_level"] = 2}},
	},
	[13] = {
		['order'] = { [1]={["item_type"]=12 ,["id"]=59,["pos"] = 1 , ["item_level"] = 1},[2]={["item_type"]=15 ,["id"]=2,["pos"] = 2 , ["item_level"] = 1},[3]={["item_type"]=15 ,["id"]=196,["pos"] = 3 , ["item_level"] = 2}},
	},
}

return recharge_order