-- ------------------------------
-- desc: generated by xls2data.py
-- source: 首冲累计充值.xlsx
-- sheet: 首冲累计充值
-- ------------------------------


local recharge = {
	[1] = {
		['amount'] = 0,
	},
	[2] = {
		['amount'] = 10,
	},
	[3] = {
		['amount'] = 50,
	},
	[4] = {
		['amount'] = 180,
	},
	[5] = {
		['amount'] = 500,
	},
	[6] = {
		['amount'] = 1000,
	},
	[7] = {
		['amount'] = 2000,
	},
	[8] = {
		['amount'] = 3000,
	},
	[9] = {
		['amount'] = 5000,
	},
	[10] = {
		['amount'] = 10000,
	},
	[11] = {
		['amount'] = 15000,
	},
	[12] = {
		['amount'] = 20000,
	},
	[13] = {
		['amount'] = 30000,
	},
	[14] = {
		['amount'] = 50000,
	},
}

return recharge