-- ------------------------------
-- desc: generated by xls2data.py
-- source: config.xls
-- sheet: 活跃度奖励
-- ------------------------------


local syllabus_mission_reward = {
	[1] = {
	},
	[2] = {
	},
	[3] = {
	},
	[4] = {
	},
	[5] = {
	},
	[6] = {
	},
}

return syllabus_mission_reward