-- ------------------------------
-- desc: generated by xls2data.py
-- source: boat_config.xls
-- sheet: 船舶舰队相关
-- ------------------------------


local boat_fleet_config = {
	[1] = {
		['name'] = T('轻木帆船'),
		['upload_baowu_type'] = {2, 1, 2, 3},
		['can_reform'] = 0,
	},
	[2] = {
		['name'] = T('轻型三角帆船'),
		['upload_baowu_type'] = {3, 4, 3, 2},
		['can_reform'] = 0,
	},
	[3] = {
		['name'] = T('三桅卡拉维尔'),
		['upload_baowu_type'] = {1, 3, 4, 2},
		['can_reform'] = 0,
	},
	[5] = {
		['name'] = T('汉萨排桨商船'),
		['upload_baowu_type'] = {5, 4, 5, 1},
		['can_reform'] = 0,
	},
	[6] = {
		['name'] = T('武装帆船'),
		['upload_baowu_type'] = {3, 4, 3, 2},
		['can_reform'] = 0,
	},
	[7] = {
		['name'] = T('阿拉伯桨帆船'),
		['upload_baowu_type'] = {5, 4, 5, 1},
		['can_reform'] = 1,
	},
	[8] = {
		['name'] = T('中国绿眉毛'),
		['upload_baowu_type'] = {3, 4, 3, 2},
		['can_reform'] = 1,
	},
	[9] = {
		['name'] = T('安宅船'),
		['upload_baowu_type'] = {4, 5, 4, 2},
		['can_reform'] = 1,
	},
	[10] = {
		['name'] = T('加莱船'),
		['upload_baowu_type'] = {5, 4, 5, 1},
		['can_reform'] = 1,
	},
	[11] = {
		['name'] = T('中国大广船'),
		['upload_baowu_type'] = {3, 4, 3, 2},
		['can_reform'] = 1,
	},
	[12] = {
		['name'] = T('龟甲船'),
		['upload_baowu_type'] = {4, 5, 4, 2},
		['can_reform'] = 1,
	},
	[13] = {
		['name'] = T('西班牙大帆船'),
		['upload_baowu_type'] = {1, 3, 4, 2},
		['can_reform'] = 1,
	},
	[14] = {
		['name'] = T('威尼斯炮舰'),
		['upload_baowu_type'] = {5, 4, 5, 1},
		['can_reform'] = 1,
	},
	[15] = {
		['name'] = T('中国大福船'),
		['upload_baowu_type'] = {4, 5, 4, 2},
		['can_reform'] = 1,
	},
	[16] = {
		['name'] = T('西班牙无敌炮舰'),
		['upload_baowu_type'] = {3, 4, 3, 2},
		['can_reform'] = 1,
	},
	[17] = {
		['name'] = T('黑珍珠'),
		['upload_baowu_type'] = {1, 3, 4, 2},
		['can_reform'] = 1,
	},
	[18] = {
		['name'] = T('金雌鹿'),
		['upload_baowu_type'] = {4, 5, 4, 2},
		['can_reform'] = 1,
	},
	[19] = {
		['name'] = T('安妮女王复仇'),
		['upload_baowu_type'] = {4, 5, 4, 2},
		['can_reform'] = 1,
	},
	[20] = {
		['name'] = T('飞翔的荷兰人'),
		['upload_baowu_type'] = {5, 4, 5, 1},
		['can_reform'] = 1,
	},
	[21] = {
		['name'] = T('皇家海军胜利号'),
		['upload_baowu_type'] = {3, 4, 3, 2},
		['can_reform'] = 1,
	},
	[22] = {
		['name'] = T('三保宝船'),
		['upload_baowu_type'] = {2, 1, 2, 3},
		['can_reform'] = 1,
	},
	[23] = {
		['name'] = T('双桅横帆船'),
		['upload_baowu_type'] = {4, 5, 4, 2},
		['can_reform'] = 0,
	},
	[24] = {
		['name'] = T('加利斯桨帆船'),
		['upload_baowu_type'] = {2, 1, 2, 3},
		['can_reform'] = 0,
	},
	[25] = {
		['name'] = T('柯克船'),
		['upload_baowu_type'] = {2, 1, 2, 3},
		['can_reform'] = 1,
	},
	[26] = {
		['name'] = T('迅捷突击帆船'),
		['upload_baowu_type'] = {1, 3, 4, 2},
		['can_reform'] = 0,
	},
	[27] = {
		['name'] = T('马尼拉大帆船'),
		['upload_baowu_type'] = {2, 1, 2, 3},
		['can_reform'] = 1,
	},
	[28] = {
		['name'] = T('巡洋重炮船'),
		['upload_baowu_type'] = {1, 3, 4, 2},
		['can_reform'] = 1,
	},
	[29] = {
		['name'] = T('斯库纳帆船'),
		['upload_baowu_type'] = {1, 3, 4, 2},
		['can_reform'] = 1,
	},
	[30] = {
		['name'] = T('高桅横帆船'),
		['upload_baowu_type'] = {2, 1, 2, 3},
		['can_reform'] = 1,
	},
	[31] = {
		['name'] = T('费留特船'),
		['upload_baowu_type'] = {1, 3, 4, 2},
		['can_reform'] = 1,
	},
	[32] = {
		['name'] = T('皇家战列舰'),
		['upload_baowu_type'] = {3, 4, 3, 2},
		['can_reform'] = 1,
	},
}

return boat_fleet_config