-- ------------------------------
-- desc: generated by xls2data.py
-- source: boat_config.xls
-- sheet: 船舶改造
-- ------------------------------


local fleet_transform_probability = {
	[1] = {
		['transform_attribute_num'] = 0,
		['battle_attribute_up'] = 0,
		['attribute_up_btn'] = '',
	},
	[2] = {
		['transform_attribute_num'] = 1,
		['battle_attribute_up'] = 0,
		['attribute_up_btn'] = '',
	},
	[3] = {
		['transform_attribute_num'] = 2,
		['battle_attribute_up'] = 0,
		['attribute_up_btn'] = '',
	},
	[4] = {
		['transform_attribute_num'] = 3,
		['battle_attribute_up'] = 0,
		['attribute_up_btn'] = '',
	},
	[5] = {
		['transform_attribute_num'] = 4,
		['battle_attribute_up'] = 0,
		['attribute_up_btn'] = '',
	},
	[6] = {
		['transform_attribute_num'] = 5,
		['battle_attribute_up'] = 5,
		['attribute_up_btn'] = 'fleet_remake_green.png',
	},
	[7] = {
		['transform_attribute_num'] = 6,
		['battle_attribute_up'] = 5,
		['attribute_up_btn'] = 'fleet_remake_green.png',
	},
	[8] = {
		['transform_attribute_num'] = 7,
		['battle_attribute_up'] = 5,
		['attribute_up_btn'] = 'fleet_remake_green.png',
	},
	[9] = {
		['transform_attribute_num'] = 8,
		['battle_attribute_up'] = 5,
		['attribute_up_btn'] = 'fleet_remake_green.png',
	},
	[10] = {
		['transform_attribute_num'] = 9,
		['battle_attribute_up'] = 5,
		['attribute_up_btn'] = 'fleet_remake_green.png',
	},
	[11] = {
		['transform_attribute_num'] = 10,
		['battle_attribute_up'] = 10,
		['attribute_up_btn'] = 'fleet_remake_blue.png',
	},
	[12] = {
		['transform_attribute_num'] = 11,
		['battle_attribute_up'] = 10,
		['attribute_up_btn'] = 'fleet_remake_blue.png',
	},
	[13] = {
		['transform_attribute_num'] = 12,
		['battle_attribute_up'] = 10,
		['attribute_up_btn'] = 'fleet_remake_blue.png',
	},
	[14] = {
		['transform_attribute_num'] = 13,
		['battle_attribute_up'] = 10,
		['attribute_up_btn'] = 'fleet_remake_blue.png',
	},
	[15] = {
		['transform_attribute_num'] = 14,
		['battle_attribute_up'] = 10,
		['attribute_up_btn'] = 'fleet_remake_blue.png',
	},
	[16] = {
		['transform_attribute_num'] = 15,
		['battle_attribute_up'] = 15,
		['attribute_up_btn'] = 'fleet_remake_purple.png',
	},
	[17] = {
		['transform_attribute_num'] = 16,
		['battle_attribute_up'] = 15,
		['attribute_up_btn'] = 'fleet_remake_purple.png',
	},
	[18] = {
		['transform_attribute_num'] = 17,
		['battle_attribute_up'] = 15,
		['attribute_up_btn'] = 'fleet_remake_purple.png',
	},
	[19] = {
		['transform_attribute_num'] = 18,
		['battle_attribute_up'] = 15,
		['attribute_up_btn'] = 'fleet_remake_purple.png',
	},
	[20] = {
		['transform_attribute_num'] = 19,
		['battle_attribute_up'] = 15,
		['attribute_up_btn'] = 'fleet_remake_purple.png',
	},
	[21] = {
		['transform_attribute_num'] = 20,
		['battle_attribute_up'] = 20,
		['attribute_up_btn'] = 'fleet_remake_orange.png',
	},
}

return fleet_transform_probability