-- ------------------------------
-- desc: generated by xls2data.py
-- source: special_lueduo.xls
-- sheet: plot
-- ------------------------------


local plot_special_lueduo_info = {
	[1] = {
		['plot'] = 'text_display',
		['param'] = {{T("偶遇运输珍贵钻石的舰队……")}},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1280,640,0}},
	},
	[3] = {
		['plot'] = 'cameraScale',
		['param'] = {{1280,640,0},0.6,1.5},
	},
	[4] = {
		['plot'] = 'cameraMoveAndScale',
		['param'] = {{1280,640,0},{768,640,1.5,1.0},{{1280,640,0},1.0,1.5}},
	},
}

return plot_special_lueduo_info