-- ------------------------------
-- desc: generated by xls2data.py
-- source: 戴肯.xls
-- sheet: plot
-- ------------------------------


local plot_1201010_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{2380,640,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("没想会遇到你，新仇旧恨一齐报了吧！。"),ship_id=1},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {72,T("戴肯"),2,T("救救我们，我们从德雷克那魔鬼那边逃了出来。"),ship_id=2},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("既然到了这一步，生死都可以置之度外了，求一场酣畅淋漓的战斗！")},
	},
}

return plot_1201010_info