-- ------------------------------
-- desc: generated by xls2data.py
-- source: 1500001.xls
-- sheet: plot
-- ------------------------------


local plot_1500001_info = {
	[1] = {
		['plot'] = 'text_display',
		['param'] = {{T("船长，我们已经抵达藏宝图标记位置！发现沉船宝藏！")}},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{2432,704,2}},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("这鬼天气！船只受损了，宝藏沉船被漩涡封印着，快点结束战斗！"),ship_id=2},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{1984,600,2}},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("是守护宝藏的“无惧者”，击败他们就能解除宝藏漩涡！"),ship_id=2},
	},
	[6] = {
		['plot'] = 'text_display',
		['param'] = {{T("“无惧者”已经被击败，宝藏封印解除！")}},
	},
}

return plot_1500001_info