-- ------------------------------
-- desc: generated by xls2data.py
-- source: 172.xls
-- sheet: plot
-- ------------------------------


local plot_1000172_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("德雷克，放弃吧，你逃不掉了"),ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1500,440,1}},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {63,T("德雷克副手"),2,T("可恶，无敌战舰竟然没摧毁你们"),ship_id=3},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{2100,640,1}},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {63,T("德雷克副手"),2,T("不知死活，我们的忍耐可是有限度的，要逃命趁早！"),ship_id=2},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {60,T("德雷克"),2,T("解决他们！"),ship_id=2},
	},
	[7] = {
		['plot'] = 'camera',
		['param'] = {{2100,640,1}},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {60,T("德雷克"),2,T("不妙……连我的副手都被轰成这样……先撤"),ship_id=2},
	},
}

return plot_1000172_info