-- ------------------------------
-- desc: generated by xls2data.py
-- source: 黑胡子.xls
-- sheet: plot
-- ------------------------------


local plot_1201007_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{2000,640,1}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {67,T("黑胡子"),2,T("瞧瞧，可怜的英国海军追到这了。"),ship_id=2},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("黑胡子！今日一定要拿下你的项上人头。"),ship_id=1},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {67,T("黑胡子"),2,T("只有娘娘腔才会浪费口舌，像你们这样的虫子，在加勒比海我能打一百个！瞄准！！"),ship_id=2},
	},
	[5] = {
		['plot'] = 'text_display',
		['param'] = {{T("英军梅纳德不幸死亡")}},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {67,T("黑胡子"),2,T("真是讽刺，想不到我的胸腔里竟然还有滚烫的鲜血，哈哈哈哈……"),ship_id=2},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {53,T("英军梅纳德"),1,T("我还是……失败了吗……"),ship_id=3},
	},
}

return plot_1201007_info