-- ------------------------------
-- desc: generated by xls2data.py
-- source: 131.xls
-- sheet: plot
-- ------------------------------


local plot_1000131_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{2450,640,0.2}},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{2450,320,0.2}},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{2450,960,0.2}},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{2450,440,0.2}},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{2450,840,0.2}},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("可恶，让他们逃了。"),ship_id=1},
	},
	[7] = {
		['plot'] = 'camera',
		['param'] = {{1400,640,2}},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("发现缉拿目标走私贩头目的船了！必须集火一艘，别给他们喘息的机会！"),ship_id=1},
	},
}

return plot_1000131_info