-- ------------------------------
-- desc: generated by xls2data.py
-- source: 151.xls
-- sheet: plot
-- ------------------------------


local plot_1000151_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("击倒卡宴防守军的首领，不要让他们有机会去报信。")},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {31,T("防守军首领"),2,T("居然敢到巴洛沙缪大人的地盘撒野，见识见识我们的厉害。"),ship_id=8},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("糟了，让他们逃了……")},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{0,300,0.5}},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{0,600,0.5}},
	},
	[6] = {
		['plot'] = 'camera',
		['param'] = {{0,900,0.5}},
	},
	[7] = {
		['plot'] = 'camera',
		['param'] = {{1600,640,1}},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("好，这个港口已经是我们的囊中之物了！")},
	},
}

return plot_1000151_info