-- ------------------------------
-- desc: generated by xls2data.py
-- source: 21.xls
-- sheet: plot
-- ------------------------------


local plot_1000021_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("港湾内的海盗正在肆无忌惮的饮酒作乐呢！"),ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{500,800,0},{1200,900,1},},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("趁他们毫无戒备，快速逐个击破！"),ship_id=1},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{1600,850,1}},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗"),2,T("嗨呀出大事啦！火药库爆炸啦！一定有敌人！回击他们！"),ship_id=5},
	},
}

return plot_1000021_info