-- ------------------------------
-- desc: generated by xls2data.py
-- source: 12_2.xls
-- sheet: plot
-- ------------------------------


local plot_1002012_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),1,T("哼，轻敌的蠢货，居然只派了一群杂鱼对付我们，点击$(c:COLOR_GREEN)【加速】$(c:COLOR_WHITE)，先冲进敌阵给他们点厉害尝尝。"),ship_id=1,10,false,"VOICE_NPC_ADVISER_16"},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),1,T("使用$(c:COLOR_GREEN)【摇杆】$(c:COLOR_WHITE)控制方向，点击右下角$(c:COLOR_GREEN)【加速】$(c:COLOR_WHITE)，先冲进敌阵给他们点厉害尝尝。"),ship_id=1,6,false,"VOICE_NPC_ADVISER_1"},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),1,T("这艘船配备齐全，点击使用$(c:COLOR_GREEN)各项技能$(c:COLOR_WHITE)，清理掉碍事的家伙。"),ship_id=1,6,false,"VOICE_NPC_ADVISER_17"},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("一艘破船就想攻击我们？没睡醒么？小的们，给我上！碾碎这群头脑发热的渣滓！"),ship_id=14,10,false,"VOICE_MOORE_1"},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),1,T("接下来使用$(c:COLOR_GREEN)终极技能$(c:COLOR_WHITE)，让那个小瞧我们的混蛋接受制裁！"),ship_id=1,7,false,"VOICE_NPC_ADVISER_18"},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("你们不要得意，老大会替我报仇的！"),5,false,"VOICE_MOORE_2"},
	},
}

return plot_1002012_info