-- ------------------------------
-- desc: generated by xls2data.py
-- source: 191.xls
-- sheet: plot
-- ------------------------------


local plot_1000191_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {35,T("敌军首领"),2,T("兄弟们，赐予我力量……."),ship_id=8},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("趁他们人员不齐，赶紧消灭海盗首领,要注意先击溃掉敌军的防守船。")},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("海盗首领血量下降到一定程度，会吸取防守船来获得力量")},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {35,T("敌军首领"),2,T("我们来决一死战吧！"),ship_id=21},
	},
}

return plot_1000191_info