-- ------------------------------
-- desc: generated by xls2data.py
-- source: 111_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100111_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),2,T("看，我们马上就到马尼拉了。")},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1312,660,2}},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),2,T("奇怪，本来这片海域到处都是郑芝龙的手下才对呀。")},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("海上飘来烧焦的木板，情况不对！全员警惕、保持阵型。")},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{400,640,2}},
	},
}

return plot_1100111_info