-- ------------------------------
-- desc: generated by xls2data.py
-- source: 173_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100173_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("德雷克，你已无路可逃，投降吧！"),ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1539,801,1}},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {60,T("德雷克"),2,T("抱歉，我没听清，你们想要投降？"),ship_id=2},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {60,T("德雷克"),2,T("无所谓，反正今天你们也要葬身于此。"),ship_id=2},
	},
}

return plot_1100173_info