-- ------------------------------
-- desc: generated by xls2data.py
-- source: 162.xls
-- sheet: plot
-- ------------------------------


local plot_1000162_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("可恶，又是奥斯曼海盗！全员警惕，准备作战！"),ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{250,639,1}},
	},
	[3] = {
		['plot'] = 'cameraScale',
		['param'] = {{250,639},0.5, 2},
	},
	[4] = {
		['plot'] = 'text_display',
		['param'] = {{T("北端左翼战线还呈胶着状态，南端右翼战线也开始展开")}},
	},
	[5] = {
		['plot'] = 'text_display',
		['param'] = {{T("奥斯曼海军利用熟悉地形的优势，成功迂回到同盟军后方展开突袭……")}},
	},
}

return plot_1000162_info