-- ------------------------------
-- desc: generated by xls2data.py
-- source: 212_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100212_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("可恶的兵痞，你们已经无路可逃了！快投降吧！")},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1600,640,1}},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {13,T("兵痞首领"),2,T("这次那位大人不在，兄弟们，干掉他！"),ship_id=2},
	},
}

return plot_1100212_info