-- ------------------------------
-- desc: generated by xls2data.py
-- source: 134_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100134_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{2300,640,1}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {93,T("汪直"),2,T("你们真是阴魂不散呢，如此苦苦相逼……"),ship_id=2},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {93,T("汪直"),2,T("让你们看看我手下浪人的厉害！来人啊，把他们切碎了丢海里喂鱼去！"),ship_id=2},
	},
}

return plot_1100134_info