-- ------------------------------
-- desc: generated by xls2data.py
-- source: 21_3.xls
-- sheet: plot
-- ------------------------------


local plot_1003021_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("来来来，喝！我告诉你们，这单至少赚了这个——数！"),ship_id=5},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {6,T("摩尔海盗"),2,T("跟着阿芒德大人，吃穿不愁！"),ship_id=4},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{800,850,1}},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {72,T("戴肯"),1,T("礁石？哈哈，我们来让他们醒醒酒！"),ship_id=1},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {72,T("戴肯"),1,T("船长，请使用$(c:COLOR_GREEN)【冲撞】$(c:COLOR_WHITE)将敌人撞上礁石！"),ship_id=1},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("嗨呀火药库爆炸啦！兄弟们！后面有敌人，回击他们！"),ship_id=5},
	},
}

return plot_1003021_info