-- ------------------------------
-- desc: generated by xls2data.py
-- source: 201.xls
-- sheet: plot
-- ------------------------------


local plot_1000201_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {45,T("俞红袖"),2,T("是大明水师！被红旗军围困此地，请解救他们！")},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("拦住追击队伍，别让他们击沉这艘大明水军的船舰")},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),2,T("休要惊动敌方首领，小心行事。")},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {35,T("敌军首领"),2,T("这次，先放你们一马，，，"),ship_id=21},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{2200,600,2}},
	},
	[6] = {
		['plot'] = 'camera',
		['param'] = {{0,600,1}},
	},
}

return plot_1000201_info