-- ------------------------------
-- desc: generated by xls2data.py
-- source: 171_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100171_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("德雷克！！！"),ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1500,440,1}},
	},
	[3] = {
		['plot'] = 'cameraScale',
		['param'] = {{1500,440},1.2,1},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {60,T("德雷克"),2,T("我又回来了，这次，我带了无敌战舰送给你们，哈哈哈哈"),ship_id=7},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {60,T("德雷克"),2,T("玩得开心，我先撤了"),ship_id=7},
	},
}

return plot_1100171_info