-- ------------------------------
-- desc: generated by xls2data.py
-- source: 121.xls
-- sheet: plot
-- ------------------------------


local plot_1000121_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1300,600,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {13,T("大明水军"),2,T("誓死捍卫家园！冲啊，消灭这些入侵者。")},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{900,600,2}},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("由于长期的海禁政策，这些海军装备老旧实力不济。弓箭难以与火炮抗衡，必须尽快支援他们。")},
	},
}

return plot_1000121_info