-- ------------------------------
-- desc: generated by xls2data.py
-- source: 42_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100042_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{494,600,0},{1674,636,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("目标商船正遭遇攻击，解救他们！"),ship_id=1},
	},
}

return plot_1100042_info