-- ------------------------------
-- desc: generated by xls2data.py
-- source: 163_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100163_info = {
	[1] = {
		['plot'] = 'text_display',
		['param'] = {{T("与巴巴罗萨之战终于来临……")}},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1500,640,1}},
	},
	[3] = {
		['plot'] = 'cameraScale',
		['param'] = {{1500,640},2, 2},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {59,T("巴巴罗萨"),2,T("决战！荣耀属于奥斯曼！地中海终将成为这些贪婪者的墓地！"),ship_id=2},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{1280,640,1}},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {59,T("巴巴罗萨"),2,T("来吧！我要亲手埋葬你！"),ship_id=2},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {59,T("巴巴罗萨"),2,T("对敌人来说，我是恶魔！但对我的人民来说，我是英雄！而这正是我无悔的追求……"),ship_id=2},
	},
}

return plot_1100163_info