-- ------------------------------
-- desc: generated by xls2data.py
-- source: 192_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100192_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("敌军旗舰在血量越低时，部分属性会增强，尽量先击倒其中一艘旗舰！")},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1600,640,0.5}},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {95,T("信众"),2,T("斩杀所有异教徒！！"),ship_id=17},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {95,T("信众"),2,T("你以为就这么些人吗。。。"),ship_id=19},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{200,640,0.5}},
	},
}

return plot_1100192_info