-- ------------------------------
-- desc: generated by xls2data.py
-- source: 巴巴罗萨.xls
-- sheet: plot
-- ------------------------------


local plot_1201004_info = {
	[1] = {
		['plot'] = 'text_display',
		['param'] = {{T("与巴巴罗萨之战终于来临……")}},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{2100,640,1}},
	},
	[3] = {
		['plot'] = 'cameraScale',
		['param'] = {{2100,640},2, 2},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {59,T("巴巴罗萨"),2,T("不知天高地厚的虫子！居然妄想挑战我！世上最伟大的海盗王！巴巴罗萨！"),ship_id=2},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {59,T("巴巴罗萨"),2,T("我！巴巴罗萨！我的一生！无怨无悔！"),ship_id=2},
	},
}

return plot_1201004_info