-- ------------------------------
-- desc: generated by xls2data.py
-- source: 2000001.xls
-- sheet: plot
-- ------------------------------


local plot_2000001_info = {
}

return plot_2000001_info