-- ------------------------------
-- desc: generated by xls2data.py
-- source: 181.xls
-- sheet: plot
-- ------------------------------


local plot_1000181_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("你确定那里真的是贩奴船吗？")},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {31,T("北方商队首领"),2,T("可恶的海盗，快！分散逃离这片海域。"),ship_id=2},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("糟了，有商船逃掉了……")},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{750,500,1}},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{0,600,1}},
	},
	[6] = {
		['plot'] = 'camera',
		['param'] = {{0,1100,0.5}},
	},
	[7] = {
		['plot'] = 'camera',
		['param'] = {{2000,640,1}},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("这战力，并不是贩奴船！而是普通的商船！")},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {92,T("马铃薯"),2,T("当然了，快干掉他们！。"),ship_id=7},
	},
	[10] = {
		['plot'] = 'camera',
		['param'] = {{1600,640,1}},
	},
	[11] = {
		['plot'] = 'camera',
		['param'] = {{0,100,0.5}},
	},
	[12] = {
		['plot'] = 'camera',
		['param'] = {{1500,750,0.5}},
	},
	[13] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("糟了！马铃薯被击沉了！")},
	},
}

return plot_1000181_info