-- ------------------------------
-- desc: generated by xls2data.py
-- source: 23.xls
-- sheet: plot
-- ------------------------------


local plot_1000023_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("终于攻入摩尔海盗的老巢！拉比斯会不会就在这里？"),2,fail,ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1250,1100,2}},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {72,T("戴肯"),1,T("很有可能，这些犬牙交错的岛礁不仅可以掩护伏击，分散海盗阵型逐个击破。"),4,fail,ship_id=1},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{460,600,1}},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("敌人舰队装备精良，让我们利用岛礁障碍，埋伏攻击$(c:COLOR_GREEN)【海盗首领】$(c:COLOR_WHITE)"),5,fail,ship_id=1},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {72,T("戴肯"),1,T("现在，跟着$(c:COLOR_GREEN)绿色箭头$(c:COLOR_WHITE)指引方向前行。"),5,fail,ship_id=1},
	},
	[7] = {
		['plot'] = 'guide',
		['param'] = {40,{131,56}},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("到达目的地，停船！白色区域为我方射程，躲在掩体后等待海盗进入$(c:COLOR_GREEN)船只射程$(c:COLOR_WHITE)，守株待兔！"),5,fail,ship_id=1},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("哈哈！敌人已经进入$(c:COLOR_GREEN)船只射程$(c:COLOR_WHITE)，点击释放技能攻击敌人！"),5,fail,ship_id=1},
	},
	[10] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),1,T("有战斗？也不知道阿芒德那个蠢货又招惹了谁，怪不得今天守备如此松懈。管他呢，终于不用再呆在又湿又臭的牢房里了。先去威尼斯躲躲，等风头过了再回里斯本。"),ship_id=5},
	},
}

return plot_1000023_info