-- ------------------------------
-- desc: generated by xls2data.py
-- source: 21_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100021_jy_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("港湾内的海盗正在肆无忌惮的饮酒作乐呢！"),ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{500,800,0},{1200,900,1},},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("趁他们毫无戒备，快速逐个击破！"),ship_id=1},
	},
}

return plot_1100021_jy_info