-- ------------------------------
-- desc: generated by xls2data.py
-- source: 22_3.xls
-- sheet: plot
-- ------------------------------


local plot_1003022_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{850,850,1}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("海盗正在追击商船！我们要想办法阻止他们！"),ship_id=1},
	},
	[3] = {
		['plot'] = 'cameraScale',
		['param'] = {{500,850},2, 1},
	},
	[4] = {
		['plot'] = 'cameraScale',
		['param'] = {{500,850},0.8, 0},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("哈！礁石，不过这次的礁石位置可不大好！"),ship_id=1},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {72,T("戴肯"),2,T("别急船长，$(c:COLOR_GREEN)【钩索】$(c:COLOR_WHITE)可以把敌人拉过来撞上礁石噢，试试看吧！"),ship_id=1},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("起风了！天助我也，全速追击！")},
	},
	[8] = {
		['plot'] = 'camera',
		['param'] = {{950,800,1}},
	},
	[9] = {
		['plot'] = 'cameraScale',
		['param'] = {{950,800},2, 1},
	},
	[10] = {
		['plot'] = 'cameraScale',
		['param'] = {{950,800},0.8, 0},
	},
	[11] = {
		['plot'] = 'dialog',
		['param'] = {17,T("商船船长"),2,T("太棒了！勇敢的船长，给您留下$(c:COLOR_GREEN)【酒桶】$(c:COLOR_WHITE)，请随意使用吧！"),ship_id=5},
	},
	[12] = {
		['plot'] = 'dialog',
		['param'] = {72,T("戴肯"),2,T("船长，得到$(c:COLOR_GREEN)【酒桶】$(c:COLOR_WHITE)可以为我们恢复血量，请一定要记住！"),ship_id=1},
	},
	[13] = {
		['plot'] = 'dialog',
		['param'] = {17,T("商船船长"),2,T("是摩尔海盗！这些该死的海盗！这趟算是白跑了！"),ship_id=5},
	},
	[14] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("得到$(c:COLOR_GREEN)【酒桶】$(c:COLOR_WHITE)，船只耐久恢复！"),ship_id=1},
	},
}

return plot_1003022_info