-- ------------------------------
-- desc: generated by xls2data.py
-- source: 郑和.xls
-- sheet: plot
-- ------------------------------


local plot_1201009_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{2180,640,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {83,T("郑和"),2,T("“剑指西山面朝天，最是难逢一强敌”，咦有人，小友可想与我一战？"),ship_id=2},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("当然，最幸运的事情莫过于和高手过招。"),ship_id=1},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {83,T("郑和"),2,T("自西洋之行后，我便鲜少在碰到对手，这次你可要让我尽兴啊！"),ship_id=2},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("当然，如您所愿。")},
	},
}

return plot_1201009_info