-- ------------------------------
-- desc: generated by xls2data.py
-- source: 李舜臣.xls
-- sheet: plot
-- ------------------------------


local plot_1201001_info = {
	[1] = {
		['plot'] = 'text_display',
		['param'] = {{T("对手是在鸣梁海战中大胜的将领，李舜臣……")}},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1664,640,1}},
	},
	[3] = {
		['plot'] = 'cameraScale',
		['param'] = {{1664,640},2, 2},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("敌人数量不多，此战我们赢定了！")},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {82,T("李舜臣"),2,T("哈哈！年轻人！战争并不只是军力之争！"),ship_id=2},
	},
	[6] = {
		['plot'] = 'camera',
		['param'] = {{1216,640,1}},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("被卷入漩涡会严重减速！糟了！")},
	},
	[8] = {
		['plot'] = 'camera',
		['param'] = {{1664,640,1}},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {82,T("李舜臣"),2,T("时机已到！全军！最大火力轰碎他们！"),ship_id=2},
	},
}

return plot_1201001_info