-- ------------------------------
-- desc: generated by xls2data.py
-- source: 153_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100153_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("巴沙洛缪·罗伯茨，现在投降还来得及。")},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {62,T("巴沙洛缪·罗伯茨"),2,T("哈哈，口出狂言！给我上，谁摘了他的脑袋，重重有赏！"),ship_id=16},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{2000,600,0.5}},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {62,T("巴沙洛缪·罗伯茨"),2,T("既然你不识好歹，等我来亲自收拾你"),ship_id=16},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("糟了，不小心击沉命运号了…….")},
	},
}

return plot_1100153_info