-- ------------------------------
-- desc: generated by xls2data.py
-- source: 威廉.丹比尔.xls
-- sheet: plot
-- ------------------------------


local plot_1201002_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1728,512,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("海上的雾太大了，瞭望手只能确认部分船只的位置，威廉一直在暗处增强船只，快点找到并击败他！"),ship_id=1},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {62,T("威廉丹比尔"),2,T("哈哈哈哈，补给完成，现在该我来抓你了！"),ship_id=2},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {62,T("威廉丹比尔"),2,T("挺能干的嘛！居然找到这里！但我早已设下埋伏！"),ship_id=2},
	},
}

return plot_1201002_info