-- ------------------------------
-- desc: generated by xls2data.py
-- source: 133_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100133_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1600,640,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {93,T("汪直"),2,T("该死！丰臣大人拒绝我们进入大阪，这些阴魂不散的家伙追上来了。"),ship_id=2},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {93,T("汪直"),2,T("只有背水一战了，让这些可恶的家伙葬身海底！"),ship_id=2},
	},
}

return plot_1100133_info