-- ------------------------------
-- desc: generated by xls2data.py
-- source: 21_1.xls
-- sheet: plot
-- ------------------------------


local plot_1001021_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{900,850,1},{700,850,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("来来来，喝！我告诉你们，这单至少赚了这个——数！"),ship_id=4},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {6,T("摩尔海盗"),2,T("回家咯！跟着阿芒德大人，吃穿不愁！"),ship_id=3},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {72,T("戴肯"),1,T("醉醺醺的海盗想要跑的！船长，快使用$(c:COLOR_GREEN)【贯通射击】$(c:COLOR_WHITE)晕掉落单的海盗。"),ship_id=1},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{800,850,1}},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("嗨呀我头好晕啊！兄弟们！后面有敌人，回击他们！"),ship_id=5},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {6,T("摩尔海盗"),2,T("那不行嗨！大难临头各显神通！我们快逃！"),ship_id=5},
	},
	[8] = {
		['plot'] = 'camera',
		['param'] = {{1400,850,1}},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {6,T("摩尔海盗"),2,T("哎呦！撞到礁石啦！兄弟们我们回头和他们拼了！"),ship_id=5},
	},
	[10] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("哈哈哈哈你看看你！"),ship_id=5},
	},
}

return plot_1001021_info