-- ------------------------------
-- desc: generated by xls2data.py
-- source: 132.xls
-- sheet: plot
-- ------------------------------


local plot_1000132_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1400,640,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {3,T("武装冲锋船"),2,T("别天真的以为，我们就只有这点能力。"),ship_id=3},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {3,T("武装冲锋船"),2,T("没点本事,我们怎么能在东亚光明正大走私？"),ship_id=3},
	},
}

return plot_1000132_info