-- ------------------------------
-- desc: generated by xls2data.py
-- source: 999.xls
-- sheet: plot
-- ------------------------------


local plot_1209999_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{996,640,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("不自量力的小鬼！居然想要挑战伟大的摩尔海盗！"),ship_id=2},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {5,T("汉娜"),2,T("这群海盗还真嚣张，船长，请先使用$(c:COLOR_GREEN)摇杆$(c:COLOR_WHITE)控制船只前往指定位置。"),ship_id=1,2,true},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {5,T("汉娜"),2,T("成功抵达目标点，前方出现海盗斥候，点击释放技能$(c:COLOR_GREEN)【贯通射击】$(c:COLOR_WHITE)可对单名敌人造成大量伤害并击晕敌人。"),ship_id=1,2,true},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {5,T("汉娜"),2,T("前方出现大量敌人，点击释放技能$(c:COLOR_GREEN)【链弹】$(c:COLOR_WHITE)可同时对弹道上多名敌人造成伤害并造成敌人减速。"),ship_id=1,2,true},
	},
	[6] = {
		['plot'] = 'camera',
		['param'] = {{996,640,2}},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("没想到你还挺能干的嘛！兄弟们！做好准备！"),ship_id=5},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {5,T("汉娜"),2,T("士气高涨！船长，请前往目标点与摩尔海盗首领展开决战！"),ship_id=1},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {5,T("汉娜"),2,T("伏军火力凶猛，点击释放技能$(c:COLOR_GREEN)【分身】$(c:COLOR_WHITE)可以召唤增援舰并解除敌人对船只的控制。"),ship_id=1,2,true},
	},
	[10] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("哈哈哈哈垂死挣扎！"),ship_id=5},
	},
	[11] = {
		['plot'] = 'dialog',
		['param'] = {5,T("汉娜"),2,T("船长莫急，接下来点击释放技能$(c:COLOR_GREEN)【船体修补】$(c:COLOR_WHITE)可为所有友军船只恢复耐久。"),ship_id=1,2,true},
	},
	[12] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("这什么啊！发...发生啥事？！"),ship_id=5},
	},
	[13] = {
		['plot'] = 'dialog',
		['param'] = {5,T("汉娜"),2,T("船长，干得漂亮，教程到此结束，请自由战斗击溃敌军！"),ship_id=1,2,true},
	},
	[14] = {
		['plot'] = 'camera',
		['param'] = {{100,640,2}},
	},
	[15] = {
		['plot'] = 'dialog',
		['param'] = {31,T("摩尔海盗首领"),2,T("这招埋伏真是屡试不爽啊！兄弟们！干掉他！"),ship_id=5},
	},
}

return plot_1209999_info