-- ------------------------------
-- desc: generated by xls2data.py
-- source: 23_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100023_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("终于攻入摩尔海盗的老巢！"),2,fail,ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{600,600,0},{1800,600,1},},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("这些犬牙交错的岛礁不仅可以掩护伏击，也可以分散船阵！"),4,fail,ship_id=1},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{1800,600,0},{600,600,1},},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("敌人舰队装备精良，让我们利用岛礁障碍，分散海盗阵形逐个击破，再集中火力攻击【海盗首领】"),5,fail,ship_id=1},
	},
}

return plot_1100023_info