-- ------------------------------
-- desc: generated by xls2data.py
-- source: solo_boss.xls
-- sheet: plot
-- ------------------------------


local plot_solo_boss_info = {
}

return plot_solo_boss_info