-- ------------------------------
-- desc: generated by xls2data.py
-- source: 102_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100102_info = {
	[1] = {
		['plot'] = 'text_display',
		['param'] = {{T("反抗军从亚齐酒馆……旁的猪圈找到了一名间谍，让他潜入马六甲城打探军情。")}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {71,T("反抗军首领"),2,T("张保仔，希望我信任你是正确的。"),ship_id=7},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {70,T("张保仔"),2,T("放心吧船长，我很高兴你又找到了我，不会让你们失望的。"),ship_id=8},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {70,T("张保仔"),2,T("他们以为我仅是个酗酒的普通商人罢了。"),ship_id=8},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{475,1028,2}},
	},
	[6] = {
		['plot'] = 'text_display',
		['param'] = {{T("张保仔成功潜入马六甲城待命。")}},
	},
	[7] = {
		['plot'] = 'text_display',
		['param'] = {{T("反抗军首领的船被击沉了，先撤退吧！")}},
	},
	[8] = {
		['plot'] = 'text_display',
		['param'] = {{T("与炮塔保持距离，击沉所有的巡逻舰，直到张保仔潜入马六甲。")}},
	},
}

return plot_1100102_info