-- ------------------------------
-- desc: generated by xls2data.py
-- source: 13_3.xls
-- sheet: plot
-- ------------------------------


local plot_1003013_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {27,T("摩尔海盗精英"),2,T("老大，救命啊！"),ship_id=6,2,false},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),1,T("你就算喊破喉咙也不会有人来救你！"),ship_id=1},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {100,T("阿芒德"),2,T("多谢你帮我教训这些不成器的手下，废物没有存在的价值。"),ship_id=7,5,false},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),1,T("该死，居然遇到了海盗头目，我们赶紧撤！"),ship_id=1},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("这是……梦中的那个家伙？！不好，拉比斯，我们撤！"),ship_id=1},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {100,T("阿芒德"),2,T("（没想到会在这里遇到飞翔的荷兰人，如果能把它献给巴巴罗萨大人，他一定会很开心的）哼，既然来了，就不要走了。"),ship_id=7,9,false},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("把拉比斯还回来！可恶，船，怎么不听使唤了！不好，它正在消失！"),ship_id=1,8,false,"VOICE_ROLE_PIRATE_8"},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {72,T("神秘人"),2,T("抓紧绳子，上来。"),3,false,"VOICE_NPC_DK_6"},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {55,T("拉比斯"),1,T("放开我！该死的海盗！"),ship_id=1,6,false,"VOICE_NPC_ADVISER_15"},
	},
	[10] = {
		['plot'] = 'dialog',
		['param'] = {100,T("阿芒德"),2,T("小美人，乖乖跟老子走吧，哈哈哈！"),ship_id=7,7,false,"VOICE_AMMAND_2"},
	},
	[11] = {
		['plot'] = 'dialog',
		['param'] = {72,T("范·德·戴肯"),2,T("年轻人，我是范.德.戴肯，看样子你需要一些帮助。"),7,false,"VOICE_NPC_DK_1"},
	},
	[12] = {
		['plot'] = 'add_sprite',
		['param'] = {"ui/story/story_1.jpg",{0,0},1,0.8,1,0,1,"RGB565"},
	},
	[13] = {
		['plot'] = 'remove_sprite',
		['param'] = {999,0,0.5,0},
	},
	[14] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("请你帮帮我，帮我救回拉比斯，我愿意付出任何代价！"),ship_id=14,5,false,"VOICE_ROLE_PIRATE_4"},
	},
	[15] = {
		['plot'] = 'dialog',
		['param'] = {72,T("范·德·戴肯"),2,T("我是一名学者，昨天在港口见到飞翔的荷兰人，便迫不及待地跑到船上进行研究，没想到你们两个小家伙居然直接驾驶这艘船出海作战，而且还输了……"),8,false,"VOICE_NPC_DK_1"},
	},
	[16] = {
		['plot'] = 'dialog',
		['param'] = {72,T("范·德·戴肯"),2,T("呵呵，代价……欢迎来到大航海时代，你准备好了吗？"),ship_id=14,8,false,"VOICE_NPC_DK_2"},
	},
	[17] = {
		['plot'] = 'camera',
		['param'] = {{1150,600,0.5}},
	},
}

return plot_1003013_info