-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_begin_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1280,640,0}},
	},
	[2] = {
		['plot'] = 'cameraScale',
		['param'] = {{1280,640,0},0.6,1.5},
	},
	[3] = {
		['plot'] = 'cameraMoveAndScale',
		['param'] = {{1280,640,0},{768,640,1.5,1.0},{{1280,640,0},1.0,1.5}},
	},
}

return plot_begin_info