-- ------------------------------
-- desc: generated by xls2data.py
-- source: 161_jy.xls
-- sheet: plot
-- ------------------------------


local plot_1100161_info = {
	[1] = {
		['plot'] = 'text_display',
		['param'] = {{T("清晨，战斗的号角最先在北端的左翼战线吹响，神圣同盟军率先向奥斯曼军发起了冲击……")}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {7,T("奥斯曼海盗首领"),2,T("警报！神圣同盟军发起突袭!"),ship_id=4},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{1900,800,0.5}},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {7,T("奥斯曼海盗首领"),2,T("可恶的神圣同盟，别慌，大家跟着我冲出敌阵!"),ship_id=4},
	},
}

return plot_1100161_info