-- ------------------------------
-- desc: generated by xls2data.py
-- source: bat_guildboss_11.xls
-- sheet: plot
-- ------------------------------


local plot_1600001_info = {
}

return plot_1600001_info