-- ------------------------------
-- desc: generated by xls2data.py
-- source: 72.xls
-- sheet: plot
-- ------------------------------


local plot_1000072_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1747,308,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {10,T("约翰.霍金斯"),2,T("你们竟敢放走我们捕获的奴隶！"),ship_id=3},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {10,T("约翰.霍金斯"),2,T("我们是经过伟大的女王允许的。"),ship_id=3},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {10,T("约翰.霍金斯"),2,T("“朱迪思”，把他们抓来当奴隶，这样我们才能向女王交待。"),ship_id=3},
	},
	[5] = {
		['plot'] = 'text_display',
		['param'] = {{T("若“贩奴军舰”被击沉，则奴隶会转变阵营。")}},
	},
	[6] = {
		['plot'] = 'camera',
		['param'] = {{1240,1052,2},{439,351,2}},
	},
}

return plot_1000072_info