-- ------------------------------
-- desc: generated by xls2data.py
-- source: 152.xls
-- sheet: plot
-- ------------------------------


local plot_1000152_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("在他们援军来之前，消灭驻扎在这里的舰队。")},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1600,640,0.5}},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {35,T("驻军首领"),2,T("等我的支援来了，你们就完蛋了……."),ship_id=8},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("糟了，他们援军来了……")},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{200,640,0.5}},
	},
}

return plot_1000152_info