-- ------------------------------
-- desc: generated by xls2data.py
-- source: 22_1.xls
-- sheet: plot
-- ------------------------------


local plot_1001022_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{850,850,2},{500,850,1},},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("海盗正在追击商船！我们要想办法阻止他们！可是这个数量。。。"),ship_id=1},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {72,T("戴肯"),2,T("别急船长，他们的位置很集中，可以用$(c:COLOR_GREEN)【链弹】$(c:COLOR_WHITE)同时让他们减速，试试！"),ship_id=1},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {24,T("海盗斥候"),2,T("可恶啊，船速大减！商船要跟丢了！"),ship_id=2},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("哈哈哈哈，成功了！")},
	},
	[6] = {
		['plot'] = 'camera',
		['param'] = {{950,800,1}},
	},
	[7] = {
		['plot'] = 'cameraScale',
		['param'] = {{950,800},2, 2},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {17,T("商船船长"),2,T("太棒了！勇敢的船长，给您留下$(c:COLOR_GREEN)【酒桶】$(c:COLOR_WHITE)，请随意使用吧！"),ship_id=5},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {72,T("戴肯"),2,T("船长，$(c:COLOR_GREEN)【酒桶】$(c:COLOR_WHITE)可以为我们恢复血量，请一定记住！"),ship_id=1,},
	},
	[10] = {
		['plot'] = 'dialog',
		['param'] = {17,T("商船船长"),2,T("是摩尔海盗！这些该死的海盗！这趟算是白跑了！"),ship_id=5},
	},
	[11] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,T("得到$(c:COLOR_GREEN)【酒桶】$(c:COLOR_WHITE)，船只耐久恢复！"),ship_id=1},
	},
}

return plot_1001022_info