-- ------------------------------
-- desc: generated by xls2data.py
-- source: 好友目标config.xlsx
-- sheet: Sheet1
-- ------------------------------


local friend_relation = {
	[1] = {
		['desc'] = T('同玩好友数量'),
		['img'] = 'common_item_hammer.png',
		['reward_num'] = 5,
		['goal_value'] = 5,
		['kind'] = 'num',
	},
	[2] = {
		['desc'] = T('同玩好友数量'),
		['img'] = 'common_item_letter.png',
		['reward_num'] = 10,
		['goal_value'] = 10,
		['kind'] = 'num',
	},
	[3] = {
		['desc'] = T('同玩好友数量'),
		['img'] = 'common_item_crystal.png',
		['reward_num'] = 5,
		['goal_value'] = 20,
		['kind'] = 'num',
	},
	[4] = {
		['desc'] = T('同玩好友等级'),
		['img'] = 'common_item_drawing_5.png',
		['reward_num'] = 15,
		['goal_value'] = 1200,
		['kind'] = 'level',
	},
	[5] = {
		['desc'] = T('同玩好友等级'),
		['img'] = 'common_item_trearusemap2.png',
		['reward_num'] = 2,
		['goal_value'] = 1400,
		['kind'] = 'level',
	},
	[6] = {
		['desc'] = T('同玩好友等级'),
		['img'] = 'common_item_medal.png',
		['reward_num'] = 2,
		['goal_value'] = 1500,
		['kind'] = 'level',
	},
}

return friend_relation