-- ------------------------------
-- desc: generated by xls2data.py
-- source: 好友度config.xlsx
-- sheet: Sheet1
-- ------------------------------


local friend_intimacy = {
	[1] = {
		['name'] = T('一级'),
		['exp'] = {0,10},
	},
	[2] = {
		['name'] = T('二级'),
		['exp'] = {10,30},
	},
	[3] = {
		['name'] = T('三级'),
		['exp'] = {30,100},
	},
	[4] = {
		['name'] = T('四级'),
		['exp'] = {100,200},
	},
	[5] = {
		['name'] = T('五级'),
		['exp'] = {200,500},
	},
}

return friend_intimacy