-- ------------------------------
-- desc: generated by xls2data.py
-- source: bind_dialog.xls
-- sheet: 绑定重登文本
-- ------------------------------


local bind_dialog = {
	[1] = {
		['text'] = T('在零星的鸥鸣中，初春的信风送来塔楼的钟声'),
		['width'] = 200,
		['voice'] = 'EX_WAVE',
		['size'] = 22,
		['time'] = 5,
	},
	[2] = {
		['text'] = T('我知道，是时候扬起我的风帆'),
		['width'] = 200,
		['voice'] = '',
		['size'] = 22,
		['time'] = 5,
	},
	[3] = {
		['text'] = T('海平线上，我看见父亲脸庞，微笑着，金光璀璨'),
		['width'] = 200,
		['voice'] = '',
		['size'] = 22,
		['time'] = 5,
	},
	[4] = {
		['text'] = T('再见吧，我的故乡！我的心，已在世界尽头翱翔！'),
		['width'] = 200,
		['voice'] = 'EX_WAVE',
		['size'] = 22,
		['time'] = 5,
	},
	[5] = {
		['text'] = T('寻找自由的彼岸，拥抱这大航海时代的……'),
		['width'] = 200,
		['voice'] = '',
		['size'] = 22,
		['time'] = 5,
	},
	[6] = {
		['text'] = T('荣光！'),
		['width'] = 200,
		['voice'] = '',
		['size'] = 32,
		['time'] = 5,
	},
}

return bind_dialog