-- ------------------------------
-- desc: generated by xls2data.py
-- source: camp.xls
-- sheet: 阵营
-- ------------------------------


local camp_info = {
	[1] = {
		['name'] = T('神圣同盟'),
		['area'] = 1,
	},
	[2] = {
		['name'] = T('奥斯曼自由阵线'),
		['area'] = 1,
	},
	[3] = {
		['name'] = T('海盗声望阵营'),
		['area'] = 0,
	},
	[4] = {
		['name'] = T('海军声望阵营'),
		['area'] = 0,
	},
}

return camp_info