-- ------------------------------
-- desc: generated by xls2data.py
-- source: function_cue.xls
-- sheet: 功能开放
-- ------------------------------


local feature_tip = {
	[1] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('技能系统'),
		['describe_3'] = T('2级'),
	},
	[2] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('交易所'),
		['describe_3'] = '',
	},
	[3] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('市政厅投资'),
		['describe_3'] = '',
	},
	[4] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('伙伴系统'),
		['describe_3'] = '',
	},
	[5] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('商城/船舶强化'),
		['describe_3'] = '',
	},
	[6] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('爵位系统'),
		['describe_3'] = '',
	},
	[7] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('建造旗舰'),
		['describe_3'] = '',
	},
	[8] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('招募系统'),
		['describe_3'] = '',
	},
	[9] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('悬赏任务/商会'),
		['describe_3'] = '',
	},
	[10] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('魔瓶试炼'),
		['describe_3'] = '',
	},
	[11] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('船舶改造/拆解'),
		['describe_3'] = '',
	},
	[12] = {
		['describe_1'] = T('即将下发'),
		['describe_2'] = T('登陆奖励'),
		['describe_3'] = '',
	},
	[13] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('遗迹探索'),
		['describe_3'] = '',
	},
	[14] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('自动战斗'),
		['describe_3'] = '',
	},
	[15] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('沉船宝藏'),
		['describe_3'] = '',
	},
	[16] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('维京竞技场'),
		['describe_3'] = '',
	},
	[17] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('日常任务'),
		['describe_3'] = '',
	},
	[19] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('好友/组队活动'),
		['describe_3'] = '',
	},
	[20] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('宝物洗炼'),
		['describe_3'] = '',
	},
	[21] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('委任经商'),
		['describe_3'] = '',
	},
	[22] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('试炼/夜晚活动'),
		['describe_3'] = T('20级'),
	},
	[23] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('特惠活动'),
		['describe_3'] = T('21级'),
	},
	[24] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('黑市商人'),
		['describe_3'] = T('22级'),
	},
	[25] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('排行/海神挑战'),
		['describe_3'] = T('23级'),
	},
	[26] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('海上活动'),
		['describe_3'] = T('24级'),
	},
	[27] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('商会活动'),
		['describe_3'] = T('25级'),
	},
	[28] = {
		['describe_1'] = T('即将开放'),
		['describe_2'] = T('传奇航海士'),
		['describe_3'] = T('30级'),
	},
}

return feature_tip