-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1131_end
-- ------------------------------


local port_power_info_1131_end = {
	[32] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = {"tx_port_change_hammer_green","tx_port_change_quan_green"},
	},
}

return port_power_info_1131_end