-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1690_end
-- ------------------------------


local port_power_info_1690_end = {
	[57] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = {"tx_port_change_fama_green","tx_port_change_quan_green"},
		['change_describe'] = T('在张保仔的协助下，兵不血刃，占领【亚丁】'),
	},
}

return port_power_info_1690_end