-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1650_end
-- ------------------------------


local port_power_info_1650_end = {
	[51] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = {"tx_port_change_fama_green","tx_port_change_quan_green"},
		['change_describe'] = T('成功封锁【亚齐】航线，城内守军投降'),
	},
}

return port_power_info_1650_end