-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1420_end
-- ------------------------------


local port_power_info_1420_end = {
	[44] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = {"tx_port_change_fama_yellow","tx_port_change_quan_yellow"},
	},
}

return port_power_info_1420_end