-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 2340_start
-- ------------------------------


local port_power_info_2340_start = {
	[1] = {
		['power_id'] = 1,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[2] = {
		['power_id'] = 1,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[3] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[4] = {
		['power_id'] = 1,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[5] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[6] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[7] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[8] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[9] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[10] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[11] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[12] = {
		['power_id'] = 3,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[13] = {
		['power_id'] = 3,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[14] = {
		['power_id'] = 3,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[15] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[16] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[17] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[18] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[19] = {
		['power_id'] = 5,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[20] = {
		['power_id'] = 5,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[21] = {
		['power_id'] = 5,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[22] = {
		['power_id'] = 5,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[23] = {
		['power_id'] = 5,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[24] = {
		['power_id'] = 5,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[25] = {
		['power_id'] = 5,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[26] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[27] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[28] = {
		['power_id'] = 5,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[29] = {
		['power_id'] = 10,
		['port_status'] = 1,
		['special_effects'] = {"tx_port_change_fama_red","tx_port_change_quan_red"},
	},
	[30] = {
		['power_id'] = 10,
		['port_status'] = 1,
		['special_effects'] = {"tx_port_change_fama_red","tx_port_change_quan_red"},
	},
	[31] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[32] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[33] = {
		['power_id'] = 10,
		['port_status'] = 1,
		['special_effects'] = {"tx_port_change_fama_red","tx_port_change_quan_red"},
	},
	[34] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[35] = {
		['power_id'] = 9,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[36] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[37] = {
		['power_id'] = 9,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[38] = {
		['power_id'] = 9,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[39] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[40] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[41] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[42] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[43] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[44] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[45] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[46] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[47] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[48] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[49] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[50] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[51] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[52] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[53] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[54] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[55] = {
		['power_id'] = 14,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[56] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[57] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[58] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[59] = {
		['power_id'] = 16,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[60] = {
		['power_id'] = 16,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[61] = {
		['power_id'] = 16,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[62] = {
		['power_id'] = 16,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[63] = {
		['power_id'] = 16,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[64] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[65] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[66] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[67] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[68] = {
		['power_id'] = 19,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[69] = {
		['power_id'] = 19,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[70] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[71] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[72] = {
		['power_id'] = 19,
		['port_status'] = 0,
		['special_effects'] = nil,
	},
	[73] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[74] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[75] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[76] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[77] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
	[78] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = nil,
	},
}

return port_power_info_2340_start