-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1830_end
-- ------------------------------


local port_power_info_1830_end = {
	[61] = {
		['power_id'] = 1,
		['port_status'] = 1,
		['special_effects'] = nil,
		['change_describe'] = '',
	},
}

return port_power_info_1830_end