-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1140_end
-- ------------------------------


local port_power_info_1140_end = {
	[32] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = {"tx_port_change_hammer_green","tx_port_change_quan_green"},
		['change_describe'] = T('击败贩奴舰队，【圣乔治】原住民得以幸免于难'),
	},
	[34] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = {"tx_port_change_fama_green","tx_port_change_quan_green"},
		['change_describe'] = T('击败贩奴舰队，【圣乔治】原住民得以幸免于难'),
	},
}

return port_power_info_1140_end