-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1210_end
-- ------------------------------


local port_power_info_1210_end = {
	[35] = {
		['power_id'] = 9,
		['port_status'] = 2,
		['special_effects'] = {"tx_port_change_ink_green","tx_port_change_quan_green"},
	},
}

return port_power_info_1210_end