-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1860_end
-- ------------------------------


local port_power_info_1860_end = {
	[60] = {
		['power_id'] = 16,
		['port_status'] = 0,
		['special_effects'] = {"tx_port_change_ink_yellow","tx_port_change_quan_yellow"},
		['change_describe'] = T('击败伊比利亚公国舰队，收复【泉州】'),
	},
}

return port_power_info_1860_end