-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1510_end
-- ------------------------------


local port_power_info_1510_end = {
	[48] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = {"tx_port_change_hammer_yellow","tx_port_change_quan_yellow"},
		['change_describe'] = T('率众突围【卡利卡特】，卡利卡特光复'),
	},
}

return port_power_info_1510_end