-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 2040_end
-- ------------------------------


local port_power_info_2040_end = {
	[68] = {
		['power_id'] = 19,
		['port_status'] = 0,
		['special_effects'] = {"tx_port_change_ink_yellow","tx_port_change_quan_yellow"},
	},
}

return port_power_info_2040_end