-- ------------------------------
-- desc: generated by xls2data.py
-- source: 势力表.xlsx
-- sheet: Sheet1
-- ------------------------------


local port_power = {
	[1] = {
		['name'] = T('伊比利亚公国'),
		['flagship_map_res'] = 'force_tordesillas_1.png',
		['flagship_port_res'] = '#force_tordesillas_2.png',
		['sea_belong'] = {1,6,7},
	},
	[2] = {
		['name'] = T('摩尔海盗'),
		['flagship_map_res'] = 'force_moore_1.png',
		['flagship_port_res'] = '#force_moore_2.png',
		['sea_belong'] = {1},
	},
	[3] = {
		['name'] = T('奥斯曼帝国'),
		['flagship_map_res'] = 'force_ousman_1.png',
		['flagship_port_res'] = '#force_ousman_2.png',
		['sea_belong'] = {1},
	},
	[4] = {
		['name'] = T('维京海盗'),
		['flagship_map_res'] = 'force_viking_1.png',
		['flagship_port_res'] = '#force_viking_2.png',
		['sea_belong'] = {2},
	},
	[5] = {
		['name'] = T('日不落帝国'),
		['flagship_map_res'] = 'force_britain_1.png',
		['flagship_port_res'] = '#force_britain_2.png',
		['sea_belong'] = {2,3},
	},
	[6] = {
		['name'] = T('汉萨同盟'),
		['flagship_map_res'] = 'force_hanse_1.png',
		['flagship_port_res'] = '#force_hanse_2.png',
		['sea_belong'] = {2},
	},
	[7] = {
		['name'] = T('神圣同盟'),
		['flagship_map_res'] = 'force_armada_1.png',
		['flagship_port_res'] = '#force_armada_2.png',
		['sea_belong'] = {1},
	},
	[8] = {
		['name'] = T('黑金商队'),
		['flagship_map_res'] = 'force_blackgold_1.png',
		['flagship_port_res'] = '#force_blackgold_2.png',
		['sea_belong'] = {3},
	},
	[9] = {
		['name'] = T('阿班图部落'),
		['flagship_map_res'] = 'force_ubuntu_1.png',
		['flagship_port_res'] = '#force_ubuntu_2.png',
		['sea_belong'] = {3},
	},
	[10] = {
		['name'] = T('非洲守护军'),
		['flagship_map_res'] = 'force_seraph_1.png',
		['flagship_port_res'] = '#force_seraph_2.png',
		['sea_belong'] = {3},
	},
	[11] = {
		['name'] = T('东印度公司'),
		['flagship_map_res'] = 'force_eastindia_1.png',
		['flagship_port_res'] = '#force_eastindia_2.png',
		['sea_belong'] = {3,4,5},
	},
	[12] = {
		['name'] = T('萨法尔王国'),
		['flagship_map_res'] = 'force_safar_1.png',
		['flagship_port_res'] = '#force_safar_2.png',
		['sea_belong'] = {4},
	},
	[13] = {
		['name'] = T('西印度公司'),
		['flagship_map_res'] = 'force_westindia_1.png',
		['flagship_port_res'] = '#force_westindia_2.png',
		['sea_belong'] = {4},
	},
	[14] = {
		['name'] = T('红旗帮'),
		['flagship_map_res'] = 'force_redflag_1.png',
		['flagship_port_res'] = '#force_redflag_2.png',
		['sea_belong'] = {5},
	},
	[15] = {
		['name'] = T('潮州军'),
		['flagship_map_res'] = 'force_chaozhou_1.png',
		['flagship_port_res'] = '#force_chaozhou_2.png',
		['sea_belong'] = {5},
	},
	[16] = {
		['name'] = T('大明'),
		['flagship_map_res'] = 'force_ming_1.png',
		['flagship_port_res'] = '#force_ming_2.png',
		['sea_belong'] = {6},
	},
	[17] = {
		['name'] = T('倭寇'),
		['flagship_map_res'] = 'force_japanese_1.png',
		['flagship_port_res'] = '#force_japanese_2.png',
		['sea_belong'] = {6},
	},
	[18] = {
		['name'] = T('清'),
		['flagship_map_res'] = 'force_qing_1.png',
		['flagship_port_res'] = '#force_qing_2.png',
		['sea_belong'] = {6},
	},
	[19] = {
		['name'] = T('黑萨姆海盗团'),
		['flagship_map_res'] = 'force_bellamy_1.png',
		['flagship_port_res'] = '#force_bellamy_2.png',
		['sea_belong'] = {7},
	},
	[20] = {
		['name'] = T('神国'),
		['flagship_map_res'] = 'force_promethus_1.png',
		['flagship_port_res'] = '#force_promethus_2.png',
		['sea_belong'] = {7},
	},
}

return port_power