-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1540_end
-- ------------------------------


local port_power_info_1540_end = {
	[49] = {
		['power_id'] = 12,
		['port_status'] = 0,
		['special_effects'] = {"tx_port_change_fama_yellow","tx_port_change_quan_yellow"},
		['change_describe'] = T('设计解决锡兰守军，占领锡兰'),
	},
}

return port_power_info_1540_end