-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口势力分布表.xlsx
-- sheet: 1100_end
-- ------------------------------


local port_power_info_1100_end = {
	[30] = {
		['power_id'] = 0,
		['port_status'] = 2,
		['special_effects'] = {"tx_port_change_fama_green","tx_port_change_quan_green"},
		['change_describe'] = T('【佛得角】原住民被武装起来反抗黑金商队，佛得角解放'),
	},
}

return port_power_info_1100_end