-- ------------------------------
-- desc: generated by xls2data.py
-- source: 势力港口类型图标.xlsx
-- sheet: Sheet1
-- ------------------------------


local power_to_port_img = {
	['market'] = {
		['power_img'] = {"common_port_business_neutrality.png", "common_port_business_rivalry.png", "common_port_business_friendly.png"},
	},
	['pub'] = {
		['power_img'] = {"common_port_culture_neutrality.png", "common_port_culture_rivalry.png", "common_port_culture_friendly.png"},
	},
	['ship'] = {
		['power_img'] = {"common_port_industry_neutrality.png", "common_port_industry_rivalry.png", "common_port_industry_friendly.png"},
	},
}

return power_to_port_img