-- ------------------------------
-- desc: generated by xls2data.py
-- source: battle_slogan.xls
-- sheet: Sheet1
-- ------------------------------


local battle_slogan = {
	[1002] = {
		['random'] = 50,
		['slogan_info'] = {male=T("机会来了！瞄准！开火！"),female =T("进入射程了，所有火炮准备，开火！")},
		['voice'] = {male="VOICE_BATTLE_1004",female ="VOICE_BATTLE_1034"},
	},
	[1003] = {
		['random'] = 50,
		['slogan_info'] = {male=T("机会来了！瞄准！开火！"),female =T("进入射程了，所有火炮准备，开火！")},
		['voice'] = {male="VOICE_BATTLE_1004",female ="VOICE_BATTLE_1034"},
	},
	[1004] = {
		['random'] = 50,
		['slogan_info'] = {male=T("机会来了！瞄准！开火！"),female =T("进入射程了，所有火炮准备，开火！")},
		['voice'] = {male="VOICE_BATTLE_1004",female ="VOICE_BATTLE_1034"},
	},
	[1123] = {
		['random'] = 50,
		['slogan_info'] = {male=T("机会来了！瞄准！开火！"),female =T("进入射程了，所有火炮准备，开火！")},
		['voice'] = {male="VOICE_BATTLE_1004",female ="VOICE_BATTLE_1034"},
	},
	[1201] = {
		['random'] = 50,
		['slogan_info'] = {male=T("机会来了！瞄准！开火！"),female =T("进入射程了，所有火炮准备，开火！")},
		['voice'] = {male="VOICE_BATTLE_1004",female ="VOICE_BATTLE_1034"},
	},
	[1202] = {
		['random'] = 50,
		['slogan_info'] = {male=T("机会来了！瞄准！开火！"),female =T("进入射程了，所有火炮准备，开火！")},
		['voice'] = {male="VOICE_BATTLE_1004",female ="VOICE_BATTLE_1034"},
	},
	[1010] = {
		['random'] = 50,
		['slogan_info'] = {male=T("上链弹！把敌人桅杆都给我拆咯！"),female =T("瞄准桅杆！狠狠的打！")},
		['voice'] = {male="VOICE_BATTLE_1019",female ="VOICE_BATTLE_1035"},
	},
	[1011] = {
		['random'] = 50,
		['slogan_info'] = {male=T("上链弹！把敌人桅杆都给我拆咯！"),female =T("瞄准桅杆！狠狠的打！")},
		['voice'] = {male="VOICE_BATTLE_1019",female ="VOICE_BATTLE_1035"},
	},
	[1013] = {
		['random'] = 50,
		['slogan_info'] = {male=T("上链弹！把敌人桅杆都给我拆咯！"),female =T("瞄准桅杆！狠狠的打！")},
		['voice'] = {male="VOICE_BATTLE_1019",female ="VOICE_BATTLE_1035"},
	},
	[1125] = {
		['random'] = 50,
		['slogan_info'] = {male=T("上链弹！把敌人桅杆都给我拆咯！"),female =T("瞄准桅杆！狠狠的打！")},
		['voice'] = {male="VOICE_BATTLE_1019",female ="VOICE_BATTLE_1035"},
	},
	[1203] = {
		['random'] = 50,
		['slogan_info'] = {male=T("上链弹！把敌人桅杆都给我拆咯！"),female =T("瞄准桅杆！狠狠的打！")},
		['voice'] = {male="VOICE_BATTLE_1019",female ="VOICE_BATTLE_1035"},
	},
	[1204] = {
		['random'] = 50,
		['slogan_info'] = {male=T("上链弹！把敌人桅杆都给我拆咯！"),female =T("瞄准桅杆！狠狠的打！")},
		['voice'] = {male="VOICE_BATTLE_1019",female ="VOICE_BATTLE_1035"},
	},
	[1018] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抓紧绳索荡过去！呼哈！"),female =T("拔出武器，到敌人甲板上解决他们！")},
		['voice'] = {male="VOICE_BATTLE_1020",female ="VOICE_BATTLE_1036"},
	},
	[1019] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抓紧绳索荡过去！呼哈！"),female =T("拔出武器，到敌人甲板上解决他们！")},
		['voice'] = {male="VOICE_BATTLE_1020",female ="VOICE_BATTLE_1036"},
	},
	[1021] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抓紧绳索荡过去！呼哈！"),female =T("拔出武器，到敌人甲板上解决他们！")},
		['voice'] = {male="VOICE_BATTLE_1020",female ="VOICE_BATTLE_1036"},
	},
	[1126] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抓紧绳索荡过去！呼哈！"),female =T("拔出武器，到敌人甲板上解决他们！")},
		['voice'] = {male="VOICE_BATTLE_1020",female ="VOICE_BATTLE_1036"},
	},
	[1213] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抓紧绳索荡过去！呼哈！"),female =T("拔出武器，到敌人甲板上解决他们！")},
		['voice'] = {male="VOICE_BATTLE_1020",female ="VOICE_BATTLE_1036"},
	},
	[1214] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抓紧绳索荡过去！呼哈！"),female =T("拔出武器，到敌人甲板上解决他们！")},
		['voice'] = {male="VOICE_BATTLE_1020",female ="VOICE_BATTLE_1036"},
	},
	[1026] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抛出钩索别让他们逃了，蠢货们！"),female =T("勾住他们，笨蛋！")},
		['voice'] = {male="VOICE_BATTLE_1021",female ="VOICE_BATTLE_1037"},
	},
	[1028] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抛出钩索别让他们逃了，蠢货们！"),female =T("勾住他们，笨蛋！")},
		['voice'] = {male="VOICE_BATTLE_1021",female ="VOICE_BATTLE_1037"},
	},
	[1029] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抛出钩索别让他们逃了，蠢货们！"),female =T("勾住他们，笨蛋！")},
		['voice'] = {male="VOICE_BATTLE_1021",female ="VOICE_BATTLE_1037"},
	},
	[1127] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抛出钩索别让他们逃了，蠢货们！"),female =T("勾住他们，笨蛋！")},
		['voice'] = {male="VOICE_BATTLE_1021",female ="VOICE_BATTLE_1037"},
	},
	[1215] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抛出钩索别让他们逃了，蠢货们！"),female =T("勾住他们，笨蛋！")},
		['voice'] = {male="VOICE_BATTLE_1021",female ="VOICE_BATTLE_1037"},
	},
	[1216] = {
		['random'] = 50,
		['slogan_info'] = {male=T("抛出钩索别让他们逃了，蠢货们！"),female =T("勾住他们，笨蛋！")},
		['voice'] = {male="VOICE_BATTLE_1021",female ="VOICE_BATTLE_1037"},
	},
	[1030] = {
		['random'] = 50,
		['slogan_info'] = {male=T("举高护板保护船舷！把脑袋缩回去！"),female =T("到舷墙边举起护板，给我顶住！")},
		['voice'] = {male="VOICE_BATTLE_1022",female ="VOICE_BATTLE_1038"},
	},
	[1032] = {
		['random'] = 50,
		['slogan_info'] = {male=T("举高护板保护船舷！把脑袋缩回去！"),female =T("到舷墙边举起护板，给我顶住！")},
		['voice'] = {male="VOICE_BATTLE_1022",female ="VOICE_BATTLE_1038"},
	},
	[1033] = {
		['random'] = 50,
		['slogan_info'] = {male=T("举高护板保护船舷！把脑袋缩回去！"),female =T("到舷墙边举起护板，给我顶住！")},
		['voice'] = {male="VOICE_BATTLE_1022",female ="VOICE_BATTLE_1038"},
	},
	[1128] = {
		['random'] = 50,
		['slogan_info'] = {male=T("举高护板保护船舷！把脑袋缩回去！"),female =T("到舷墙边举起护板，给我顶住！")},
		['voice'] = {male="VOICE_BATTLE_1022",female ="VOICE_BATTLE_1038"},
	},
	[1211] = {
		['random'] = 50,
		['slogan_info'] = {male=T("举高护板保护船舷！把脑袋缩回去！"),female =T("到舷墙边举起护板，给我顶住！")},
		['voice'] = {male="VOICE_BATTLE_1022",female ="VOICE_BATTLE_1038"},
	},
	[1212] = {
		['random'] = 50,
		['slogan_info'] = {male=T("举高护板保护船舷！把脑袋缩回去！"),female =T("到舷墙边举起护板，给我顶住！")},
		['voice'] = {male="VOICE_BATTLE_1022",female ="VOICE_BATTLE_1038"},
	},
	[1006] = {
		['random'] = 50,
		['slogan_info'] = {male=T("堵好漏洞！不，放开那个酒桶！笨蛋！"),female =T("堵住漏洞！用脑子或身子！快！")},
		['voice'] = {male="VOICE_BATTLE_1023",female ="VOICE_BATTLE_1039"},
	},
	[1007] = {
		['random'] = 50,
		['slogan_info'] = {male=T("堵好漏洞！不，放开那个酒桶！笨蛋！"),female =T("堵住漏洞！用脑子或身子！快！")},
		['voice'] = {male="VOICE_BATTLE_1023",female ="VOICE_BATTLE_1039"},
	},
	[1009] = {
		['random'] = 50,
		['slogan_info'] = {male=T("堵好漏洞！不，放开那个酒桶！笨蛋！"),female =T("堵住漏洞！用脑子或身子！快！")},
		['voice'] = {male="VOICE_BATTLE_1023",female ="VOICE_BATTLE_1039"},
	},
	[1129] = {
		['random'] = 50,
		['slogan_info'] = {male=T("堵好漏洞！不，放开那个酒桶！笨蛋！"),female =T("堵住漏洞！用脑子或身子！快！")},
		['voice'] = {male="VOICE_BATTLE_1023",female ="VOICE_BATTLE_1039"},
	},
	[1209] = {
		['random'] = 50,
		['slogan_info'] = {male=T("堵好漏洞！不，放开那个酒桶！笨蛋！"),female =T("堵住漏洞！用脑子或身子！快！")},
		['voice'] = {male="VOICE_BATTLE_1023",female ="VOICE_BATTLE_1039"},
	},
	[1210] = {
		['random'] = 50,
		['slogan_info'] = {male=T("堵好漏洞！不，放开那个酒桶！笨蛋！"),female =T("堵住漏洞！用脑子或身子！快！")},
		['voice'] = {male="VOICE_BATTLE_1023",female ="VOICE_BATTLE_1039"},
	},
	[1034] = {
		['random'] = 50,
		['slogan_info'] = {male=T("危险！注意回避！"),female =T("满舵，下锚，避开攻击！")},
		['voice'] = {male="VOICE_BATTLE_1003",female ="VOICE_BATTLE_1040"},
	},
	[1036] = {
		['random'] = 50,
		['slogan_info'] = {male=T("危险！注意回避！"),female =T("满舵，下锚，避开攻击！")},
		['voice'] = {male="VOICE_BATTLE_1003",female ="VOICE_BATTLE_1040"},
	},
	[1037] = {
		['random'] = 50,
		['slogan_info'] = {male=T("危险！注意回避！"),female =T("满舵，下锚，避开攻击！")},
		['voice'] = {male="VOICE_BATTLE_1003",female ="VOICE_BATTLE_1040"},
	},
	[1132] = {
		['random'] = 50,
		['slogan_info'] = {male=T("危险！注意回避！"),female =T("满舵，下锚，避开攻击！")},
		['voice'] = {male="VOICE_BATTLE_1003",female ="VOICE_BATTLE_1040"},
	},
	[1205] = {
		['random'] = 50,
		['slogan_info'] = {male=T("危险！注意回避！"),female =T("满舵，下锚，避开攻击！")},
		['voice'] = {male="VOICE_BATTLE_1003",female ="VOICE_BATTLE_1040"},
	},
	[1206] = {
		['random'] = 50,
		['slogan_info'] = {male=T("危险！注意回避！"),female =T("满舵，下锚，避开攻击！")},
		['voice'] = {male="VOICE_BATTLE_1003",female ="VOICE_BATTLE_1040"},
	},
	[1038] = {
		['random'] = 50,
		['slogan_info'] = {male=T("满帆受风，下桨，全速前进！"),female =T("让侧舷吃足风力，全速前进！")},
		['voice'] = {male="VOICE_BATTLE_1024",female ="VOICE_BATTLE_1041"},
	},
	[1039] = {
		['random'] = 50,
		['slogan_info'] = {male=T("满帆受风，下桨，全速前进！"),female =T("让侧舷吃足风力，全速前进！")},
		['voice'] = {male="VOICE_BATTLE_1024",female ="VOICE_BATTLE_1041"},
	},
	[1041] = {
		['random'] = 50,
		['slogan_info'] = {male=T("满帆受风，下桨，全速前进！"),female =T("让侧舷吃足风力，全速前进！")},
		['voice'] = {male="VOICE_BATTLE_1024",female ="VOICE_BATTLE_1041"},
	},
	[1133] = {
		['random'] = 50,
		['slogan_info'] = {male=T("满帆受风，下桨，全速前进！"),female =T("让侧舷吃足风力，全速前进！")},
		['voice'] = {male="VOICE_BATTLE_1024",female ="VOICE_BATTLE_1041"},
	},
	[1207] = {
		['random'] = 50,
		['slogan_info'] = {male=T("满帆受风，下桨，全速前进！"),female =T("让侧舷吃足风力，全速前进！")},
		['voice'] = {male="VOICE_BATTLE_1024",female ="VOICE_BATTLE_1041"},
	},
	[1208] = {
		['random'] = 50,
		['slogan_info'] = {male=T("满帆受风，下桨，全速前进！"),female =T("让侧舷吃足风力，全速前进！")},
		['voice'] = {male="VOICE_BATTLE_1024",female ="VOICE_BATTLE_1041"},
	},
}

return battle_slogan