-- ------------------------------
-- desc: generated by xls2data.py
-- source: bullet.xls
-- sheet: Sheet1
-- ------------------------------


local bullet_info = {
	[1] = {
		['name'] = 'pd_01',
		['fire_effect'] = 'pd_01',
		['fire_sound_id'] = 'FIRE_SMALL',
		['hited_sound_id'] = 'HIT_SMALL',
	},
	[2] = {
		['name'] = 'pd_02',
		['fire_effect'] = 'pd_02',
		['fire_sound_id'] = 'FIRE_MEDIUM',
		['hited_sound_id'] = 'HIT_MEDIUM',
	},
	[3] = {
		['name'] = 'pd_03',
		['fire_effect'] = 'pd_03',
		['fire_sound_id'] = 'FIRE_LARGE',
		['hited_sound_id'] = 'HIT_LARGE',
	},
	[4] = {
		['name'] = 'liuxingchui',
		['fire_effect'] = 'liuxingchui',
		['fire_sound_id'] = 'FIRE_MEDIUM',
		['hited_sound_id'] = 'FIRE_MEDIUM',
	},
	[5] = {
		['name'] = 'liuxingchui',
		['fire_effect'] = 'paodan_ice',
		['fire_sound_id'] = 'FIRE_SMALL',
		['hited_sound_id'] = 'HIT_SMALL',
	},
	[6] = {
		['name'] = 'pd_03',
		['fire_effect'] = 'tx_0166',
		['fire_sound_id'] = 'FIRE_LARGE',
		['hited_sound_id'] = 'HIT_LARGE',
	},
	[7] = {
		['name'] = 'tx_0164_model',
		['fire_effect'] = 'tx_0164_model',
		['fire_sound_id'] = 'FIRE_LARGE',
		['hited_sound_id'] = 'HIT_LARGE',
	},
	[8] = {
		['name'] = '',
		['fire_effect'] = 'tx_0174',
		['fire_sound_id'] = 'FIRE_SMALL',
		['hited_sound_id'] = 'HIT_SMALL',
	},
	[9] = {
		['name'] = '',
		['fire_effect'] = 'pd_04',
		['fire_sound_id'] = 'FIRE_SMALL',
		['hited_sound_id'] = 'HIT_SMALL',
	},
	[10] = {
		['name'] = '',
		['fire_effect'] = 'pd_05',
		['fire_sound_id'] = 'FIRE_SMALL',
		['hited_sound_id'] = 'HIT_SMALL',
	},
	[11] = {
		['name'] = '',
		['fire_effect'] = 'pd_06',
		['fire_sound_id'] = 'FIRE_SMALL',
		['hited_sound_id'] = 'HIT_SMALL',
	},
	[12] = {
		['name'] = '',
		['fire_effect'] = 'tx_kraken_pao',
		['fire_sound_id'] = 'FIRE_SMALL',
		['hited_sound_id'] = 'HIT_SMALL',
	},
}

return bullet_info