return 
{
['1'] = {
    ['area_id'] = 1,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 30,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['10'] = {
    ['area_id'] = 2,
    ['cnt'] = 90,
    ['id'] = 226,
    ['invest_num'] = 74,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['11'] = {
    ['area_id'] = 3,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 30,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['12'] = {
    ['area_id'] = 3,
    ['cnt'] = 40,
    ['id'] = 226,
    ['invest_num'] = 40,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['13'] = {
    ['area_id'] = 3,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 50,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['14'] = {
    ['area_id'] = 3,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 64,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['15'] = {
    ['area_id'] = 3,
    ['cnt'] = 90,
    ['id'] = 226,
    ['invest_num'] = 76,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['16'] = {
    ['area_id'] = 4,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 30,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['17'] = {
    ['area_id'] = 4,
    ['cnt'] = 40,
    ['id'] = 226,
    ['invest_num'] = 40,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['18'] = {
    ['area_id'] = 4,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 50,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['19'] = {
    ['area_id'] = 4,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 54,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['2'] = {
    ['area_id'] = 1,
    ['cnt'] = 80,
    ['id'] = 226,
    ['invest_num'] = 60,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['20'] = {
    ['area_id'] = 4,
    ['cnt'] = 90,
    ['id'] = 226,
    ['invest_num'] = 64,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['21'] = {
    ['area_id'] = 5,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 20,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['22'] = {
    ['area_id'] = 5,
    ['cnt'] = 40,
    ['id'] = 226,
    ['invest_num'] = 30,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['23'] = {
    ['area_id'] = 5,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 40,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['24'] = {
    ['area_id'] = 5,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 44,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['25'] = {
    ['area_id'] = 5,
    ['cnt'] = 80,
    ['id'] = 226,
    ['invest_num'] = 52,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['26'] = {
    ['area_id'] = 6,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 20,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['27'] = {
    ['area_id'] = 6,
    ['cnt'] = 40,
    ['id'] = 226,
    ['invest_num'] = 30,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['28'] = {
    ['area_id'] = 6,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 40,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['29'] = {
    ['area_id'] = 6,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 46,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['3'] = {
    ['area_id'] = 1,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 80,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['30'] = {
    ['area_id'] = 6,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 54,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['31'] = {
    ['area_id'] = 7,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 30,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['32'] = {
    ['area_id'] = 7,
    ['cnt'] = 40,
    ['id'] = 226,
    ['invest_num'] = 40,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['33'] = {
    ['area_id'] = 7,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 50,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['34'] = {
    ['area_id'] = 7,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 64,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['35'] = {
    ['area_id'] = 7,
    ['cnt'] = 90,
    ['id'] = 226,
    ['invest_num'] = 76,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['36'] = {
    ['area_id'] = 10,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 30,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['37'] = {
    ['area_id'] = 10,
    ['cnt'] = 40,
    ['id'] = 226,
    ['invest_num'] = 40,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['38'] = {
    ['area_id'] = 10,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 50,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['39'] = {
    ['area_id'] = 10,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 64,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['4'] = {
    ['area_id'] = 1,
    ['cnt'] = 80,
    ['id'] = 226,
    ['invest_num'] = 97,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['40'] = {
    ['area_id'] = 10,
    ['cnt'] = 90,
    ['id'] = 226,
    ['invest_num'] = 76,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['41'] = {
    ['area_id'] = 1,
    ['cnt'] = 30,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 5,
    ['type'] = 'gold',
    },
['42'] = {
    ['area_id'] = 1,
    ['cnt'] = 30,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 8,
    ['type'] = 'gold',
    },
['43'] = {
    ['area_id'] = 1,
    ['cnt'] = 45,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 12,
    ['type'] = 'gold',
    },
['44'] = {
    ['area_id'] = 1,
    ['cnt'] = 60,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 15,
    ['type'] = 'gold',
    },
['45'] = {
    ['area_id'] = 1,
    ['cnt'] = 90,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 28,
    ['type'] = 'gold',
    },
['46'] = {
    ['area_id'] = 2,
    ['cnt'] = 30,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 5,
    ['type'] = 'gold',
    },
['47'] = {
    ['area_id'] = 2,
    ['cnt'] = 60,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 15,
    ['type'] = 'gold',
    },
['48'] = {
    ['area_id'] = 2,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 20,
    ['type'] = 'gold',
    },
['49'] = {
    ['area_id'] = 2,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 25,
    ['type'] = 'gold',
    },
['5'] = {
    ['area_id'] = 1,
    ['cnt'] = 100,
    ['id'] = 226,
    ['invest_num'] = 114,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['50'] = {
    ['area_id'] = 2,
    ['cnt'] = 90,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 38,
    ['type'] = 'gold',
    },
['51'] = {
    ['area_id'] = 3,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 10,
    ['type'] = 'gold',
    },
['52'] = {
    ['area_id'] = 3,
    ['cnt'] = 40,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 15,
    ['type'] = 'gold',
    },
['53'] = {
    ['area_id'] = 3,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 20,
    ['type'] = 'gold',
    },
['54'] = {
    ['area_id'] = 3,
    ['cnt'] = 60,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 24,
    ['type'] = 'gold',
    },
['55'] = {
    ['area_id'] = 3,
    ['cnt'] = 90,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 38,
    ['type'] = 'gold',
    },
['56'] = {
    ['area_id'] = 4,
    ['cnt'] = 30,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 4,
    ['type'] = 'gold',
    },
['57'] = {
    ['area_id'] = 4,
    ['cnt'] = 30,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 8,
    ['type'] = 'gold',
    },
['58'] = {
    ['area_id'] = 4,
    ['cnt'] = 45,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 12,
    ['type'] = 'gold',
    },
['59'] = {
    ['area_id'] = 4,
    ['cnt'] = 60,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 15,
    ['type'] = 'gold',
    },
['6'] = {
    ['area_id'] = 2,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 30,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['60'] = {
    ['area_id'] = 4,
    ['cnt'] = 90,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 28,
    ['type'] = 'gold',
    },
['61'] = {
    ['area_id'] = 5,
    ['cnt'] = 30,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 5,
    ['type'] = 'gold',
    },
['62'] = {
    ['area_id'] = 5,
    ['cnt'] = 60,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 15,
    ['type'] = 'gold',
    },
['63'] = {
    ['area_id'] = 5,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 25,
    ['type'] = 'gold',
    },
['64'] = {
    ['area_id'] = 5,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 30,
    ['type'] = 'gold',
    },
['65'] = {
    ['area_id'] = 5,
    ['cnt'] = 80,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 38,
    ['type'] = 'gold',
    },
['66'] = {
    ['area_id'] = 6,
    ['cnt'] = 30,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 5,
    ['type'] = 'gold',
    },
['67'] = {
    ['area_id'] = 6,
    ['cnt'] = 40,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 10,
    ['type'] = 'gold',
    },
['68'] = {
    ['area_id'] = 6,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 20,
    ['type'] = 'gold',
    },
['69'] = {
    ['area_id'] = 6,
    ['cnt'] = 90,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 30,
    ['type'] = 'gold',
    },
['7'] = {
    ['area_id'] = 2,
    ['cnt'] = 40,
    ['id'] = 226,
    ['invest_num'] = 40,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['70'] = {
    ['area_id'] = 6,
    ['cnt'] = 100,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 49,
    ['type'] = 'gold',
    },
['71'] = {
    ['area_id'] = 7,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 10,
    ['type'] = 'gold',
    },
['72'] = {
    ['area_id'] = 7,
    ['cnt'] = 100,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 30,
    ['type'] = 'gold',
    },
['73'] = {
    ['area_id'] = 7,
    ['cnt'] = 100,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 50,
    ['type'] = 'gold',
    },
['74'] = {
    ['area_id'] = 7,
    ['cnt'] = 100,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 62,
    ['type'] = 'gold',
    },
['75'] = {
    ['area_id'] = 7,
    ['cnt'] = 80,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 69,
    ['type'] = 'gold',
    },
['76'] = {
    ['area_id'] = 10,
    ['cnt'] = 20,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 3,
    ['type'] = 'gold',
    },
['77'] = {
    ['area_id'] = 10,
    ['cnt'] = 20,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 6,
    ['type'] = 'gold',
    },
['78'] = {
    ['area_id'] = 10,
    ['cnt'] = 30,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 8,
    ['type'] = 'gold',
    },
['79'] = {
    ['area_id'] = 10,
    ['cnt'] = 30,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 11,
    ['type'] = 'gold',
    },
['8'] = {
    ['area_id'] = 2,
    ['cnt'] = 50,
    ['id'] = 226,
    ['invest_num'] = 50,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
['80'] = {
    ['area_id'] = 10,
    ['cnt'] = 30,
    ['id'] = 226,
    ['invest_num'] = 0,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 14,
    ['type'] = 'gold',
    },
['9'] = {
    ['area_id'] = 2,
    ['cnt'] = 70,
    ['id'] = 226,
    ['invest_num'] = 63,
    ['memo'] = '',
    ['rate'] = 1,
    ['relic_num'] = 0,
    ['type'] = 'gold',
    },
}