-- ------------------------------
-- desc: generated by xls2data.py
-- source: config.xls
-- sheet: 精华消耗
-- ------------------------------


local baowu_consume = {
	[1] = {
		['refining_1'] = 0,
		['refining_2'] = 0,
		['refining_essence_1'] = 100,
		['refining_essence_2'] = 200,
		['essence'] = 5,
		['level'] = 9,
	},
	[2] = {
		['refining_1'] = 0,
		['refining_2'] = 0,
		['refining_essence_1'] = 100,
		['refining_essence_2'] = 200,
		['essence'] = 10,
		['level'] = 19,
	},
	[3] = {
		['refining_1'] = 0,
		['refining_2'] = 0,
		['refining_essence_1'] = 100,
		['refining_essence_2'] = 200,
		['essence'] = 15,
		['level'] = 24,
	},
	[4] = {
		['refining_1'] = 0,
		['refining_2'] = 0,
		['refining_essence_1'] = 100,
		['refining_essence_2'] = 200,
		['essence'] = 20,
		['level'] = 70,
	},
}

return baowu_consume