-- ------------------------------
-- desc: generated by xls2data.py
-- source: config.xls
-- sheet: 宝物拆解
-- ------------------------------


local baowu_dismantling = {
	[1] = {
		['baowu_quality_1'] = {[3]=1},
		['baowu_quality_2'] = {[3]=5},
		['baowu_quality_3'] = {[3]=15},
		['baowu_quality_4'] = {[3]=50},
		['baowu_quality_5'] = {[3]=150},
	},
	[2] = {
		['baowu_quality_1'] = {[3]=1},
		['baowu_quality_2'] = {[3]=5},
		['baowu_quality_3'] = {[3]=15},
		['baowu_quality_4'] = {[3]=50},
		['baowu_quality_5'] = {[3]=150},
	},
	[3] = {
		['baowu_quality_1'] = {[3]=2},
		['baowu_quality_2'] = {[3]=10},
		['baowu_quality_3'] = {[3]=30},
		['baowu_quality_4'] = {[3]=100},
		['baowu_quality_5'] = {[3]=300},
	},
	[4] = {
		['baowu_quality_1'] = {[3]=4},
		['baowu_quality_2'] = {[3]=20},
		['baowu_quality_3'] = {[3]=60},
		['baowu_quality_4'] = {[3]=200},
		['baowu_quality_5'] = {[3]=600},
	},
	[5] = {
		['baowu_quality_1'] = {[3]=8},
		['baowu_quality_2'] = {[3]=40},
		['baowu_quality_3'] = {[3]=120},
		['baowu_quality_4'] = {[3]=400},
		['baowu_quality_5'] = {[3]=1200},
	},
	[6] = {
		['baowu_quality_1'] = {[3]=16},
		['baowu_quality_2'] = {[3]=80},
		['baowu_quality_3'] = {[3]=240},
		['baowu_quality_4'] = {[3]=800},
		['baowu_quality_5'] = {[3]=2400},
	},
	[7] = {
		['baowu_quality_1'] = {[3]=32},
		['baowu_quality_2'] = {[3]=160},
		['baowu_quality_3'] = {[3]=320},
		['baowu_quality_4'] = {[3]=1600},
		['baowu_quality_5'] = {[3]=4800},
	},
}

return baowu_dismantling