-- ------------------------------
-- desc: generated by xls2data.py
-- source: config.xls
-- sheet: 宝物洗练评级
-- ------------------------------


local baowu_refine_rank = {
	[1] = {
		['per'] = 10,
		['special_attr'] = 0,
	},
	[2] = {
		['per'] = 20,
		['special_attr'] = 0,
	},
	[3] = {
		['per'] = 30,
		['special_attr'] = 0,
	},
	[4] = {
		['per'] = 40,
		['special_attr'] = 0,
	},
	[5] = {
		['per'] = 50,
		['special_attr'] = 0,
	},
	[6] = {
		['per'] = 60,
		['special_attr'] = 1,
	},
	[7] = {
		['per'] = 70,
		['special_attr'] = 1,
	},
	[8] = {
		['per'] = 80,
		['special_attr'] = 2,
	},
}

return baowu_refine_rank