-- ------------------------------
-- desc: generated by xls2data.py
-- source: 船舶装备解锁属性.xlsx
-- sheet: 船舶装备解锁属性
-- ------------------------------


local equip_unlock_attr = {
	[1] = {
		['lv'] = 12,
		['occup'] = {1, 2, 3},
		['describe'] = T('暴击率+5%,抗暴率+5%'),
	},
	[2] = {
		['lv'] = 15,
		['occup'] = {1, 2, 3},
		['describe'] = T('命中率+5%,闪避率+5%'),
	},
	[3] = {
		['lv'] = 18,
		['occup'] = {1, 2, 3},
		['describe'] = T('伤害减免+10%'),
	},
	[4] = {
		['lv'] = 21,
		['occup'] = {1, 2, 3},
		['describe'] = T('暴击率+8%,抗暴率+8%'),
	},
	[5] = {
		['lv'] = 24,
		['occup'] = {1, 2, 3},
		['describe'] = T('命中率+8%，闪避率+8%'),
	},
	[6] = {
		['lv'] = 27,
		['occup'] = {1, 2, 3},
		['describe'] = T('伤害减免+15%'),
	},
	[7] = {
		['lv'] = 30,
		['occup'] = {1, 2, 3},
		['describe'] = T('伤害增幅+20%'),
	},
}

return equip_unlock_attr