-- ------------------------------
-- desc: generated by xls2data.py
-- source: config.xls
-- sheet: 遗迹星级
-- ------------------------------


local relic_star_info = {
	[1] = {
		['explorePoint'] = 10,
		['cash'] = 5000,
		['grade'] = 15,
		['explore_consume_power'] = 0,
		['explore_consume_cash'] = 0,
		['explore_consume_diamond'] = 0,
		['explore_consume_power_m'] = 0,
	},
	[2] = {
		['explorePoint'] = 30,
		['cash'] = 10000,
		['grade'] = 20,
		['explore_consume_power'] = 10,
		['explore_consume_cash'] = 30000,
		['explore_consume_diamond'] = 400,
		['explore_consume_power_m'] = 0,
	},
	[3] = {
		['explorePoint'] = 60,
		['cash'] = 20000,
		['grade'] = 30,
		['explore_consume_power'] = 10,
		['explore_consume_cash'] = 100000,
		['explore_consume_diamond'] = 500,
		['explore_consume_power_m'] = 0,
	},
	[4] = {
		['explorePoint'] = 100,
		['cash'] = 37500,
		['grade'] = 40,
		['explore_consume_power'] = 10,
		['explore_consume_cash'] = 200000,
		['explore_consume_diamond'] = 800,
		['explore_consume_power_m'] = 0,
	},
	[5] = {
		['explorePoint'] = 150,
		['cash'] = 60000,
		['grade'] = 50,
		['explore_consume_power'] = 10,
		['explore_consume_cash'] = 300000,
		['explore_consume_diamond'] = 800,
		['explore_consume_power_m'] = 0,
	},
	[6] = {
		['explorePoint'] = 200,
		['cash'] = 80000,
		['grade'] = 60,
		['explore_consume_power'] = 10,
		['explore_consume_cash'] = 500000,
		['explore_consume_diamond'] = 1200,
		['explore_consume_power_m'] = 0,
	},
	[7] = {
		['explorePoint'] = 250,
		['cash'] = 100000,
		['grade'] = 60,
		['explore_consume_power'] = 10,
		['explore_consume_cash'] = 1000000,
		['explore_consume_diamond'] = 1500,
		['explore_consume_power_m'] = 0,
	},
	[8] = {
		['explorePoint'] = 0,
		['cash'] = 0,
		['grade'] = 0,
		['explore_consume_power'] = 10,
		['explore_consume_cash'] = 2000000,
		['explore_consume_diamond'] = 1500,
		['explore_consume_power_m'] = 0,
	},
}

return relic_star_info