-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口config.xls
-- sheet: 港口建筑
-- ------------------------------


local build_info = {
	[1] = {
		['name'] = T('酒  馆'),
		['icon'] = '#main_wood_tavern.png',
		['explain'] = T('酒馆是休闲娱乐的场所，优秀的航海士常在这里聚集'),
	},
	[2] = {
		['name'] = T('交易所'),
		['icon'] = '#main_wood_market.png',
		['explain'] = T('商品货物需要在交易所贩卖来获取利润'),
	},
	[3] = {
		['name'] = T('船  厂'),
		['icon'] = '#main_wood_shipyard.png',
		['explain'] = T('船舶建造和装配研究'),
	},
	[4] = {
		['name'] = T('市政厅'),
		['icon'] = '#main_wood_cityhall.png',
		['explain'] = T('城市的管理机构，影响整个城市的兴旺和繁荣'),
	},
	[5] = {
		['name'] = T('码  头'),
		['icon'] = '',
		['explain'] = T('船舶停靠点，忙碌的水手正在为你准备下一次航行的补给'),
	},
	[6] = {
		['name'] = T('功能建筑'),
		['icon'] = '',
		['explain'] = T('开放本港口的建筑按钮，包括造船厂、市政厅、酒馆、交易所等。'),
	},
	[7] = {
		['name'] = T('舰  队'),
		['icon'] = '#main_wood_fleet.png',
		['explain'] = '',
	},
	[8] = {
		['name'] = T('商  会'),
		['icon'] = '#main_wood_guild.png',
		['explain'] = '',
	},
}

return build_info