-- ------------------------------
-- desc: generated by xls2data.py
-- source: config.xls
-- sheet: 需求品
-- ------------------------------


local goods_info = {
	[1] = {
		['name'] = T('艺术品'),
		['res'] = 'port_cargo_169.png',
	},
	[2] = {
		['name'] = T('食物'),
		['res'] = 'port_cargo_143.png',
	},
	[3] = {
		['name'] = T('纺织品'),
		['res'] = 'port_cargo_127.png',
	},
	[4] = {
		['name'] = T('香料'),
		['res'] = 'port_cargo_158.png',
	},
	[5] = {
		['name'] = T('奢侈品'),
		['res'] = 'port_cargo_258.png',
	},
	[6] = {
		['name'] = T('工业品'),
		['res'] = 'port_cargo_133.png',
	},
	[7] = {
		['name'] = T('嗜好品'),
		['res'] = 'port_cargo_106.png',
	},
}

return goods_info