-- ------------------------------
-- desc: generated by xls2data.py
-- source: 市政工作配置表.xlsx
-- sheet: 市政工作
-- ------------------------------


local municipal_work = {
	[1] = {
		['star'] = 1,
		['title'] = T('城市送信'),
		['res'] = 'cityhall_task_paper.png',
		['details'] = T('总督有封加急的信件，船长能代跑一趟吗？'),
		['food'] = 200,
		['exp'] = 600,
		['time'] = 1200,
		['rewards'] = 'reward_szgz_star1',
	},
	[2] = {
		['star'] = 1,
		['title'] = T('整理文书'),
		['res'] = 'cityhall_task_book.png',
		['details'] = T('知识渊博的船长，能麻烦你把市政厅里的书籍分类放好吗？'),
		['food'] = 200,
		['exp'] = 600,
		['time'] = 1200,
		['rewards'] = 'reward_szgz_star1',
	},
	[3] = {
		['star'] = 2,
		['title'] = T('城市建设'),
		['res'] = 'cityhall_task_build.png',
		['details'] = T('我们需要把城市建设的更加适于居住,希望能得到你的帮助。'),
		['food'] = 400,
		['exp'] = 1200,
		['time'] = 2400,
		['rewards'] = 'reward_szgz_star2',
	},
	[4] = {
		['star'] = 3,
		['title'] = T('维护治安'),
		['res'] = 'cityhall_task_order.png',
		['details'] = T('英勇的船长，近来城市各地有海盗作乱，能否帮帮我们？'),
		['food'] = 600,
		['exp'] = 1800,
		['time'] = 3600,
		['rewards'] = 'reward_szgz_star3',
	},
}

return municipal_work