-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口config.xls
-- sheet: 港口特效
-- ------------------------------


local portEffect = {
	[1] = {
		['name'] = T('喷泉'),
		['anim'] = nil,
		['effect'] = 'tx_penquan',
	},
	[2] = {
		['name'] = 'XX',
		['anim'] = {res="port_role12_%d.png",count=12},
		['effect'] = '',
	},
	[3] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[4] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[5] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[6] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[7] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[8] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[9] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[10] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[11] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[12] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[13] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[14] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[15] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[16] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[17] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
	[18] = {
		['name'] = '',
		['anim'] = nil,
		['effect'] = '',
	},
}

return portEffect