-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口config.xls
-- sheet: 港口类型
-- ------------------------------


local port_type_info = {
	['market'] = {
		['name'] = T('商业城市'),
		['reward'] = T('商业投资：可解锁高利润特产'),
		['stronghold_award'] = 'common_item_essence.png',
		['award_icon'] = 55,
		['award_name'] = T('宝物精华'),
	},
	['ship'] = {
		['name'] = T('工业城市'),
		['reward'] = T('工业投资：可解锁新的船只'),
		['stronghold_award'] = 'material_iron_1.png',
		['award_icon'] = 65,
		['award_name'] = T('升级材料'),
	},
	['pub'] = {
		['name'] = T('文化城市'),
		['reward'] = T('文化投资：可获得航海士信物'),
		['stronghold_award'] = 'common_icon_honour.png',
		['award_icon'] = 85,
		['award_name'] = T('朗姆酒'),
	},
}

return port_type_info