-- ------------------------------
-- desc: generated by xls2data.py
-- source: share_config.xls
-- sheet: Sheet1
-- ------------------------------


sharelimit_info = {
	[1] = {
		['sailor'] = 2600,
		['goods'] = 5400,
	},
}
