-- ------------------------------
-- desc: generated by xls2data.py
-- source: 主角基础技能.xlsx
-- sheet: attrs_role
-- ------------------------------


local attrs_role = {
	[1] = {
		['role_id'] = 1,
		['attr'] = T('暴击率+4%'),
		['level_limit'] = 10,
		['icon'] = 'skill_1036.png',
		['desc'] = T('暴击率+4%'),
	},
	[2] = {
		['role_id'] = 1,
		['attr'] = T('抗暴率+4%'),
		['level_limit'] = 20,
		['icon'] = 'skill_1007.png',
		['desc'] = T('抗暴率+4%'),
	},
	[3] = {
		['role_id'] = 1,
		['attr'] = T('命中率+4%'),
		['level_limit'] = 30,
		['icon'] = 'skill_1043.png',
		['desc'] = T('命中率+4%'),
	},
	[4] = {
		['role_id'] = 1,
		['attr'] = T('闪避率+4%'),
		['level_limit'] = 40,
		['icon'] = 'skill_1035.png',
		['desc'] = T('闪避率+4%'),
	},
	[5] = {
		['role_id'] = 1,
		['attr'] = T('暴击率+6%'),
		['level_limit'] = 45,
		['icon'] = 'skill_1036.png',
		['desc'] = T('暴击率+6%'),
	},
	[6] = {
		['role_id'] = 1,
		['attr'] = T('抗暴率+6%'),
		['level_limit'] = 50,
		['icon'] = 'skill_1007.png',
		['desc'] = T('抗暴率+6%'),
	},
	[7] = {
		['role_id'] = 1,
		['attr'] = T('命中率+6%'),
		['level_limit'] = 55,
		['icon'] = 'skill_1043.png',
		['desc'] = T('命中率+6%'),
	},
	[8] = {
		['role_id'] = 1,
		['attr'] = T('闪避率+6%'),
		['level_limit'] = 60,
		['icon'] = 'skill_1035.png',
		['desc'] = T('闪避率+6%'),
	},
	[9] = {
		['role_id'] = 2,
		['attr'] = T('暴击率+4%'),
		['level_limit'] = 10,
		['icon'] = 'skill_1036.png',
		['desc'] = T('暴击率+4%'),
	},
	[10] = {
		['role_id'] = 2,
		['attr'] = T('抗暴率+4%'),
		['level_limit'] = 20,
		['icon'] = 'skill_1007.png',
		['desc'] = T('抗暴率+4%'),
	},
	[11] = {
		['role_id'] = 2,
		['attr'] = T('命中率+4%'),
		['level_limit'] = 30,
		['icon'] = 'skill_1043.png',
		['desc'] = T('命中率+4%'),
	},
	[12] = {
		['role_id'] = 2,
		['attr'] = T('闪避率+4%'),
		['level_limit'] = 40,
		['icon'] = 'skill_1035.png',
		['desc'] = T('闪避率+4%'),
	},
	[13] = {
		['role_id'] = 2,
		['attr'] = T('暴击率+6%'),
		['level_limit'] = 45,
		['icon'] = 'skill_1036.png',
		['desc'] = T('暴击率+6%'),
	},
	[14] = {
		['role_id'] = 2,
		['attr'] = T('抗暴率+6%'),
		['level_limit'] = 50,
		['icon'] = 'skill_1007.png',
		['desc'] = T('抗暴率+6%'),
	},
	[15] = {
		['role_id'] = 2,
		['attr'] = T('命中率+6%'),
		['level_limit'] = 55,
		['icon'] = 'skill_1043.png',
		['desc'] = T('命中率+6%'),
	},
	[16] = {
		['role_id'] = 2,
		['attr'] = T('闪避率+6%'),
		['level_limit'] = 60,
		['icon'] = 'skill_1035.png',
		['desc'] = T('闪避率+6%'),
	},
	[17] = {
		['role_id'] = 3,
		['attr'] = T('暴击率+4%'),
		['level_limit'] = 10,
		['icon'] = 'skill_1036.png',
		['desc'] = T('暴击率+4%'),
	},
	[18] = {
		['role_id'] = 3,
		['attr'] = T('抗暴率+4%'),
		['level_limit'] = 20,
		['icon'] = 'skill_1007.png',
		['desc'] = T('抗暴率+4%'),
	},
	[19] = {
		['role_id'] = 3,
		['attr'] = T('命中率+4%'),
		['level_limit'] = 30,
		['icon'] = 'skill_1043.png',
		['desc'] = T('命中率+4%'),
	},
	[20] = {
		['role_id'] = 3,
		['attr'] = T('闪避率+4%'),
		['level_limit'] = 40,
		['icon'] = 'skill_1035.png',
		['desc'] = T('闪避率+4%'),
	},
	[21] = {
		['role_id'] = 3,
		['attr'] = T('暴击率+6%'),
		['level_limit'] = 45,
		['icon'] = 'skill_1036.png',
		['desc'] = T('暴击率+6%'),
	},
	[22] = {
		['role_id'] = 3,
		['attr'] = T('抗暴率+6%'),
		['level_limit'] = 50,
		['icon'] = 'skill_1007.png',
		['desc'] = T('抗暴率+6%'),
	},
	[23] = {
		['role_id'] = 3,
		['attr'] = T('命中率+6%'),
		['level_limit'] = 55,
		['icon'] = 'skill_1043.png',
		['desc'] = T('命中率+6%'),
	},
	[24] = {
		['role_id'] = 3,
		['attr'] = T('闪避率+6%'),
		['level_limit'] = 60,
		['icon'] = 'skill_1035.png',
		['desc'] = T('闪避率+6%'),
	},
}

return attrs_role