-- ------------------------------
-- desc: generated by xls2data.py
-- source: 主角基础技能.xlsx
-- sheet: skill_desc
-- ------------------------------


local base_skill_desc = {
	[1] = {
		['name'] = T('炮术'),
		['attr'] = T('远程攻击'),
		['icon'] = 'partner_skill_far.png',
		['desc'] = T('随着等级的提升，提高火炮的远程攻击力。'),
	},
	[2] = {
		['name'] = T('剑术'),
		['attr'] = T('近战攻击'),
		['icon'] = 'partner_skill_near.png',
		['desc'] = T('随着等级的提升，提高肉搏战时的近战攻击力。'),
	},
	[3] = {
		['name'] = T('防御'),
		['attr'] = T('船只防御'),
		['icon'] = 'partner_skill_defense.png',
		['desc'] = T('随着等级的提升，减少敌方远程和近战对自己造成的伤害。'),
	},
	[4] = {
		['name'] = T('铁甲'),
		['attr'] = T('船只耐久'),
		['icon'] = 'partner_skill_hp.png',
		['desc'] = T('随着等级的提升，增加船舶耐久度。'),
	},
}

return base_skill_desc