-- ------------------------------
-- desc: generated by xls2data.py
-- source: 主角基础技能.xlsx
-- sheet: base_skill_gen
-- ------------------------------


local base_skill_gen = {
	[1] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[2] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[3] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[4] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[5] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[6] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[7] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[8] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[9] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[10] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[11] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[12] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[13] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[14] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[15] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[16] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[17] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[18] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[19] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[20] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[21] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[22] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[23] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[24] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[25] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[26] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[27] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[28] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[29] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[30] = {
		['sin_exp'] = 2,
		['coin_consume'] = 70000,
		['exp_consume'] = 45,
	},
	[31] = {
		['sin_exp'] = 3,
		['coin_consume'] = 100000,
		['exp_consume'] = 68,
	},
	[32] = {
		['sin_exp'] = 3,
		['coin_consume'] = 110000,
		['exp_consume'] = 68,
	},
	[33] = {
		['sin_exp'] = 4,
		['coin_consume'] = 150000,
		['exp_consume'] = 90,
	},
	[34] = {
		['sin_exp'] = 4,
		['coin_consume'] = 160000,
		['exp_consume'] = 90,
	},
	[35] = {
		['sin_exp'] = 4,
		['coin_consume'] = 160000,
		['exp_consume'] = 90,
	},
	[36] = {
		['sin_exp'] = 4,
		['coin_consume'] = 170000,
		['exp_consume'] = 90,
	},
	[37] = {
		['sin_exp'] = 4,
		['coin_consume'] = 180000,
		['exp_consume'] = 90,
	},
	[38] = {
		['sin_exp'] = 5,
		['coin_consume'] = 230000,
		['exp_consume'] = 113,
	},
	[39] = {
		['sin_exp'] = 5,
		['coin_consume'] = 240000,
		['exp_consume'] = 113,
	},
	[40] = {
		['sin_exp'] = 5,
		['coin_consume'] = 250000,
		['exp_consume'] = 113,
	},
	[41] = {
		['sin_exp'] = 6,
		['coin_consume'] = 310000,
		['exp_consume'] = 135,
	},
	[42] = {
		['sin_exp'] = 6,
		['coin_consume'] = 330000,
		['exp_consume'] = 135,
	},
	[43] = {
		['sin_exp'] = 6,
		['coin_consume'] = 340000,
		['exp_consume'] = 135,
	},
	[44] = {
		['sin_exp'] = 8,
		['coin_consume'] = 470000,
		['exp_consume'] = 180,
	},
	[45] = {
		['sin_exp'] = 8,
		['coin_consume'] = 490000,
		['exp_consume'] = 180,
	},
	[46] = {
		['sin_exp'] = 8,
		['coin_consume'] = 510000,
		['exp_consume'] = 180,
	},
	[47] = {
		['sin_exp'] = 10,
		['coin_consume'] = 670000,
		['exp_consume'] = 225,
	},
	[48] = {
		['sin_exp'] = 10,
		['coin_consume'] = 690000,
		['exp_consume'] = 225,
	},
	[49] = {
		['sin_exp'] = 10,
		['coin_consume'] = 720000,
		['exp_consume'] = 225,
	},
	[50] = {
		['sin_exp'] = 12,
		['coin_consume'] = 900000,
		['exp_consume'] = 270,
	},
	[51] = {
		['sin_exp'] = 12,
		['coin_consume'] = 940000,
		['exp_consume'] = 270,
	},
	[52] = {
		['sin_exp'] = 12,
		['coin_consume'] = 980000,
		['exp_consume'] = 270,
	},
	[53] = {
		['sin_exp'] = 15,
		['coin_consume'] = 1270000,
		['exp_consume'] = 338,
	},
	[54] = {
		['sin_exp'] = 15,
		['coin_consume'] = 1330000,
		['exp_consume'] = 338,
	},
	[55] = {
		['sin_exp'] = 18,
		['coin_consume'] = 1660000,
		['exp_consume'] = 405,
	},
	[56] = {
		['sin_exp'] = 18,
		['coin_consume'] = 1730000,
		['exp_consume'] = 405,
	},
	[57] = {
		['sin_exp'] = 20,
		['coin_consume'] = 2000000,
		['exp_consume'] = 450,
	},
	[58] = {
		['sin_exp'] = 20,
		['coin_consume'] = 2080000,
		['exp_consume'] = 450,
	},
	[59] = {
		['sin_exp'] = 22,
		['coin_consume'] = 2380000,
		['exp_consume'] = 495,
	},
	[60] = {
		['sin_exp'] = 25,
		['coin_consume'] = 2820000,
		['exp_consume'] = 563,
	},
	[61] = {
		['sin_exp'] = 26,
		['coin_consume'] = 3050000,
		['exp_consume'] = 585,
	},
	[62] = {
		['sin_exp'] = 28,
		['coin_consume'] = 3420000,
		['exp_consume'] = 630,
	},
	[63] = {
		['sin_exp'] = 30,
		['coin_consume'] = 3820000,
		['exp_consume'] = 675,
	},
	[64] = {
		['sin_exp'] = 32,
		['coin_consume'] = 4240000,
		['exp_consume'] = 720,
	},
	[65] = {
		['sin_exp'] = 34,
		['coin_consume'] = 4700000,
		['exp_consume'] = 765,
	},
	[66] = {
		['sin_exp'] = 36,
		['coin_consume'] = 5180000,
		['exp_consume'] = 810,
	},
	[67] = {
		['sin_exp'] = 38,
		['coin_consume'] = 5690000,
		['exp_consume'] = 855,
	},
	[68] = {
		['sin_exp'] = 40,
		['coin_consume'] = 6240000,
		['exp_consume'] = 900,
	},
	[69] = {
		['sin_exp'] = 45,
		['coin_consume'] = 7310000,
		['exp_consume'] = 1013,
	},
	[70] = {
		['sin_exp'] = 50,
		['coin_consume'] = 8460000,
		['exp_consume'] = 1125,
	},
}

return base_skill_gen