-- ------------------------------
-- desc: generated by xls2data.py
-- source: role.xls
-- sheet: 角色
-- ------------------------------


local role_info = {
	[1] = {
		['name'] = T('拉娜亚'),
		['sex'] = 1,
		['job_atr'] = T('控制削弱'),
		['job_difficulty'] = 2,
		['bigicon'] = 'ui/role_pic/role_pic_1.png',
		['res'] = 'ui/seaman/seaman_101.png',
		['id'] = 101,
		['job_id'] = 1,
		['Skills'] = {5101, 5301, 5201, 5501, 5102, 5302, 5202, 5502, 5103, 5303, 5203, 5503},
		['detailed_des'] = T('热爱冒险的伊比利亚公国贵族，从小就憧憬成为一名伟大的航海家。他接受亨利王子的委托，前往世界尽头，展开他的奇幻冒险之旅。'),
	},
	[2] = {
		['name'] = T('耐维摩尔'),
		['sex'] = 0,
		['job_atr'] = T('远程群攻'),
		['job_difficulty'] = 1,
		['bigicon'] = 'ui/role_pic/role_pic_2.png',
		['res'] = 'ui/seaman/seaman_102.png',
		['id'] = 102,
		['job_id'] = 2,
		['Skills'] = {3101, 3201, 3301, 3501, 3102, 3202, 3302, 3502, 3103, 3203, 3303, 3503},
		['detailed_des'] = T('大明贵族遗孤，逃亡至伊比利亚公国。接受了亨利王子的邀请，成为伊比利亚公国的一名海军下士，前往世界尽头，寻找海洋尽头的答案。'),
	},
	[3] = {
		['name'] = T('阿卡莎'),
		['sex'] = 1,
		['job_atr'] = T('高速近战'),
		['job_difficulty'] = 3,
		['bigicon'] = 'ui/role_pic/role_pic_3.png',
		['res'] = 'ui/seaman/seaman_103.png',
		['id'] = 103,
		['job_id'] = 3,
		['Skills'] = {4101, 4301, 4201, 4501, 4102, 4302, 4202, 4502, 4103, 4303, 4203, 4503},
		['detailed_des'] = T('生性放浪不羁，唯独钟情冒险。听闻世界尽头的传说之后便深深的着迷，借助亨利王子的力量，前往世界尽头，一睹海洋之神的风采。'),
	},
}

return role_info