return 
{
[1] = {
    ['ai_id'] = {
        },
    ['boat_damage'] = 0,
    ['fireClose'] = 0,
    ['goods_plunder'] = 0,
    ['gun_range1'] = 0,
    ['gun_range2'] = 0,
    ['gun_range3'] = 0,
    ['gun_value1'] = 0,
    ['gun_value2'] = 0,
    ['gun_value3'] = 0,
    ['is_leader'] = 1,
    ['is_player'] = 1,
    ['max_hp'] = 0,
    ['max_sh'] = 0,
    ['miss_attack'] = 0,
    ['name'] = '',
    ['rota'] = 3,
    ['sailor_id'] = 0,
    ['ship_id'] = 11,
    ['speed'] = 0,
    ['speed_control'] = 0,
    ['tag'] = T('玩家'),
    ['team_id'] = 1,
    ['turn_speed'] = 0,
    ['walk_Id'] = 3,
    ['x'] = 250,
    ['y'] = 800,
    },
[2] = {
    ['ai_id'] = {
        [1] = 14,
        [2] = 22,
        },
    ['boat_damage'] = 0,
    ['fireClose'] = 400,
    ['goods_plunder'] = 0,
    ['gun_range1'] = 200,
    ['gun_range2'] = 250,
    ['gun_range3'] = 300,
    ['gun_value1'] = 500,
    ['gun_value2'] = 400,
    ['gun_value3'] = 300,
    ['is_leader'] = 1,
    ['is_player'] = 0,
    ['max_hp'] = 10000,
    ['max_sh'] = 10000,
    ['miss_attack'] = 100,
    ['name'] = T('文雯'),
    ['rota'] = 7,
    ['sailor_id'] = 67,
    ['ship_id'] = 8,
    ['speed'] = 900,
    ['speed_control'] = 200,
    ['tag'] = T('di一'),
    ['team_id'] = 2,
    ['turn_speed'] = 200,
    ['walk_Id'] = 3,
    ['x'] = 600,
    ['y'] = 800,
    },
}