-- ------------------------------
-- desc: generated by xls2data.py
-- source: share.xlsx
-- sheet: 微信
-- ------------------------------


local share_info_wechat = {
	['friend_invite'] = {
		['title'] = T('船长快来！'),
		['desc'] = T('快来和我一起玩《全民大航海》吧，你带我经商，我带你打劫！'),
		['url'] = 'https://game.weixin.qq.com/cgi-bin/h5/static/gamecenter/detail.html?appid=wxa228fbbb06c2cb79',
		['scene'] = 0,
		['img_url'] = 'res/sdk_share/icon.png',
		['media_tag_name'] = 'MSG_INVITE',
		['message_ext'] = '',
		['act'] = '',
	},
	['friend_heart'] = {
		['title'] = T('嘿，船长！'),
		['desc'] = T('我在《全民大航海》里面赠送你红包啦，快去试试手气吧~'),
		['url'] = 'https://game.weixin.qq.com/cgi-bin/h5/static/gamecenter/detail.html?appid=wxa228fbbb06c2cb79',
		['scene'] = 0,
		['img_url'] = 'res/sdk_share/icon.png',
		['media_tag_name'] = 'MSG_heart_send',
		['message_ext'] = '',
		['act'] = '',
	},
	['friend_recall'] = {
		['title'] = T('呜~出发啦！'),
		['desc'] = T('船长，快回来！这里给你准备了一份回归大礼包喔~'),
		['url'] = 'https://game.weixin.qq.com/cgi-bin/h5/static/gamecenter/detail.html?appid=wxa228fbbb06c2cb79',
		['scene'] = 0,
		['img_url'] = 'res/sdk_share/icon.png',
		['media_tag_name'] = 'MSG_FRIEND_RECALL_HYZH',
		['message_ext'] = '',
		['act'] = '',
	},
}

return share_info_wechat