-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 每日28
-- ------------------------------


local arena_stage_reward_day_28 = {
	['1'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 180,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 220,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 200000,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 300000,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 440000,
		['rate'] = 100,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 660000,
		['rate'] = 100,
		['memo'] = '',
	},
	['7'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 1000000,
		['rate'] = 100,
		['memo'] = '',
	},
	['8'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 1500000,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_day_28