-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 传奇结束2
-- ------------------------------


local arena_stage_reward_legend_end_2 = {
	['1'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 2000,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 1800,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 1500,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 1200,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 1000,
		['rate'] = 100,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 800,
		['rate'] = 100,
		['memo'] = '',
	},
	['7'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 600,
		['rate'] = 100,
		['memo'] = '',
	},
	['8'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 500,
		['rate'] = 100,
		['memo'] = '',
	},
	['9'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 400,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_legend_end_2