-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场赛季奖励表(前端).xlsx
-- sheet: arena_season_reward_1
-- ------------------------------


local arena_season_reward_1 = {
	[1] = {
		['reward'] = {{icon = "equip_icon_615.png", name = T("五级船舶宝物"), count = 1, quality =4}},
	},
	[2] = {
		['reward'] = {{icon = "equip_icon_612.png", name = T("四级船舶宝物"), count = 3, quality =3}},
	},
	[3] = {
		['reward'] = {{icon = "equip_icon_612.png", name = T("四级船舶宝物"), count = 3, quality =3}},
	},
	[4] = {
		['reward'] = {{icon = "equip_icon_612.png", name = T("四级船舶宝物"), count = 2, quality =3}},
	},
	[5] = {
		['reward'] = {{icon = "equip_icon_612.png", name = T("四级船舶宝物"), count = 2, quality =3}},
	},
	[6] = {
		['reward'] = {{icon = "equip_icon_612.png", name = T("四级船舶宝物"), count = 1, quality =3}},
	},
	[7] = {
		['reward'] = {{icon = "equip_icon_612.png", name = T("四级船舶宝物"), count = 1, quality =3}},
	},
	[8] = {
		['reward'] = {{icon = "equip_icon_612.png", name = T("四级船舶宝物"), count = 1, quality =3}},
	},
	[9] = {
		['reward'] = {{icon = "equip_icon_612.png", name = T("四级船舶宝物"), count = 1, quality =3}},
	},
}

return arena_season_reward_1