-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 传奇结束3
-- ------------------------------


local arena_stage_reward_legend_end_3 = {
	['1'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 40,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 35,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 30,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 25,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 20,
		['rate'] = 100,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 15,
		['rate'] = 100,
		['memo'] = '',
	},
	['7'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 12,
		['rate'] = 100,
		['memo'] = '',
	},
	['8'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 10,
		['rate'] = 100,
		['memo'] = '',
	},
	['9'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 8,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_legend_end_3