-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 每日17
-- ------------------------------


local arena_stage_reward_day_17 = {
	['1'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 54,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 54,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 54,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 54,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 54,
		['rate'] = 100,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'item',
		['id'] = 106,
		['cnt'] = 4,
		['rate'] = 100,
		['memo'] = '',
	},
	['7'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 20000,
		['rate'] = 100,
		['memo'] = '',
	},
	['8'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 30000,
		['rate'] = 100,
		['memo'] = '',
	},
	['9'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 44000,
		['rate'] = 100,
		['memo'] = '',
	},
	['10'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 66000,
		['rate'] = 100,
		['memo'] = '',
	},
	['11'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 100000,
		['rate'] = 100,
		['memo'] = '',
	},
	['12'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 150000,
		['rate'] = 100,
		['memo'] = '',
	},
	['13'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 54,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_day_17