-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 战斗失败奖励
-- ------------------------------


local arena_stage_fail_1 = {
	['1'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 20,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 20,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 20,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 20,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 20,
		['rate'] = 100,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 20,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_fail_1