-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 白金3
-- ------------------------------


local arena_stage_reward_19 = {
	['1'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 200,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 5,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_19