-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 每日32
-- ------------------------------


local arena_stage_reward_day_32 = {
	['1'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 180,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 130,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 100000,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 150000,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 220000,
		['rate'] = 100,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 330000,
		['rate'] = 100,
		['memo'] = '',
	},
	['7'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 500000,
		['rate'] = 100,
		['memo'] = '',
	},
	['8'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 750000,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_day_32