-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场赛季奖励表(前端).xlsx
-- sheet: arena_season_reward_2
-- ------------------------------


local arena_season_reward_2 = {
	[1] = {
		['reward'] = {{icon = "common_icon_diamond.png", name = T("钻石"), count = 2000, quality =0}},
	},
	[2] = {
		['reward'] = {{icon = "common_icon_diamond.png", name = T("钻石"), count = 1800, quality =0}},
	},
	[3] = {
		['reward'] = {{icon = "common_icon_diamond.png", name = T("钻石"), count = 1500, quality =0}},
	},
	[4] = {
		['reward'] = {{icon = "common_icon_diamond.png", name = T("钻石"), count = 1200, quality =0}},
	},
	[5] = {
		['reward'] = {{icon = "common_icon_diamond.png", name = T("钻石"), count = 1000, quality =0}},
	},
	[6] = {
		['reward'] = {{icon = "common_icon_diamond.png", name = T("钻石"), count = 800, quality =0}},
	},
	[7] = {
		['reward'] = {{icon = "common_icon_diamond.png", name = T("钻石"), count = 600, quality =0}},
	},
	[8] = {
		['reward'] = {{icon = "common_icon_diamond.png", name = T("钻石"), count = 500, quality =0}},
	},
	[9] = {
		['reward'] = {{icon = "common_icon_diamond.png", name = T("钻石"), count = 400, quality =0}},
	},
}

return arena_season_reward_2