-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 黄金2
-- ------------------------------


local arena_stage_reward_15 = {
	['1'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 150,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'item',
		['id'] = 211,
		['cnt'] = 4,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_15