-- ------------------------------
-- desc: generated by xls2data.py
-- source: arena_reward.xls
-- sheet: 奖励
-- ------------------------------


local arena_time_reward_info = {
	[1] = {
		['type'] = 'baowu',
		['need_point'] = 15,
		['goods_id'] = 114,
		['amount'] = 1,
	},
	[2] = {
		['type'] = 'gold',
		['need_point'] = 30,
		['goods_id'] = 0,
		['amount'] = 200,
	},
	[3] = {
		['type'] = 'baowu',
		['need_point'] = 60,
		['goods_id'] = 316,
		['amount'] = 1,
	},
	[4] = {
		['type'] = 'gold',
		['need_point'] = 90,
		['goods_id'] = 0,
		['amount'] = 400,
	},
	[5] = {
		['type'] = 'baowu',
		['need_point'] = 150,
		['goods_id'] = 218,
		['amount'] = 1,
	},
	[6] = {
		['type'] = 'gold',
		['need_point'] = 200,
		['goods_id'] = 0,
		['amount'] = 500,
	},
	[7] = {
		['type'] = 'item',
		['need_point'] = 280,
		['goods_id'] = 50,
		['amount'] = 100,
	},
	[8] = {
		['type'] = 'baowu',
		['need_point'] = 360,
		['goods_id'] = 119,
		['amount'] = 1,
	},
	[9] = {
		['type'] = 'gold',
		['need_point'] = 480,
		['goods_id'] = 0,
		['amount'] = 500,
	},
	[10] = {
		['type'] = 'item',
		['need_point'] = 600,
		['goods_id'] = 50,
		['amount'] = 100,
	},
	[11] = {
		['type'] = 'baowu',
		['need_point'] = 800,
		['goods_id'] = 326,
		['amount'] = 1,
	},
}

return arena_time_reward_info