-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场配置表.xlsx
-- sheet: 赛季结束奖励
-- ------------------------------


local arena_stage_legendend = {
	[1] = {
		['reward'] = 'arena_stage_reward_legend_end_1',
	},
	[2] = {
		['reward'] = 'arena_stage_reward_legend_end_2',
	},
	[3] = {
		['reward'] = 'arena_stage_reward_legend_end_3',
	},
	[4] = {
		['reward'] = 'arena_stage_reward_legend_end_3',
	},
	[5] = {
		['reward'] = 'arena_stage_reward_legend_end_3',
	},
	[6] = {
		['reward'] = 'arena_stage_reward_legend_end_3',
	},
}

return arena_stage_legendend