-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 传奇结束1
-- ------------------------------


local arena_stage_reward_legend_end_1 = {
	['1'] = {
		['type'] = 'reward',
		['id'] = 0,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'reward',
		['id'] = 0,
		['cnt'] = 3,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'reward',
		['id'] = 0,
		['cnt'] = 3,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'reward',
		['id'] = 0,
		['cnt'] = 2,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'reward',
		['id'] = 0,
		['cnt'] = 2,
		['rate'] = 100,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'reward',
		['id'] = 0,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
	},
	['7'] = {
		['type'] = 'reward',
		['id'] = 0,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
	},
	['8'] = {
		['type'] = 'reward',
		['id'] = 0,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
	},
	['9'] = {
		['type'] = 'reward',
		['id'] = 0,
		['cnt'] = 1,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_legend_end_1