-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 每日8
-- ------------------------------


local arena_stage_reward_day_8 = {
	['1'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 24,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 24,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 24,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 24,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 24,
		['rate'] = 100,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'item',
		['id'] = 106,
		['cnt'] = 2,
		['rate'] = 100,
		['memo'] = '',
	},
	['7'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 8000,
		['rate'] = 100,
		['memo'] = '',
	},
	['8'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 12000,
		['rate'] = 100,
		['memo'] = '',
	},
	['9'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 17600,
		['rate'] = 100,
		['memo'] = '',
	},
	['10'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 26400,
		['rate'] = 100,
		['memo'] = '',
	},
	['11'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 40000,
		['rate'] = 100,
		['memo'] = '',
	},
	['12'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 60000,
		['rate'] = 100,
		['memo'] = '',
	},
	['13'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 24,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_day_8