-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 每日31
-- ------------------------------


local arena_stage_reward_day_31 = {
	['1'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 180,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 150,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 120000,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 180000,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 264000,
		['rate'] = 100,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 396000,
		['rate'] = 100,
		['memo'] = '',
	},
	['7'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 600000,
		['rate'] = 100,
		['memo'] = '',
	},
	['8'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 900000,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_day_31