-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场奖励表.xls
-- sheet: 每日27
-- ------------------------------


local arena_stage_reward_day_27 = {
	['1'] = {
		['type'] = 'exp',
		['id'] = 0,
		['cnt'] = 180,
		['rate'] = 100,
		['memo'] = '',
	},
	['2'] = {
		['type'] = 'gold',
		['id'] = 0,
		['cnt'] = 250,
		['rate'] = 100,
		['memo'] = '',
	},
	['3'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 250000,
		['rate'] = 100,
		['memo'] = '',
	},
	['4'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 375000,
		['rate'] = 100,
		['memo'] = '',
	},
	['5'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 550000,
		['rate'] = 100,
		['memo'] = '',
	},
	['6'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 825000,
		['rate'] = 100,
		['memo'] = '',
	},
	['7'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 1250000,
		['rate'] = 100,
		['memo'] = '',
	},
	['8'] = {
		['type'] = 'cash',
		['id'] = 0,
		['cnt'] = 1875000,
		['rate'] = 100,
		['memo'] = '',
	},
}

return arena_stage_reward_day_27