-- ------------------------------
-- desc: generated by xls2data.py
-- source: 竞技场赛季奖励表(前端).xlsx
-- sheet: arena_season_reward_3
-- ------------------------------


local arena_season_reward_3 = {
	[1] = {
		['reward'] = {{icon = "common_item_crystal.png", name = T("海妖水晶"), count = 40, quality =4}},
	},
	[2] = {
		['reward'] = {{icon = "common_item_crystal.png", name = T("海妖水晶"), count = 35, quality =4}},
	},
	[3] = {
		['reward'] = {{icon = "common_item_crystal.png", name = T("海妖水晶"), count = 30, quality =4}},
	},
	[4] = {
		['reward'] = {{icon = "common_item_crystal.png", name = T("海妖水晶"), count = 25, quality =4}},
	},
	[5] = {
		['reward'] = {{icon = "common_item_crystal.png", name = T("海妖水晶"), count = 20, quality =4}},
	},
	[6] = {
		['reward'] = {{icon = "common_item_crystal.png", name = T("海妖水晶"), count = 15, quality =4}},
	},
	[7] = {
		['reward'] = {{icon = "common_item_crystal.png", name = T("海妖水晶"), count = 12, quality =4}},
	},
	[8] = {
		['reward'] = {{icon = "common_item_crystal.png", name = T("海妖水晶"), count = 10, quality =4}},
	},
	[9] = {
		['reward'] = {{icon = "common_item_crystal.png", name = T("海妖水晶"), count = 8, quality =4}},
	},
}

return arena_season_reward_3