-- ------------------------------
-- desc: generated by xls2data.py
-- source: 资源不足config.xls
-- sheet: 资源不足跳转框config
-- ------------------------------


local jump_info = {
	['DIAMOND_NOT_ENOUGH'] = {
		['title'] = T('钻石不足'),
		['main_panel_index'] = 2,
		['description'] = T('持有海神宝藏每天可获得钻石，商城也可以购买哦！'),
		['btn_info'] = {[1]={['text']=T("获取海神宝藏"),['event']="goGetMonthCard",['key']='VIP_PAGE'},[2]={['text']=T("商城"),['event']="goShopDiamond",['key']='SHOP_BUTTON'}},
	},
	['DIAMOND_NOT_ENOUGH_GOSHOP'] = {
		['title'] = T('钻石不足'),
		['main_panel_index'] = 2,
		['description'] = T('持有海神宝藏每天可获得钻石，商城也可以购买哦！'),
		['btn_info'] = {[1]={['text']=T("获取海神宝藏"),['event']="goGetMonthCard",['key']='VIP_PAGE'},[2]={['text']=T("充值"),['event']="goShopDiamond",['key']='SHOP_BUTTON'}},
	},
	['HONOUR_NOT_ENOUGH'] = {
		['title'] = T('朗姆酒不足'),
		['main_panel_index'] = 1,
		['description'] = T('商会仓库新增一批朗姆酒喔，快来试试吧！'),
		['btn_info'] = {[1]={['text']=T("商会仓库"),['event']="goGuildWarehouse",['key']='GUILD_DEPOT'}},
	},
	['POWER_NOT_ENOUGH'] = {
		['title'] = T('体力不足'),
		['main_panel_index'] = 2,
		['description'] = T('去商城购买，是获得体力最快的办法！'),
		['btn_info'] = {[1]={['text']=T("商城"),['event']="goShop",['key']='SHOP_BUTTON'},[2]={['text']=T("立即获得"),['event']="goGetPowerNow",['type']="orange"}},
	},
	['LETTER_NOT_ENOUGH'] = {
		['title'] = T('推荐信不足'),
		['main_panel_index'] = 3,
		['description'] = T('去交易所经商可以获得推荐信，商会仓库也可获得！'),
		['btn_info'] = {[1]={['text']=T("委任经商"),['event']="goAutoTrade",['key']='PORT_MARKET'},[2]={['text']=T("商会仓库"),['event']="goGuildWarehouse",['key']='GUILD_DEPOT'},[3]={['text']=T("每日礼包"),['event']="goWelfareGift",['key']='WELFARE_DAILY'}},
	},
	['CASH_NOT_ENOUGH'] = {
		['title'] = T('金币不足'),
		['main_panel_index'] = 2,
		['description'] = T('去交易所赚点钱再来吧，直接兑换也是不错的选择！'),
		['btn_info'] = {[1]={['text']=T("交易所"),['event']="goMarket",['key']='PORT_MARKET'},[2]={['text']=T("立即获得"),['event']="goGetCashNow",['type']="orange"}},
	},
	['PAPER_NOT_ENOUGH'] = {
		['title'] = T('图纸不足'),
		['main_panel_index'] = 1,
		['description'] = T('图纸在商城有售，快去购买吧！'),
		['btn_info'] = {[1]={['text']=T("商城"),['event']="goShop",['key']='SHOP_BUTTON'}},
	},
	['EXP_BOOK_NOT_ENOUGH'] = {
		['title'] = T('经验书不足'),
		['main_panel_index'] = 2,
		['description'] = T('完成藏宝海湾，或去商会仓库都可以获得经验书，去试试看吧！'),
		['btn_info'] = {[1]={['text']=T("藏宝海湾"),['event']="goFindBaowu",['key']='ORGANIZETEAM'},[2]={['text']=T("商会仓库"),['event']="goGuildWarehouse",['key']='GUILD_DEPOT'}},
	},
	['CHAPTER_STAR_NOT_ENOUGH'] = {
		['title'] = T('信物不足'),
		['main_panel_index'] = 1,
		['description'] = T('去酒馆解雇对应品阶航海士，可获得对应航海士信物。'),
		['btn_info'] = {[1]={['text']=T("解雇"),['event']="goFire",['key']='SAILOR_FIRE'}},
	},
	['NOBILITY_NOT_ENOUGH'] = {
		['title'] = T('爵位不足'),
		['main_panel_index'] = 1,
		['description'] = T('爵位不足，想办法获得更高级的爵位吧！'),
		['btn_info'] = {[1]={['text']=T("爵位提升"),['event']="goPeerage",['key']='PEERAGES'}},
	},
	['BAOWU_JINGHUA_NOT_ENOUGH'] = {
		['title'] = T('宝物精华不足'),
		['main_panel_index'] = 1,
		['description'] = T('点击以下按钮，可直接获取宝物精华。'),
		['btn_info'] = {[1]={['text']=T("立即获得"),['event']="goGetJinghuaNow",['type']="orange"}},
	},
	['CANGBAOTU_NOT_ENOUGH'] = {
		['title'] = T('藏宝图不足'),
		['main_panel_index'] = 1,
		['description'] = T('打捞藏宝海湾沉船,有机会获得藏宝图！'),
		['btn_info'] = {[1]={['text']=T("藏宝海湾"),['event']="goFindBaowu",['key']='ORGANIZETEAM'}},
	},
	['NOBILITY_EXP_NOT_ENOUGH'] = {
		['title'] = T('声望不足'),
		['main_panel_index'] = 1,
		['description'] = T('声望可通过魔瓶试炼、遗迹探索、港口投资获取。'),
		['btn_info'] = {[1]={['text']=T("魔瓶试炼"),['event']="gojingyingFight",['key']='ACTIVITY_ELITEBATTLE'}},
	},
	['HAMMER_NOT_ENOUGH'] = {
		['title'] = T('工匠锤不足'),
		['main_panel_index'] = 2,
		['description'] = T('工匠锤可以在造船厂商店购买，快去看看吧！'),
		['btn_info'] = {[1]={['text']=T("船厂商店"),['event']="goShipyardStore",['key']='PORT_SHIPYARD'},[2]={['text']=T("商城"),['event']="goShop",['key']='SHOP_BUTTON'}},
	},
	['CONTRIBUTE_NOT_ENOUGH'] = {
		['title'] = T('贡献不足'),
		['main_panel_index'] = 1,
		['description'] = T('贡献不足，进行商会捐献可获得。'),
		['btn_info'] = {[1]={['text']=T("商会捐献"),['event']="goToContribute",['key']='GUILD_DONATE'}},
	},
	['SKILL_BOOK_NOT_ENOUGH'] = {
		['title'] = T('技能书不足'),
		['main_panel_index'] = 1,
		['description'] = T('完成世界任务，可获得航海士技能书。'),
		['btn_info'] = {[1]={['text']=T("世界任务"),['event']="goWorldMission",['key']='WORLD_MISSION'}},
	},
	['SAILOR_BAOWU_NOT_ENOUGH'] = {
		['title'] = T('航海士宝物'),
		['main_panel_index'] = 2,
		['description'] = T('商会悬赏达到一定次数，商会仓库也可购买！'),
		['btn_info'] = {[1]={['text']=T("商会悬赏"),['event']="goGuildTask",['key']='PORT_HOTEL_TREAT'},[2]={['text']=T("商会仓库"),['event']="goGuildWarehouse",['key']='GUILD_DEPOT'}},
	},
	['MATERIAL_NOT_ENOUGH'] = {
		['title'] = T('材料不足'),
		['main_panel_index'] = 1,
		['description'] = T('造船所需材料在造船厂商店有售，快去购买吧！'),
		['btn_info'] = {[1]={['text']=T("船厂商店"),['event']="goShipyardStore", ['key']='PORT_SHIPYARD'}},
	},
	['MERMAID_TEARS_NOT_ENOUGH'] = {
		['title'] = T('人鱼之泪不足'),
		['main_panel_index'] = 2,
		['description'] = T('藏宝海湾挖宝可以获得！船厂商店或许也有货，船长可去看看！'),
		['btn_info'] = {[1]={['text']=T("藏宝海湾"),['event']="goFindBaowu",['key']='ORGANIZETEAM'},[2]={['text']=T("船厂商店"),['event']="goShipyardStore", ['key']='PORT_SHIPYARD'}},
	},
	['BREAKTHROUGH_NOT_ENOUGH'] = {
		['title'] = T('海妖水晶不足'),
		['main_panel_index'] = 2,
		['description'] = T('突破水晶不足，您可前往船厂商店、商城购买。'),
		['btn_info'] = {[1]={['text']=T("船厂商店"),['event']="goShipyardStore",['key']='PORT_SHIPYARD'},[2]={['text']=T("商城"),['event']="goShop",['key']='SHOP_BUTTON'}},
	},
	['HAMMER_TIPS'] = {
		['title'] = T('工匠锤'),
		['main_panel_index'] = 2,
		['description'] = T('工匠锤可以在造船厂商店、商城购买，快去看看吧！'),
		['btn_info'] = {[1]={['text']=T("船厂商店"),['event']="goShipyardStore",['key']='PORT_SHIPYARD'},[2]={['text']=T("商城"),['event']="goShop",['key']='SHOP_BUTTON'}},
	},
	['PAPER_TIPS'] = {
		['title'] = T('图纸不足'),
		['main_panel_index'] = 1,
		['description'] = T('图纸在商城有售，快去购买吧！'),
		['btn_info'] = {[1]={['text']=T("商城"),['event']="goShop",['key']='SHOP_BUTTON'}},
	},
	['BREAKTHROUGH_TIPS'] = {
		['title'] = T('海妖水晶'),
		['main_panel_index'] = 2,
		['description'] = T('珍贵的海妖水晶，您可前往船厂商店购买。'),
		['btn_info'] = {[1]={['text']=T("船厂商店"),['event']="goShipyardStore",['key']='PORT_SHIPYARD'},[2]={['text']=T("商城"),['event']="goShop",['key']='SHOP_BUTTON'}},
	},
	['POWER_NOT_ENOUGH_MARKET'] = {
		['title'] = T('体力不足'),
		['main_panel_index'] = 3,
		['description'] = T('体力不足时经商利润较低，确定要继续吗？'),
		['btn_info'] = {[1]={['text']=T("继续交易"),['event']="goContinue"},[2]={['text']=T("商城"),['event']="goShop",['key']='SHOP_BUTTON'},[3]={['text']=T("立即获得"),['event']="goGetPowerNow",['type']="orange"}},
	},
	['FEATHER_NOT_ENOUGH'] = {
		['title'] = T('传送之羽不足'),
		['main_panel_index'] = 2,
		['description'] = T('商城正在出售，快去看看吧！'),
		['btn_info'] = {[1]={['text']=T("商城"),['event']="goShop",['key']='SHOP_BUTTON'},[2]={['text']=T("立即获得"),['event']="goGetPowerNow",['type']="orange"}},
	},
	['SHIP_NOT_ENOUGH'] = {
		['title'] = T('船只不足'),
		['main_panel_index'] = 1,
		['description'] = T('无可用船只，前往造船厂可制造新船！'),
		['btn_info'] = {[1]={['text']=T("造船厂"),['event']="goShipyard", ['key']='PORT_SHIPYARD'}},
	},
	['SHIP_EQUIP_NOT_ENOUGH'] = {
		['title'] = T('船舶装备不足'),
		['main_panel_index'] = 1,
		['description'] = T('船舶装备不足，探索遗迹说不定会有收获！'),
		['btn_info'] = {[1]={['text']=T("遗迹探索"),['event']="goActivityEveryday",['key']='YIJI_EXPLORE'}},
	},
	['EXP_NOT_ENOUGH'] = {
		['title'] = T('经验不足'),
		['main_panel_index'] = 3,
		['description'] = T('经验可以让船长大人升级快速提升实力喔！'),
		['btn_info'] = {[1]={['text']=T("商会悬赏"),['event']="goGuildTask",['key']='PORT_HOTEL_TREAT'},[2]={['text']=T("遗迹探索"),['event']="goActivityEveryday",['key']='YIJI_EXPLORE'},[3]={['text']=T("交易所"),['event']="goMarket",['key']='PORT_MARKET'}},
	},
}

return jump_info